### ISSUE TITLE
TransformixImageFilter seems not to combine all specified transforms but only the last

### ISSUE THREAD

**Issue by romangrothausmann** [SuperElastix/SimpleElastix#102]
In order to register stack slices to each other, I accumulate transforms that TransformixImageFilter should apply:

https://github.com/romangrothausmann/elastix_scripts/blob/a0355994842ead30bd21435d5ac7fddf59a12723/recRegStack.py#L50

However, only the last transform map seems to be regarded by `stfx.Execute()`. For example changing `stfx.AddTransformParameterMap( selx.GetTransformParameterMap(0) )` to `stfx.SetTransformParameterMap( selx.GetTransformParameterMap(0) )` causes no difference in the test results (`make -C tests/recRegStack/`) even though the reported number of maps changes accordingly.

**Comment by PertuyF** [comment]
Hi @romangrothausmann 

I am not sure to understand precisely what you're looking for.
You have a stack of images and you want to register each slide to the previous one inside the stack, right?

Could you tell more on the purpose? (type of images? why do they need registration? is it rigid, affine or bspline registration?). That would help me understand what you need more precisely.

At first sight you only get the first parameter map of each registration with `selx.GetTransformParameterMap(0)`. If the transform is not very important, it is possible that changes in the result image is not easy to figure by eye.

Also note that using `(WriteResultImage "true")` in the parameter file allows you to apply the transform directy at the end of the registration, with no call to Transformix.
This way, if you get the result image with `selx.GetResultImage()`, you could use it as fixed image for the next registration, with no need to accumulate previous transforms.

Of course this solution may not be ideal for your case, but as I said, more information is needed.

**Comment by romangrothausmann** [comment]
Hi @PertuyF 

Thanks for looking into this. The issue is a remainder from the mailing-list communication we had end of last year. I am getting the results I expect with Your recommendation to register to the previously aligned image, using rigid transforms (https://github.com/romangrothausmann/elastix_scripts/blob/f10ac383226b36ac04aaed042f4b2944041cfaa2/tests/recRegStack/parameterFile.txt) on a few test images (https://github.com/romangrothausmann/elastix_scripts/tree/f10ac383226b36ac04aaed042f4b2944041cfaa2/tests/recRegStack results in https://github.com/romangrothausmann/elastix_scripts/tree/f10ac383226b36ac04aaed042f4b2944041cfaa2/tests/recRegStack/reg)
Implementation in the branch `reg2transformed_01`: https://github.com/romangrothausmann/elastix_scripts/blob/reg2transformed_01/recRegStack.py

However, this issue referes to @kaspermarstal suggestion (http://lists.bigr.nl/pipermail/elastix/2016-December/002433.html) to accumulate transform maps with SimpleTransformix (in branch `combT_01`: https://github.com/romangrothausmann/elastix_scripts/blob/combT_01/recRegStack.py), which leads to the described issue that apparently only the last transform map is used from a given map-stack. This approach seems more robust concerning slight mis-alignment between successive "raw" images, whereas the other way the mis-alignment between an aligned image towards the next "raw" images can become very large as transforms accumulate.

**Comment by PertuyF** [comment]
Well, if there is something not working as expected with `stfx.AddTransformParameterMap()` and if setting initial transform does not work (I know this one is tricky, had troubles too in some cases), there still is the `WeightedCombinationTransform` in Elastix. But I don't know if it is implemented in SimpleElastix, di you know that @kaspermarstal ?

Some explanations in case it is supported.
It relies on creating a new transform parameter with no initial transform, all transform parameters set to 1 (don't know if it is necessary, but it worked in my case), and all other info are the same as your current transform parameter file. Except that transform is different and it takes a couple of extra parameters as indicated in the [documentation](http://elastix.isi.uu.nl/doxygen/classelastix_1_1WeightedCombinationTransformElastix.html).
```
(Transform "WeightedCombinationTransform")
(HowToCombineTransforms "Add")  # could also be "Compose" to average the parameters
(Subtransforms "<paths_to_transformParametersFiles.0>" ... "<paths_to_transformParametersFiles.n>")
(NumberOfParameters <number_of_transformParameterFiles>)
(NormalizeCombinationWeights "true")  # not sure it is needed for "Add"
```
Maybe it could help.

**Comment by kaspermarstal** [comment]
@PertuyF Yes WeightCombinationTransform is implemented.

@romangrothausmann The difference between `SetTransformParameterMap` and `AddTransformParameterMap` is that `Set` overwrites (i.e. deletes) any existing parameter maps before setting the supplied parameter maps, while `Add` appends the supplied parameter maps to existing parameter maps (if any). 

If `AddTransformParameterMap` only uses the last transform parameter map then that is news to me. Will investigate. Would you be able to provide a minimum working example that reproduces this issue?

**Comment by romangrothausmann** [comment]
> Would you be able to provide a minimum working example that reproduces this issue?

Well, the link to the commit in the initial issue message is my minimum working example (including a test image series). 
Even though multiple maps are reported by `GetNumberOfTransformParameterMaps`, changing `AddTransformParameterMap` to `SetTransformParameterMap` does not change the output results (as I would expect if multiple maps had been taken into account before).

**Comment by PertuyF** [comment]
Couldn't it come from the fact that you are applying a transform that contains `(InitialTransformParametersFileName "NoInitialTransform")`? (Pretty sure it is the case for your files, it is the default when you use a single parameterFile for registration)
Will TransformiX apply transformParameterFiles that comes after that option @kaspermarstal ? I suspect that it will stop looking for any other file when getting this parameter.

An did you tried the `WeightedCombinationTransform` strategy @romangrothausmann ?

**Comment by romangrothausmann** [comment]
`"InitialTransformParametersFileName"` now removed (https://github.com/romangrothausmann/elastix_scripts/blob/859a74f5875dfc589dcac1e3d40f4e5d07c07743/recRegStack.py#L50) but this did not have any effect on the (wrong) results.

`WeightedCombinationTransform` is another option for a workaround, but does not solve the issue reported here, that TransformixImageFilter only applies the first transform even if multiple ones are given.

**Comment by romangrothausmann** [comment]
This problem now seems solved, at least my tests (branch "combT_01", https://github.com/romangrothausmann/elastix_scripts/tree/338251381ec56ace8ff81be101eb59871e20c0e7) now yield acceptable/expected results with SE@33a6bbb6 (see also #121).

**Comment by kaspermarstal** [comment]
Thanks for the feedback :)
