### ISSUE TITLE
elastix.log not written for multiple runs of SimpleElastix

### ISSUE THREAD

**Issue by romangrothausmann** [SuperElastix/SimpleElastix#104]
It seems when logging to file `LogToFileOn()` elastix.log is only written/updated for the first run of elastix `selx.Execute()` but not for any successive run, as happens e.g. here:
 https://github.com/romangrothausmann/elastix_scripts/blob/f10ac383226b36ac04aaed042f4b2944041cfaa2/recRegStack.py

Contrary, the logging to the console `LogToConsoleOn()` does contain logs from all runs.

**Comment by PertuyF** [comment]
Hi again @romangrothausmann :)

Isn't the `elastix.log` file overwritten for each execution? I don't remember.
I used to set `selx.LogToFolder(my_ouput_folder_path)` in order to direct the log file and create separate ones for different registrations, could you try it?

**Comment by romangrothausmann** [comment]
Thanks for Your feedback. It seems `LogToFolder` does not to exist (anymore) in SimpleElastix:
(https://github.com/SuperElastix/SimpleElastix/blob/d6eaa806dfc3edf8d51dcb2b42a3e9ed6383d4af/Code/Elastix/include/sitkElastixImageFilter.h)

```selx.LogToFolder("DNl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/SimpleElastix/lib/python/SimpleITK/SimpleITK.py", line 9756, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, ElastixImageFilter, name)
  File "/opt/SimpleElastix/lib/python/SimpleITK/SimpleITK.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'ElastixImageFilter' object has no attribute 'LogToFolder'
```
I also tried to specify a path with `SetLogFileName` but that is not accepted.

Using redirection of `stdout` makes parsing the logs (e.g. for final metric value) possible (https://github.com/romangrothausmann/elastix_scripts/commit/e9475c1bd7fff34bbd2447025cc151431836da8d), but that procedure is far from obvious.

**Comment by PertuyF** [comment]
I noticed that in the script you provided you use `selx.SetOutputDirectory()` to change the output directory for each registration.
Doesn't it create separated log files for each registration? (with each file written to the current output directory)

Sorry if it is a silly question, I can't test it by myself right now.

**Comment by romangrothausmann** [comment]
It only creates one log file the first time `selx.Execute()` is executed in the dir set by `selx.SetOutputDirectory()`. All successive runs do not create a log file nor apppend/overwrite the old one.

**Comment by kaspermarstal** [comment]
@romangrothausmann What happens if you specify a directory with `SetOutputDirectory` outside the loop and then a new filename for each iteration in the loop (e.g. elastix1.log, elastix2.log etc)?

**Comment by kaspermarstal** [comment]
This is most likely due to the elastix logger being a global static object, which is an unfortunate leftover from the time elastix was only a command line program. Closing since this is an elastix issue.

**Comment by j0nj0n** [comment]
I have found a solution to this problem by using subprocesses. 

```python
import subprocess

subprocess.call(['python', 'elastixSubProcess.py', fixedImagePath, movingImagePath, parameterFilePath, logsDirectory, resultImagePath])
```
This way the elastix.log writes itself in the logsDirectory directory. Using sys argv (example of elastixSubProcess.py)

```python
import sys
import simpleITK as sitk

fixedImagePath = sys.argv[1]
movingImagePath = sys.argv[2]
parameterFilePath = sys.argv[3]
logsDirectory = sys.argv[4]
resultImagePath = sys.argv[5]

elastixImageFilter.LogToFileOn()
elastixImageFilter.SetOutputDirectory(logsDirectory)
elastixImageFilter.Execute()
```

**Comment by romangrothausmann** [comment]
Thanks for sharing that idea and the instructions.

**Comment by zmani** [comment]
Hi, someone fixed this issue not using subprocesses?

**Comment by MarHHM** [comment]
> I have found a solution to this problem by using subprocesses.
> 
> ```python
> import subprocess
> 
> subprocess.call(['python', 'elastixSubProcess.py', fixedImagePath, movingImagePath, parameterFilePath, logsDirectory, resultImagePath])
> ```
> 
> This way the elastix.log writes itself in the logsDirectory directory. Using sys argv (example of elastixSubProcess.py)
> 
> ```python
> import sys
> import simpleITK as sitk
> 
> fixedImagePath = sys.argv[1]
> movingImagePath = sys.argv[2]
> parameterFilePath = sys.argv[3]
> logsDirectory = sys.argv[4]
> resultImagePath = sys.argv[5]
> 
> elastixImageFilter.LogToFileOn()
> elastixImageFilter.SetOutputDirectory(logsDirectory)
> elastixImageFilter.Execute()
> ```

That solved the issue. Thank you very much for sharing :)
