### ISSUE TITLE
Installation error at CMake/sitkSourceVersion.cmake:38 (include):   include could not find load file

### ISSUE THREAD

**Issue by robbendavid** [SuperElastix/SimpleElastix#105]
Hi, 
I'm trying to install SimpleElastix 0.10.0 on mac os x el capitan (10.11.5) following the instructions on the site. Installation goes well until I get the following error:

```
...
[ 76%] Completed 'elastix'
[ 76%] Built target elastix
Scanning dependencies of target SimpleITK
[ 78%] Creating directories for 'SimpleITK'
[ 79%] No download step for 'SimpleITK'
[ 82%] No patch step for 'SimpleITK'
[ 82%] No update step for 'SimpleITK'
[ 83%] Performing configure step for 'SimpleITK'
Not searching for unused variables given on the command line.
loading initial cache file /Users/drobbe1/Downloads/SimpleElastix/build/SimpleITK-build/CMakeCacheInit.txt
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMake/sitkSourceVersion.cmake:38 (include):
  include could not find load file:

    /Users/drobbe1/Downloads/SimpleElastix/SimpleElastix-0.10.0/CMake/sitkSourceVersionVars.cmake
Call Stack (most recent call first):
  Version.cmake:17 (include)
  CMakeLists.txt:25 (include)
```

Any idea on how to resolve this issue?

**Comment by kaspermarstal** [comment]
Hi, you should `git clone` the project, and not download the zip file. This error occurs because the `.git` directory is missing.

Are you not seeing this issue on the SimpleITK side @blowekamp? I have not seen any SimpleITK users mentioning this :)

**Comment by blowekamp** [comment]
Yes, if you download the Github repo archive SimpleITK will produce the same error.

To create the source packages for releases we use the following script:
https://github.com/SimpleITK/SimpleITK/blob/next/Utilities/Maintenance/SourceTarball.bash

Unfortunately, the behavior of Github producing a direct archive of repo, and users commonly using this has produced some problems.

Can you please create a SimpleITK issue, so we can discuss the proper behavior there?

**Comment by robbendavid** [comment]
Thank you for the quick follow-up! That indeed solved the issue.

For future reference, later in the installation I encountered another error "Problem with Symbol not found: __PyErr_ReplaceException" which is apparently related to Anaconda not working well together with virtual env. This is a known issue (https://github.com/conda/conda/issues/1367) and what solved it for me was downgrading the anaconda python to the same version as the system python (conda install python=2.7.10).

**Comment by kaspermarstal** [comment]
@blowekamp Yes of course!
