### ISSUE TITLE
transformix usage

### ISSUE THREAD

**Issue by franfcunha** [SuperElastix/SimpleElastix#107]
Hello,

I would like to ask you some specific doubt about using transformix.
I have a set of points that define a high-resolution field of view of a specific region on my fixed image and my goal is to determine the "correspondent" field of view coordinates in the moving image. After running elastix in a coarse-to-fine mode by increasing resolutions i run:
transformix -def [file with 16 index coordinates defining the FOV of the fixed image] -out [directory] -tp [final transformation file of the above explained workflow]

Am I doing it right? Or should the -def file include index coordinates of the moving image in order to correspond the fixed image?I am asking this because even changing drastically or not my parameter files during the registration workflow the correspondence obtained seems to be quite bad.

Sincerely,

**Comment by kaspermarstal** [comment]
You are doing it right. The transformation is defined from the fixed image to the moving image (see section 2.6 in the [manual](http://elastix.isi.uu.nl/download/elastix_manual_v4.8.pdf)), so points are warped from the fixed to the moving image. Make sure the file has "index" and not "point" in the first line as you are specifying index coordinates. 

Anecdotally, I have always given transformix points in world coordinates. I have found this to be more robust and easier to debug when something goes wrong.
