### ISSUE TITLE
Transforming 3D points using transformixImageFilter reads only first 2 dimensions

### ISSUE THREAD

**Issue by anna-ilina** [SuperElastix/SimpleElastix#109]
Hello,

I've registered two images using a RigidTransform with SimpleElastix, and now I'm trying to transform a set of points using the obtained transform. I'm testing with the fixedPoints.pts file from the SimpleElastix tutorial (pasted below).

point
3
102.8 -33.4 57.0
178.1 -10.9 14.5
180.4 -18.1 78.9

I use the following code to transform the points using my transform parameter file

import SimpleITK as sitk
transformParameterMap = sitk.ElastixImageFilter().ReadParameterFile("TransformParameters.0.txt")
transformixImageFilter = sitk.TransformixImageFilter()
transformixImageFilter.SetTransformParameterMap(transformParameterMap)
transformixImageFilter.SetFixedPointSetFileName("fixedPoints.pts")
transformixImageFilter.SetOutputDirectory("outputDirectory")
transformixImageFilter.Execute()

But the transformixImageFilter seems to only read the first two values of each point. My outputPoints.txt file is below.

Point	0	; InputIndex = [ 279 -10752 ]	; InputPoint = [ 102.800000 -33.400000 ]	; OutputIndexFixed = [ 279 -10751 ]	; OutputPoint = [ 102.816604 -33.416649 ]	; Deformation = [ 0.016604 -0.016649 ]
Point	1	; InputIndex = [ -57 -18493 ]	; InputPoint = [ 57.000000 178.100000 ]	; OutputIndexFixed = [ -56 -18492 ]	; OutputPoint = [ 57.036062 178.087564 ]	; Deformation = [ 0.036062 -0.012436 ]
Point	2	; InputIndex = [ -14 -12715 ]	; InputPoint = [ -10.900000 14.500000 ]	; OutputIndexFixed = [ -14 -12715 ]	; OutputPoint = [ -10.878989 14.493811 ]	; Deformation = [ 0.021011 -0.006189 ]

How can I specify to the transformixImageFilter that my input file contains 3D points not 2D?
Running the same input with command line transformix (transformix -def fixedPoints.pts -out outputDirectory -tp TransformParameters.0.txt) gives the desired result (reads all 3 x,z,y values for each point) but with transformixImageFilter it only reads the first two. My transform file is attached.
[TransformParameters.0.txt](https://github.com/SuperElastix/SimpleElastix/files/1144995/TransformParameters.0.txt)

**Comment by kaspermarstal** [comment]
This may be related to #113. Try to also set the moving image so that transformix may infer the dimensionality from that. Let me know how it goes!

**Comment by anna-ilina** [comment]
Yes, setting the moving image for the transformixImageFilter fixes it. Thanks! This might be useful to have in the SimpleElastix tutorial. :)

**Comment by kaspermarstal** [comment]
Good point :)
