### ISSUE TITLE
Out of date doc

### ISSUE THREAD

**Issue by toomanycats** [SuperElastix/SimpleElastix#110]
Hello,
I just installed SimpleITK via Anaconda for py3.5.

I'm not able to use the API as in the examples. Needless to say, I'm somewhat lost.
http://simpleelastix.readthedocs.io/NonRigidRegistration.html

example:
`elastixImageFilter = sitk.ElastixImageFilter()`

There no class ElastixImageFilter under sitk.

Thank you!
tmc

`
import SimpleITK as sitk

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(sitk.ReadImage("fixedImage.nii"))
elastixImageFilter.SetMovingImage(sitk.ReadImage("movingImage.nii"))

parameterMapVector = sitk.VectorOfParameterMap()
parameterMapVector.append(sitk.GetDefaultParameterMap("affine"))
parameterMapVector.append(sitk.GetDefaultParameterMap("bspline"))
elastixImageFilter.SetParameterMap(parameterMapVector)

elastixImageFilter.Execute()
sitk.WriteImage(elastixImageFilter.GetResultImage())
`

**Comment by PertuyF** [comment]
Hi @toomanycats ,

I think you missed the [first section](http://simpleelastix.readthedocs.io/GettingStarted.html) of the documentation.
SimpleElastiX is built as a fork of SimpleITK, and right now you can't install it from a repository. You will have to build the package from source using the instructions provided in the doc, install the package and then `import SimpleITK as sitk`.

**Comment by toomanycats** [comment]
I see I'll read that doc and try again. Closing.
