### ISSUE TITLE
Possible Error in example?

### ISSUE THREAD

**Issue by varghesealex90** [SuperElastix/SimpleElastix#111]
I was trying out the rigid registration example .

import SimpleITK as sitk
elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(sitk.SetFixedImage("fixedImage.nii"))

However I error 'module' object has no attribute 'SetFixedImage'

Should second line be elastixImageFilter.SetFixedImage(sitk.ReadImage("fixedImage.nii"))

**Comment by PertuyF** [comment]
You're right @varghesealex90 , fixed it, thanks!

@kaspermarstal I committed in `master`, but it seems develop is used to generate the the doc, right? So duplicated commit into `develop`...

**Comment by kaspermarstal** [comment]
@PertuyF yup! No problem, it should merge just fine.
