### ISSUE TITLE
Some issues in deformable registration of the expiration scan to the inspiration scan

### ISSUE THREAD

**Issue by duancaohui** [SuperElastix/SimpleElastix#112]
Deformable registration spatially aligns the expiration scan to the inspiration scan such that both share the same spatial geometry.

However, some problems has confused me about half years

1.image format
medical images are always .dicom, or .mhd，These files contain a lot of metadata (such as the pixel size, so how long one pixel is in every dimension in the real world). are these metadata information  necessary in registration?
when I use Elastix, it's  amazing! It is executed in windows shell, but I only know how to input .mhd format image. when as to dicom format, a scan has many files, but they are a whole in fact, I don't know how to input these files as a whole.

2.Now, I deal with this problem  by SimpleITK
Original images' format is dicom, It can be input to workplace by SimpleITK or Pydicom, as a  Dicom object, but I have to do some preprocessing to obtian the HU, mask and so on ,  to do these operation, I have to convert dicom object to numpy.ndarray. the metadata information is missing.

The expiration scan is 512* 512 *237,  the inspiration scan is 512 *512 *297， 

Could you give a full pipeline of how to perform  registration of  expiration scan to the inspiration scan , including preprocessing, data input, how to get mask

just do a tutorial, that will be wonderful

**Comment by PertuyF** [comment]
Hi @duancaohui ,

I think you may have misunderstood how it works here. Although things sometime goes beyond the aim of github issues (which is to report bugs or discuss features in a project), it is not a place where you can come and just ask people to do your job from minimalistic and unclear instructions.

The least you can do is to try something by yourself, and ask here if you encounter any problem related to SimpleElastiX. I have no doubt that you will be able to gather the informations needed among the multiple resources available online. `SimpleITK`, `Numpy`, `PyDicom `and medical image processing in general are well documented.

**Comment by duancaohui** [comment]
Thank you , I got it. Thanks for your good job, I have fixed the medical image input probelm succeeful, SimpleElastix is a really nice tool!
