### ISSUE TITLE
transformix in simpleelastix: Bad direction, determinant is 0. Direction is 1 0

### ISSUE THREAD

**Issue by ablot** [SuperElastix/SimpleElastix#113]
Dear all,

I'm using transformix to transform some points. If I do it from the command line, everything works (log below) but if I use simple elastix, I get an error. My command line call is that:
`transformix -def test.pts -tp trans.txt -out cmd_line` and in simpleelastix I run that:

```import SimpleITK as sitk
transformixImageFilter = sitk.TransformixImageFilter()
transformixImageFilter.SetTransformParameterMap(sitk.ReadParameterFile('./trans.txt'))
transformixImageFilter.SetFixedPointSetFileName('./test.pts')
transformixImageFilter.SetOutputDirectory('sitk')
out = transformixImageFilter.Execute()
```
The simpleelastix verison returns:

```
Installing all components.
InstallingComponents was successful.

ELASTIX version: 4.801
Command line options from ElastixBase:
-out      sitk/
-threads  unspecified, so all available threads are used
-def      ./test.pts
-jac      unspecified, so no det(dT/dx) computed
-jacmat   unspecified, so no dT/dx computed
Calling all ReadFromFile()'s ...
  Calling all ReadFromFile()'s took 0.000167 s
Transforming points ...
  The transform is evaluated on some points, specified in the input point file.
  Reading input point file: ./test.pts
  Input points are specified as image indices.
  Number of specified input points: 191

itk::ExceptionObject (0x240bdf0)
Location: "unknown" 
File: /mnt/data/blota/software/simpleElastix/build/ITK-prefix/include/ITK-4.11/itkImageBase.hxx
Line: 194
Description: itk::ERROR: Image(0x1a1f3b0): Bad direction, determinant is 0. Direction is 1 0
0 0



However, transformix continues anyway.
  Transforming points done, it took 0.00s
Compute determinant of spatial Jacobian ...
  The command-line option "-jac" is not used, so no det(dT/dx) computed.
  Computing determinant of spatial Jacobian done, it took 0.00s
Compute spatial Jacobian (full matrix) ...
  The command-line option "-jacmat" is not used, so no dT/dx computed.
  Computing spatial Jacobian done, it took 0.00s

```

If I try to reexecute anything in the same python shell, I get a segfault. The command line works fine and the log is that:

> ~/temp/debug$ transformix -def test.pts -tp trans.txt -out .
> 
> transformix is started at Wed Jul 19 18:27:38 2017.
> 
> which transformix:   transformix
> transformix runs at: jigsaw
>   Linux 4.4.0-83-generic (x64), #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017
>   with 64368 MB memory, and 1 cores @ 1899 MHz.
> Running transformix with parameter file "trans.txt".
> 
> Reading the elastix parameters from file ...
> 
> Installing all components.
> InstallingComponents was successful.
> 
> ELASTIX version: 4.800
> Command line options from ElastixBase:
> -in       unspecified, so no input image specified
> -out      ./
> -threads  unspecified, so all available threads are used
> -tp       trans.txt
> -def      test.pts
> -jac      unspecified, so no det(dT/dx) computed
> -jacmat   unspecified, so no dT/dx computed
> Calling all ReadFromFile()'s ...
>   Calling all ReadFromFile()'s took 0.000187 s
> Transforming points ...
>   The transform is evaluated on some points, specified in the input point file.
>   Reading input point file: test.pts
>   Input points are specified as image indices.
>   Number of specified input points: 191
>   The input points are transformed.
>   The transformed points are saved in: ./outputpoints.txt
>   Transforming points done, it took 0.00s
> Compute determinant of spatial Jacobian ...
>   The command-line option "-jac" is not used, so no det(dT/dx) computed.
>   Computing determinant of spatial Jacobian done, it took 0.00s
> Compute spatial Jacobian (full matrix) ...
>   The command-line option "-jacmat" is not used, so no dT/dx computed.
>   Computing spatial Jacobian done, it took 0.00s
> 
> transformix has finished at Wed Jul 19 18:27:38 2017.

Did I set the arguments wrong in simpleelastix?

**Comment by kaspermarstal** [comment]
I think this is because elastix' library interface is unable to detect the dimensionality of the your images from the parameter file alone, and then interprets some of the parameters as 2D by default. Try to set the fixed and/or the moving image on the `transformixImageFilter` in addition to the parameter file and let me know how it goes.

**Comment by ablot** [comment]
Indeed. Adding: `transformixImageFilter.SetMovingImage(sitk.ReadIMage('random3dimage.mhd'))` fixed the problem.

**Comment by kaspermarstal** [comment]
Thank you for the feedback. Happy coding!
