### ISSUE TITLE
Setting Number of Threads for ElastixImageFilter

### ISSUE THREAD

**Issue by unidesigner** [SuperElastix/SimpleElastix#114]
Hi,
I'd like to limit the number of maximal threads used by the ElastixImageFilter.Execute() call, like the -threads option for the command-line interface. Is this possible with the current version?
Thanks a lot,
Stephan

**Comment by PertuyF** [comment]
Hi @unidesigner ,

If I remember well, this option is not exposed by ElastiX API (or was?) and is thus unavailable in SimpleElastiX.
Is it still the case @kaspermarstal ?

**Comment by kaspermarstal** [comment]
It is not exposed at the moment but it is definitely possible. It will require some changes to Elastix itself though. I will do it as soon as I get the time.

**Comment by unidesigner** [comment]
Hi, thanks for the information. Then I'll continue using the command-line version of elastix. SimpleElastix looks very nice though and I'd like to use it.
Maybe related: I was also looking for a way to disable the usage of the OpenCL code for the precompiled binary (it sends processes to my GPU that I cannot control) but did not find a way from the documentation. In case there is something to expose here as well in SimpleElastix, that would be nice too.
Thanks!

**Comment by kaspermarstal** [comment]
Fixed by SuperElastix/SimpleElastix@f8d407f5f57740d47f8308ace7edabe6d3b67179.
