### ISSUE TITLE
Can't import SimpleITK.SimpleElastix

### ISSUE THREAD

**Issue by TheGrim1** [SuperElastix/SimpleElastix#115]
Hi,

following the example code [here](https://github.com/SuperElastix/SimpleElastix/blob/master/Examples/Python/SimpleElastix.py)

import SimpleITK as sitk
selx = sitk.SimpleElastix()

I get AttributeError: 'module' object has no attribute 'SimpleElastix'

Has this API changed?

I followed the windows installation instructions [from here](http://simpleelastix.readthedocs.io/GettingStarted.html#building-manually-on-linux) successfully (cmake and VS2017). Note that the build path had to be _really_ short. 

After the building I found in the build directory: build_dir.txt
[build_dir.txt](https://github.com/SuperElastix/SimpleElastix/files/1169203/build_dir.txt)

And in it  c:\apps\b\SimpleITK-build\Wrapping\Python\Packaging
21/07/2017  13:37             3,282 setup.py
21/07/2017  12:16               545 setupegg.py
21/07/2017  15:07    <DIR>          SimpleElastix.egg-info
and ran python setup.py install from the respective venv I wanted to install this package in. Now pip list includes:
SimpleElastix=1.0.0rc1.dev555+g22340
but as I mentioned at the start I can't import it. 
SimpleITK.Elastix is available, but as there is some legacy code available to me based on SimpleElastix I would really prefer being able to use that. 

Any help is appreciated!

**Comment by kaspermarstal** [comment]
Hi, yes it has changed from `SimpleElastix()` to `ElastixImageFilter()`. Thanks for reporting this, I will update the examples!

**Comment by kaspermarstal** [comment]
The changes have been committed to develop and will be included in the next release. Thank you!
