### ISSUE TITLE
Errors in building: Unsupported protocol

### ISSUE THREAD

**Issue by lujttw** [SuperElastix/SimpleElastix#116]
I got some errors from "make -j4"
Is it because my cmake doesn't support SSL? Could you help me on the issue.
Thank you!

  Object MD5=2e115fe26e435e33b0d5c022e4490567 not found at:

    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/2e115fe26e435e33b0d5c022e4490567/download ("Unsupported protocol")
    https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5 ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")

make[2]: *** [ExternalData/.ExternalSource/pcre-8.37.tar.gz-hash-stamp] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [ExternalData/.ExternalSource/swig-3.0.11.tar.gz-hash-stamp] Error 1
make[2]: *** [ExternalData/.ExternalSource/lua-5.1.5.tar.gz-hash-stamp] Error 1

**Comment by kaspermarstal** [comment]
It could be, I don't really know. Have you tried to install a new version of CMake? Binaries from the cmake website definitely support https. r

**Comment by lujttw** [comment]
I updated CMake and it solved the problem. Thank you.
