### ISSUE TITLE
Elastix output not showing mask is set

### ISSUE THREAD

**Issue by thatguy14** [SuperElastix/SimpleElastix#117]
Hi, this is a conversation I had with Kasper and I wanted to document it here for posterity.

Original email (parts omitted not relevant):

> when I look at the terminal when the Elastix call is made and it displays the Elastix text to the terminal, it says the fixed mask is not set. This is the code I was using:
>  
> elastixImageFilter = sitk.ElastixImageFilter()
> elastixImageFilter.SetFixedMask(fixedMask)
> elastixImageFilter.SetFixedImage(image_4d)
> elastixImageFilter.SetMovingImage(image_4d)
> paramMap = sitk.GetDefaultParameterMap('groupwise')
> paramMap['ResultImageFormat'] = ['nrrd']
> elastixImageFilter.SetParameterMap(paramMap)
> elastixImageFilter.Execute()
 
Response from Kasper:

> Don't worry that it says it is not set - it is. The library interface to elastix was sort of "hacked in" and some things aren't fully compatible with the library yet.

**Comment by kaspermarstal** [comment]
Thanks for reporting here @thatguy14! Hopefully this will be useful to others.

**Comment by farhanone** [comment]
Hi,

There is the error:

> return _SimpleITK.ElastixImageFilter_Execute(self)
> RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /media/farhan/Volume/Project/SimpleElastix/src/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:133:
> sitk::ERROR: Fixed masks must have same direction cosines as fixed images (fixed image at index 0 has direction cosine [ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ], fixed mask at index 0 has direction cosine "[ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ]").

With code

`elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(sitk.ReadImage(targetImage))
elastixImageFilter.SetMovingImage(sitk.ReadImage(movingImage))
elastixImageFilter.SetFixedMask(sitk.ReadImage(movingMask))
#elastixImageFilter.SetMovingMask(sitk.ReadImage(movingMask))
elastixImageFilter.SetParameterMap(sitk.GetDefaultParameterMap("affine"))
elastixImageFilter.Execute()
sitk.WriteImage(elastixImageFilter.GetResultImage(), path)`

it says direction cosines must be the same for fixed image and fixed mask, but these are the same indeed.
thanks in advance

**Comment by farhanone** [comment]
Hi,
Here is the error message:

> RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /media/farhan/Volume/Project/SimpleElastix/src/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:133:
> sitk::ERROR: Fixed masks must have same direction cosines as fixed images (fixed image at index 0 has direction cosine [ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ], fixed mask at index 0 has direction cosine "[ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ]").
> 

With the code :-1: 
`elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(sitk.ReadImage(targetImage))
elastixImageFilter.SetMovingImage(sitk.ReadImage(movingImage))
elastixImageFilter.SetFixedMask(sitk.ReadImage(movingMask))
paraMap=sitk.GetDefaultParameterMap('affine')
#elastixImageFilter.SetMovingMask(sitk.ReadImage(movingMask))
elastixImageFilter.SetParameterMap(paraMap)
elastixImageFilter.Execute()
sitk.WriteImage(elastixImageFilter.GetResultImage(), path)`

it says direction cosine must be same for fixed image and fixed mask but thses are indeed same.

Thanks in advance

Farhan

**Comment by farhanone** [comment]
> RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /media/farhan/Volume/Project/SimpleElastix/src/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:133:> sitk::ERROR: Fixed masks must have same direction cosines as fixed images (fixed image at index 0 has direction cosine [ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ], fixed mask at index 0 has direction cosine "[ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ]").>
