### ISSUE TITLE
multiple SimpleElastix instances/runs ignore `RandomSeed` in ParameterFile

### ISSUE THREAD

**Issue by romangrothausmann** [SuperElastix/SimpleElastix#122]
It seems SimpleElastix ignores `RandomSeed` set in ParameterFile.
Even though I set `RandomSeed` in the ParameterFile, and initialize each selx instance with the very same ParameterFile (pM), selx seems not to (re-) set its random seed accordingly.  See e.g. these test results: https://github.com/romangrothausmann/elastix_scripts/commit/d2d6d04cfa9aaf6121f35d01e601b8cb65284b96?diff=split#diff-2e0a2595b81a2453a02093ffede7ec7dL1

The first metric value (107.81864) stays the same but the second run of selx yields 99.225277 even though both run with "NoInitialTransform" and the same ParameterFile. It also changes the metric values for all following runs. 

Note that the metric value for the second image pair (L2) changes back to its original value (60.185559) if the first image pair only uses one selx run: https://github.com/romangrothausmann/elastix_scripts/commit/d06bd99f8066c5d1429149412895d3046e35d0a9#diff-2e0a2595b81a2453a02093ffede7ec7dR2

So it seems to me that selx initializes its RNG with a fixed random seed (121212 by default or that given by `RandomSeed` in ParameterFile) only once but not for every new instance/run even if the ParameterFile stays the same (and one would expect the RandomSeed to be reset again).

**Comment by kaspermarstal** [comment]
Thank you for catching this issue! SimpleElastix just hands images and parameter files to elastix so this is probably more of an elastix issue. Would you consider opening an issue with your description in the [elastix repository](https://github.com/SuperElastix/elastix)?
