### ISSUE TITLE
Multi-series Registration

### ISSUE THREAD

**Issue by vikas-anand** [SuperElastix/SimpleElastix#124]
Hi,

I am trying to register two volumes that look at the same anatomy (pelvis). However, of the two sequences, one of them is a zoomed version of the other. It would be great on how to tackle this problem using SimpleElastix. I am attaching snapshots of the two sequences for your reference. 

![axial_pelvis](https://user-images.githubusercontent.com/13653312/29494999-90065d1a-85d3-11e7-868e-a8c670ee2cf5.png)

![tran_pelvis](https://user-images.githubusercontent.com/13653312/29495005-9d301206-85d3-11e7-97f4-b689c8c2a31f.png)

Thanks for your help in this regard.
Regards
Vikas

**Comment by PertuyF** [comment]
More information is needed to understand what you really want/need.

* Did you tried anything yet?
* What is your goal here?
* Are those two MRI datasets from the same individual?

**Comment by vikas-anand** [comment]
Hi PertuyF,
Thanks,
1). After posting this issue I tried doing registration with SimpleITK. It is working for me now.
2).My goal here is to register the first image(Moving Image) with respect to second image (fixed Image).
3).Yes, these MRI datasets are from same individual .
Thank you.

Regards
Vikas

**Comment by PertuyF** [comment]
Feel free to close the issue if you don't need help anymore.
