### ISSUE TITLE
List of implemented features

### ISSUE THREAD

**Issue by thatguy14** [SuperElastix/SimpleElastix#125]
Hello! I am wondering if there is a list of implemented and not implemented features. One example is how you cannot specify the number of threads (as mentioned in a previous post, issue #114). I am thinking of using some of the other aspects of elastix (for example using multiple metrics or some of the penalty terms) but just curious what is available and what isn't!
Sorry if this is a silly question, thanks for your time.

**Comment by kaspermarstal** [comment]
There is always the [elastix manual](http://elastix.isi.uu.nl/download/elastix_manual_v4.8.pdf) that describes the features of elastix, most of which is supported by SimpleElastix.

For a long time I have wanted to add doxygen information to SimpleElastix (see [this example](https://github.com/SuperElastix/SimpleElastix/blob/master/Code/Elastix/include/sitkElastixImageFilter.h#L35-L50)) but have never gotten around to do it. For now, the list of functions in this header file is the best documentation. PRs are most welcome from anyone out there willing to add docs to just a few functions.
