### ISSUE TITLE
Issues while using SimpleElastix methods

### ISSUE THREAD

**Issue by subhajitchatu** [SuperElastix/SimpleElastix#127]
Hi,

I have found two issues or rather doubts while using SimpleITK.

1. When after registration, I am going to write the result image into .nii or .dcm file, all the pixel locations are being changed to integer values

  `selx = sitk.SimpleElastix()`
  `sitk.WriteImage(selx.GetResultImage(),"testdce.nii")`

The Input image have voxels like (103.68,141.32,37.50) <x,y,z>. But there is no float values in testdce.nii. I want the pixels to be as it was in the input file. How to achieve this?

2. I have encountered a strange issue while using bspline method:

       `
       `selx = sitk.SimpleElastix()
        selx.SetFixedImage(fixed)
        selx.SetMovingImage(moving)
        parameterMapVector = sitk.VectorOfParameterMap()
        parameterMapVector.append(sitk.GetDefaultParameterMap("rigid"))
        parameterMapVector.append(sitk.GetDefaultParameterMap("affine"))
        parameterMapVector.append(sitk.GetDefaultParameterMap("bspline"))
        selx.SetParameterMap(parameterMapVector)`

Here when I am using bspline, after writing the image into testdce.nii, I have found out that there are some black holes in the image is constructed, there is no sign of these holes in original image.
When I commented out bspline only, it's working appropriately. 

Please look into my doubts and waiting for your suggestion.

**Comment by subhajitchatu** [comment]
@PertuyF @kaspermarstal @zivy Any suggestion from you guys?

Thanks

Subhajit

**Comment by kaspermarstal** [comment]
1. What is the type of image returned by `GetResultImage()`? It should be always be float, and consequently `WriteImage` should write a float image. Are you doing any postprocessing where the pixeltype might be changed?
2. If the b-spline grid is to dense compared to the images you register, the b-spline deformation might distort your image. You could try to increase the weight of the regularization by turning up the "Metric1Weight" of the b-spline parameter map or reducing the number of knots in the grid. For more info on the b-spline transform, see the [elastix manual](http://elastix.isi.uu.nl/download/elastix_manual_v4.8.pdf).

**Comment by subhajitchatu** [comment]
@kaspermarstal  
1. my problem is not regarding the intensity value, those are float and it's absolutely fine. But in the original image, the coordinates were also float like (102.4,103.2,30). These are not retaining in the result image after saving it in .nii or dicom .

I have not done any post processing, just read Dicom image both fixed and moving and used default rigid and affine transformation on the image and saving the image into .nii or .dcm

2. I have used default parameters of simpleElastix. I haven't done any parameter tuning after that. So if yu suggests to modify the default parameter I will do. yes, it is coming only in extreme slice, i think you are right. It is happening for dense grid.

Thanks

**Comment by kaspermarstal** [comment]
1. I'm am not sure I understand the problem. The coordinates in the image space are integers on the discrete image grid. The coordinates in the physical space are floats, yes, which can be obtained from the image coordinates and the origin, spacing and direction saved in the image headers. As I read your comment, you expect float coordinates to be saved in the image? If so, they are not. Only the discrete intensity grid is savedI. Info with respect to the world coordinates are saved in the image header, and you have to make the conversion yourself. If I have misunderstood you again, please do elaborate! But really spell it out for me. Sometimes a lot of context is lost in writing.
2. Yes try to experiment with the default parameters. In particular, you can try to increase the number of resolution and more slowly increase the bspline parameter resolution (e.g. use 8 resolutions and setting `GridSpacingSchedule` to `8.0 7.0 6.0 5.0 4.0 3.0 2.0 1.0`).

**Comment by subhajitchatu** [comment]
@kaspermarstal 

1. You have got my question correctly. Yes I need to  convert my fixed image first which has float coordinates. So first after reading the images I will save it to .nii and then will start processing further.

2. Ok. Will try it.

**Comment by kaspermarstal** [comment]
Closing. Feel free to reopen if your problem is not resolved.
