### ISSUE TITLE
Create 4d image from 2d dicom

### ISSUE THREAD

**Issue by thatguy14** [SuperElastix/SimpleElastix#129]
Hello,

I am trying to create a 4D image from a series of 2d+t images. I have tried a bunch of things but can't seem to get it to work.

When I use the vectorOfImages and joinseries functions, I end up with a 3d Image. This I think is because the dicoms are loaded as one image (in the example, a series of hdr images were loaded).

Is there an efficient way of doing this? I tried to create a "3d image" by creating an empty image and then using extractImageFilter to get the individual 2d slices and then finally tried to use vectorOfImage and joinseries to create the 4d image but it ignores the slice dimension (size 1) and creates a 3d image. Could very well be I did something wrong though. 

Thanks for any help

**Comment by PertuyF** [comment]
Hi @thatguy14 ,

You mention an example, but there is not in your message. This makes it hard to get where your problem comes from.
Moreover, from what you describe, your problem does not seem to be specifically related to SimpleElastix but more to SimpleITK.

**Comment by thatguy14** [comment]
Oh crap, sorry about that, I thought I was on the SimpleITK git, had both tabs open. 

You can delete this or close this - apologies for the clutter

**Comment by PertuyF** [comment]
No problem, good luck with your issue. And don't forget to include your example ;)
