### ISSUE TITLE
Composition of several transformations, potentially mixing SimpleITK and SimpleElastix types

### ISSUE THREAD

**Issue by rcasero** [SuperElastix/SimpleElastix#134]
Hi,

Basically, I would like to compose transformations written by myself with transformations computed by SimpleElastix. My first thought was to combine SimpleITK transformations with SimpleElastix transformations, but I don't think that's possible.

In SimpleITK, I can define

initialTransform = sitk.Euler2DTransform()
...
affineTransform = sitk.AffineTransform(2)
...
totalTransform = sitk.Compose(initialTransform, affineTransform)

However, let's say that affineTransform instead is the result of running SimpleElastix registration, i.e.

affineTransform = elastixImageFilter.GetTransformParameterMap()[0]

Is there a way to convert the SimpleElastix transform to SimpleITK without manually populating the fields?

affineTransformSITK = sitk.AffineTransform(2)
affineTransformSITK.SetCenter(tuple(map(float, affineTransform['CenterOfRotationPoint'])))
affineTransformSITK.SetParameters(tuple(map(float, affineTransform['TransformParameters'])))
...

Notes:

1. Not sure whether this would even work in general, as SimpleITK doesn't have an "Origin" field, but SimpleElastix's affine does.

2. What I'm thinking is that maybe the solution would be to define the initialTransform as a SimpleElastix object, then create a tuple

(initialTransform, affineTransform)

and pass that to Transformix?

Best regards,

Ramon.

**Comment by kaspermarstal** [comment]
That is not something I have tried, no, and you would have to be very careful about image definitions. What you can do is have transformix produce a deformation and use that in SimpleITK. Deformation fields should be exchangeable.

**Comment by rcasero** [comment]
OK, thanks.

**Comment by mary-alegro** [comment]
I'm curious. Is there any follow up in that question? I'm facing a similar problem.
