### ISSUE TITLE
ResultImagePixelType ignored by Transformix?

### ISSUE THREAD

**Issue by rcasero** [SuperElastix/SimpleElastix#136]
Hi,

I have created a simple transformation by registering an image to itself

    parameterMap = sitk.GetDefaultParameterMap('rigid')
    elastixImageFilter = sitk.ElastixImageFilter()
    elastixImageFilter.SetFixedImage(imhisto_gray)
    elastixImageFilter.SetMovingImage(imhisto_gray)
    elastixImageFilter.SetParameterMap(parameterMap)
    elastixImageFilter.Execute()
    rigidTransform = elastixImageFilter.GetTransformParameterMap()[0]

The input image's pixel type is int, as shown by

    type(imhisto_gray.GetPixel(0,0))
    int

For some reason, the output pixel type is float

    rigidTransform['ResultImagePixelType']
    ('float',)

I try to force that the output pixel type is int

    rigidTransform['ResultImagePixelType'] = ('int',)

But applying transformix to the image produces an image with float pixels

    transformixFilter = sitk.TransformixImageFilter()
    transformixFilter.SetTransformParameterMap(rigidTransform)
    transformixFilter.SetMovingImage(imhisto_gray)
    transformixFilter.Execute()
    imhisto_gray_rot_2ct = transformixFilter.GetResultImage()
    type(imhisto_gray_rot_2ct.GetPixel(0,0))
    
    float

**Comment by kaspermarstal** [comment]
Yes, internally pixels are always float to reduce compile time and binary size. 

You can cast them back using sitk.Cast().

**Comment by rcasero** [comment]
Oh, that's very useful, thanks. Now casting with

im = sitk.Cast(im, sitk.sitkUInt8)
