### ISSUE TITLE
Build error in Python Virtualenv creation while in Anaconda

### ISSUE THREAD

**Issue by the4thchild** [SuperElastix/SimpleElastix#141]
I'm building SimpleElastix within an Anaconda environment and encountered an error while SuperBuild was building the Python virtual environment. The Python wrapper appears to have been built before this step, and I can install and use the wrapper without issue (SimpleElastix is awesome!). Here is the error message from the compilation:

```
[ 58%] Built target SimpleITK_PYTHON
Scanning dependencies of target PythonVirtualEnv
[ 58%] Creating python virtual enviroment...
Already using interpreter /Users/david/Programs/anaconda3/envs/clr/bin/python
Not deleting /Users/david/src/build_se6/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin
Using base prefix '/Users/david/Programs/anaconda3/envs/clr'
New python executable in /Users/david/src/build_se6/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python
ERROR: The executable /Users/david/src/build_se6/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python is not functioning
ERROR: It thinks sys.prefix is '/Users/david/src/SimpleElastix/Wrapping/Python' (should be '/Users/david/src/build_se6/SimpleITK-build/Testing/Installation/PythonVirtualenv')
ERROR: virtualenv is not compatible with this system or executable
CMake Error at PythonVirtualEnvInstall.cmake:40 (message):
  Creation of Python virtual enviroment failed.

  dyld: Library not loaded: @rpath/libpython3.5m.dylib

    Referenced from: /Users/david/src/build_se6/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python
    Reason: image not found



make[5]: *** [Testing/Installation/PythonVirtualenv/bin/python] Error 1
make[5]: *** Deleting file `Testing/Installation/PythonVirtualenv/bin/python'
make[4]: *** [Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
```

I'm building from SimpleElastix master branch at commit abf921e3eb49f62d565a5171a5d52c5885821010. I'm compiling within an Anaconda environment to use Python 3.5 on MacOS 10.12.6. I turned off building all wrappers other than for Python.

When I built SimpleElastix outside of an Anaconda environment, using the Mac default Python 2.7.10 version, the full build completed without issue.

Is there a way to turn off PythonVirtualenv creation if the build is taking place within an Anaconda virtual environment?

**Comment by kaspermarstal** [comment]
There is a variable `SimpleITK_USE_SYSTEM_VIRTUALENV` but I don't know if that will resolve your problem on its own. 

Try to `conda create` an environment and activate it prior to configuring CMake and let me know how it goes.

**Comment by the4thchild** [comment]
Thanks for your advice! The error I got above was within an activated conda environment with Python 3.5, where I had configured the CMake file as well.

The ```SimpleITK_USE_SYSTEM_VIRTUALENV:BOOL``` flag appears to be off by default, so I tried turning it on but got the error:

```
CMake Error at /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonVirtualEnv (missing: PYTHON_VIRTUALENV_SCRIPT)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /Users/david/src/SimpleElastix/CMake/FindPythonVirtualEnv.cmake:49 (find_package_handle_standard_args)
  SuperBuild.cmake:342 (find_package)
  CMakeLists.txt:38 (include)
```
Is there another way to turn off the need for virtualenv if compiling within conda? Or should I try to point PYTHON_VIRTUALENV_SCRIPT to conda, if that works?

**Comment by kaspermarstal** [comment]
Found this option in the SimpleITK CMake code:

    SimpleITK_PYTHON_USE_VIRTUALENV:BOOL=OFF

Perhaps you try to use this? Give it to the SuperBuild and it will automatically be passed on.

**Comment by the4thchild** [comment]
Thanks for pointing that out -- using that flag, SuperBuild completed without any errors while in Anaconda!

Here's the cmake command I used in case it's of any use to anyone. I turned off all wrappings but left on the Python wrapping by default and included the compiler flags for Mac:
```
cmake -DCMAKE_CXX_COMPILER:STRING=/usr/bin/clang++ -DCMAKE_C_COMPILER:STRING=/usr/bin/clang -DWRAP_JAVA:BOOL=OFF -DWRAP_LUA:BOOL=OFF -DWRAP_R:BOOL=OFF -DWRAP_RUBY:BOOL=OFF -DWRAP_TCL:BOOL=OFF -DSimpleITK_PYTHON_USE_VIRTUALENV:BOOL=OFF ../SimpleElastix/SuperBuild
```

Thanks again for your help!
