### ISSUE TITLE
Building SimpleElastix with OpenCL

### ISSUE THREAD

**Issue by NHPatterson** [SuperElastix/SimpleElastix#145]
Hi, I am trying to follow what is laid out in this issue: https://github.com/SuperElastix/SimpleElastix/issues/4 but can't seem to locate the correct cmake flags to change. Any advice would be greatly appreciated. Thank you!

**Comment by PertuyF** [comment]
Hi @NHPatterson ,
Let's start from the beginning: what is **your** issue?

It's hard to help if we don't know what you're trying to solve :)

**Comment by NHPatterson** [comment]
Sorry, I don't know in which file to find and add the OpenCL cmake flags to build with the OpenCL filters. I assume that by default, it is not built with these.

**Comment by PertuyF** [comment]
You should be able to set these flags using cmake-gui, that's what I used in the issue cited above.

**Comment by NHPatterson** [comment]
@PertuyF I thought so but maybe not after some testing. When I add a ELASTIX_USE_OPENCL flag in cmake using the SimpleElastix SuperBuild, I don't activate and see the additional NVIDIA flags, etc. This will work when I configure elastix alone for compilation, but nothing happens indicating that openCL is found when I try to configure with the SuperBuild. Unfortunately, following the manual building instructions works for ITK, elastix(where I appear to successfully compile OpenCL filters), but then not for SimpleElastix. Thanks for your help..

**Comment by richhend** [comment]
Hi, 
I'm having the same problem as @NHPatterson when I try to build SimpleElastix (on Windows 10, 64 bit) from SuperBuild with OpenCL and wrapping for Python 3.6 (64 bit):
the build runs through without errors, but when I want to use OpenCL for pyramids and resampling during registration, I get an error that the components 'OpenCLResampler', 'OpenCLFixedGenericImagePyramid', and 'OpenCLMovingGenericImagePyramid' are not installed.
In the CMake-GUI I'm setting:
BUILD_EXAMPLES=OFF
BUILD_TESTING=OFF
PYTHON_EXECUTABLE: C:/Users/S/comp_SE/Anaconda3/python.exe
PYTHON_INCLUDE_DIR: C:/Users/S/comp_SE/Anaconda3/include
PYTHON_LIBRARY: C:/Users/S/comp_SE/Anaconda3/libs/python36.lib
SimpleITK_4D_IMAGES=ON
WRAP_DEFAULT=OFF
WRAP_PYTHON=ON
WRAP_<all other languages>=OFF
-----------------
ELASTIX_USE_OPENCL: ON
USE_OpenCLFixedGenericPyramid: ON
USE_OpenCLMovingGenericPyramid: ON
USE_OpenCLResampler: ON
OPENCL_INCLUDE_DIRS: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include
OPENCL_LIBRARIES: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib
OPENCL_OPTIMIZATION_MAD_ENABLE: ON
OPENCL_USENVIDIA_SDK: ON
(and also for me, as for @NHPatterson, the other OpenCL options don't come up automatically when I set ELASTIX_USE_OPENCL: ON, as reported by others. So I am setting all the above options manually right now)
Then generate with the Visual Studio 14 2015 Win64 compiler and build with 
msbuild ALL_BUILD.vcxproj /p:Configuration=Release
from the VS2015 x64 Native Build Tools Command Prompt.
Finally, I build the Python module with 
cd SimpleITK-build\Wrapping\Python\Packaging
python setup.py install
Everything runs through without errors, but then I can't use OpenCL Resampler and pyramids.
Is OpenCL supposed to work with the SuperBuild under Windows? Or does one have to install ITK
and Elastix separately first?
Thanks a lot!

**Comment by kaspermarstal** [comment]
You can test out this new `opencl` branch which adds an `SimpleElastix_OPENCL` option to the SuperBuild. Can you test it? If it works, we can merge it.

You can also manually build Elastix with OpenCL support and set `SIMPLEITK_USE_SYSTEM_ELASTIX` to `ON` or pass Elastix_DIR to SimpleITK. However, I agree this is not obvious and hopefully this patch simplifies the build for you OpenCL folks.  

OpenCL has not been available in the SuperBuild until now because it is sort of a power-user thing and CMake will throw an error if it cannot find OpenCL which might throw off new users. The default value of this flag is therefore `OFF`.

**Comment by NHPatterson** [comment]
I'm not sure it works as it should, I see the option, but configuring the SuperBuild with Elastix to install with OpenCL doesn't raise the additional flags about which OpenCL version to use, and all the other specific OpenCL options we see when configured elastix alone. It appears that it will compile but I'm not sure it will actually compile with the openCL components.

**Comment by richhend** [comment]
Thanks a lot for the new opencl branch!
When I switch SimpleElastix_OPENCL to ON, no other OpenCL options come up in CMake that let me specify the OpenCL paths, resampler, and pyramids, as is the case when configuring Elastix alone with CMake. Then, when building, it throws an error:

"C:\p\ALL_BUILD.vcxproj" (default target) (1) ->                                                                        "C:\p\SimpleITK.vcxproj" (default target) (7) ->                                                                        
(CustomBuild target) ->                                                                                                   
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppCommon.targets(171,5): 
error MSB6006: "cmd.exe" e xited with code 1. [C:\p\SimpleITK.vcxproj]    

Regarding the other option, to manually build Elastix with OpenCL and set SIMPLEITK_USE_SYSTEM_ELASTIX to ON:
I haven't been able to build OpenCL-enabled SimpleElastix from an OpenCL-enabled Elastix yet, and am not sure what the exact steps and CMake-option settings for each step are supposed to be.
Should I follow the instructions in the section "Manually Building On Linux" in the docs (https://simpleelastix.readthedocs.io/GettingStarted.html), but just in addition set all the OpenCL options in the Elastix step, i.e., 
1) build ITK from source
2) build Elastix from source, and set all the OpenCL options
3) build SimpleElastix from source (using SimpleElastix dir and _not_ SuperBuild dir as source dir in CMake), providing ITK_DIR and Elastix_DIR
?
When I try this, steps 1 and 2 run through without errors, but then I get errors in step 3.
(I'm on Windows 10, 64 bit and wrapping for Python 3.6, 64 bit, using the Visual Studio 14 2015 Win64 compiler)
Or should I use the SimpleElastix/SuperBuild dir in step 3 instead?
Would you mind giving us the exact steps together with the respective CMake options in each step?
Thanks a lot for your help!

**Comment by NHPatterson** [comment]
I compiled the openCL branch and the OpenCL filter was not found:

> Error: 
> OpenCLesampler(index 1) - This component is not installed!
> ERROR: error occurred while creating Resampler 0.
> 
> itk::ExceptionObject (0x557f9b027e50)
> Location: "unknown" 
> File: /home/ubuntu/SimpleElastix/build/Elastix/Core/Kernel/elxElastixMain.cxx
> Line: 819
> Description: itk::ERROR: ElastixMain(0x557f9b00cfa0): The following component could not be created: OpenCLesampler

Same for the OpenCL pyramids. Is this because the USE_OpenCL_* is not in the ExternalElastix cmake file? When the build was compiling I saw OpenCL links being built. 

Thanks again for the help.

**Comment by richhend** [comment]
On Windows, I just tried the following things:

1) I took the new opencl branch, and in  SuperBuild/External_Elastix.cmake I manually added the cmake options:
-DELASTIX_USE_OPENCL:BOOL=${SimpleElastix_OPENCL}
-DUSE_OpenCLFixedGenericPyramid:BOOL=ON
-DUSE_OpenCLMovingGenericPyramid:BOOL=ON
-DUSE_OpenCLResampler:BOOL=ON
-DOPENCL_INCLUDE_DIRS:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include
-DOPENCL_LIBRARIES:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib
 
Then I ran cmake with:
cmake -G "Visual Studio 14 2015 Win64" ^
More? -DPYTHON_EXECUTABLE:FILEPATH=C:\Users\SPIM\lux\comp_SE\Anaconda3\python.exe ^
More? -DPYTHON_LIBRARY:FILEPATH=C:\Users\SPIM\lux\comp_SE\Anaconda3\libs\python36.lib ^
More? -DPYTHON_INCLUDE_DIR:PATH=C:\Users\SPIM\lux\comp_SE\Anaconda3\include ^
More? -DBUILD_EXAMPLES=OFF ^
More? -DBUILD_TESTING=OFF ^
More? -DSimpleITK_4D_IMAGES=ON ^
More? -DITK_USE_64BITS_IDS=ON ^
More? -DWRAP_PYTHON=ON ^
More? -DWRAP_DEFAULT=OFF ^
More? -DWRAP_CSHARP=OFF ^
More? -DWRAP_LUA=OFF ^
More? -DWRAP_R=OFF ^
More? -DWRAP_JAVA=OFF ^
More? -DWRAP_TCL=OFF ^
More? -DWRAP_RUBY=OFF ^
More? -DSimpleElastix_OPENCL=ON ^
More? C:\Users\SPIM\lux\comp_SE\SimpleElastix_opencl_modif\SuperBuild

and then build with
msbuild /p:configuration=release ALL_BUILD.vcxproj

That gave the error
"C:\p\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\p\SimpleITK.vcxproj" (default target) (10) ->
(CustomBuild target) ->
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" e xited with code 1. [C:\p\SimpleITK.vcxproj]

2) I repeated the above for the master branch, but in SimpleElastix_master/SuperBuild/External_Elastix.cmake I explicitly set 
-DELASTIX_USE_OPENCL:BOOL=ON

followed again by the other OpenCL options:
-DUSE_OpenCLFixedGenericPyramid:BOOL=ON
-DUSE_OpenCLMovingGenericPyramid:BOOL=ON
-DUSE_OpenCLResampler:BOOL=ON
-DOPENCL_INCLUDE_DIRS:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include
-DOPENCL_LIBRARIES:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib

Now the build went further than before, but after 2 h or so gave me 200 errors, where the linker complained about unresolved external symbols from OpenCL, of the kind:

elxOpenCL.lib(itkOpenCLImage.obj) : error LNK2019: unresolved external symbol clEnqueueCopyImageToBuffer referenced
in function "public: bool __cdecl itk::OpenCLImage::Copy(class itk::OpenCLBuffer const &,class itk::OpenCLSize const &,c lass itk::OpenCLSize const &,unsigned __int64)" (?Copy@OpenCLImage@itk@@QEAA_NAEBVOpenCLBuffer@2@AEBVOpenCLSize@2@1_K@Z ) [C:\p\SimpleITK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\p\SimpleITK.vcxproj]                                elxOpenCL.lib(itkOpenCLImage.obj) : error LNK2019: unresolved external symbol clEnqueueMapImage referenced in functio n "public: void * __cdecl itk::OpenCLImage::Map(enum itk::OpenCLMemoryObject::Access,class itk::OpenCLSize const &,clas s itk::OpenCLSize const &,unsigned __int64 *,unsigned __int64 *)" (?Map@OpenCLImage@itk@@QEAAPEAXW4Access@OpenCLMemoryO bject@2@AEBVOpenCLSize@2@1PEA_K2@Z) [C:\p\SimpleITK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\p\SimpleITK.vcx proj]                                                                                                                     C:\p\SimpleITK-build\Wrapping\Python\_SimpleITK.pyd : fatal error LNK1120: 64 unresolved externals [C:\p\SimpleITK-bu ild\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\p\SimpleITK.vcxproj]                                                                                                                                                                              36 Warning(s)                                                                                                           200 Error(s)   

Is there some linking option that has to be set as well for OpenCL?

Thanks a lot!

**Comment by richhend** [comment]
@NHPatterson, would you like to try what I did under 1.) above on your Linux system? Just to check if the error I get is only a Windows issue?
That is,
take the new opencl branch, and in SuperBuild/External_Elastix.cmake after the line
-DELASTIX_USE_OPENCL:BOOL=${SimpleElastix_OPENCL}
manually add the options
-DUSE_OpenCLFixedGenericPyramid:BOOL=ON
-DUSE_OpenCLMovingGenericPyramid:BOOL=ON
-DUSE_OpenCLResampler:BOOL=ON
-DOPENCL_INCLUDE_DIRS:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include
-DOPENCL_LIBRARIES:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib

where you replace the OpenCL include and lib paths with the appropriate ones on your system.
Could be something like this
-DOPENCL_INCLUDE_DIRS:PATH=/usr/local/cuda/include
-DOPENCL_LIBRARIES:FILEPATH=/usr/local/cuda/lib64/libOpenCL.so
But you should check on your system where the include path and lib actually are. 
I would try it myself, but don't have a Linux set up here right now.
Thanks

**Comment by richhend** [comment]
@kaspermarstal, when I compare the new opencl branch with the master branch, I can see that the only changes you made are the ones in SuperBuild/External_Elastix.cmake and SuperBuild/SuperBuild.cmake, correct?
Unfortunately, I don't know much about how SimpleElastix's automatic (e.g. Python) wrapping of the ITK/Elastix C++ classes/functions actually works. But I was wondering whether the errors I posted above under 2.) mean that there needs to be something else switched / added to the automatic wrapping system in order to properly generate the (Python) wrappers for the Elastix/ITK OpenCL classes / functions?

**Comment by richhend** [comment]
Here some more observations (for Windows):
1.) Building the opencl branch with SimpleElastix_OPENCL=OFF gives the same error as with 
SimpleElastix_OPENCL=ON (see above). That is, this error does not seem to be related to the OpenCL part and is caused by some other problem with the opencl branch (on Windows. According to @NHPatterson there are no errors on Linux when building the opencl branch).
2.) Building the master branch with ELASTIX_USE_OPENCL=ON in SuperBuild/External_Elastix.cmake gives the 200 errors related to the OpenCL wrapping in Python (see above), but building runs through without any errors when ELASTIX_USE_OPENCL=OFF

**Comment by NHPatterson** [comment]
@richhend I tried what you tried on Windows yesterday and I got an error with SimpleITKExplicit, which I had seen previously when trying to compile the SuperBuild with system Elastix. At this point, I'm going to wait for @kaspermarstal, I don't have the Cmake experience to try anything further.

**Comment by kaspermarstal** [comment]
Ahhh. It's the linking step that fails. This is weird since elastix should pull in the OpenCL library dependencies via the ElastixTargets.cmake file. This will require some investigation.

**Comment by richhend** [comment]
Hi Kasper, thanks a lot for the response! Do you already have an idea what the cause for the failing linking step could be?

Also, do you think the alternative path of manually building with OpenCL, to which you were referring earlier, could work instead? That is, 
1. build ITK from source
2. build Elastix from source, and set all the OpenCL options
3. build SimpleElastix from source (using SimpleElastix dir and _not_ SuperBuild dir as source dir in CMake?), providing ITK_DIR and Elastix_DIR

I still haven't been able to make the latter work. So if you think that it should work, would you mind giving us the exact steps together with the respective CMake options in each step?
That would be really great. Thanks a lot for your help!

**Comment by kaspermarstal** [comment]
I cannot give you the exact CMake steps because I haven`t been able to install OpenCL on my system.  

The steps you outline above are correct. But to make the manual build work, I think the language wrappers also need to be linked against the OpenCL binaries which require some changes to the build system.

**Comment by kaspermarstal** [comment]
Will have a look this afternoon!

**Comment by NHPatterson** [comment]
Hi @kaspermarstal, testing the SuperBuild with the fixes you added on Ubuntu 16.04. I get the following error:

> -- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenCL (missing: OpenCL_LIBRARY) (found version "1.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindOpenCL.cmake:128 (find_package_handle_standard_args)
  CMakeLists.txt:107 (find_package)

Is version 2.0 necessary?

**Comment by kaspermarstal** [comment]
Does this work for you @richhend?

**Comment by richhend** [comment]
Sorry, I didn't see that you had updated the OpenCL branch. Thanks a lot for looking into this again.

I just tried to build with the updated OpenCL branch on Windows with 

cmake -G "Visual Studio 14 2015 Win64" ^
More? -DPYTHON_EXECUTABLE:FILEPATH=C:\Users\SPIM\lux\comp_SE\Anaconda3\python.exe ^
More? -DPYTHON_LIBRARY:FILEPATH=C:\Users\SPIM\lux\comp_SE\Anaconda3\libs\python36.lib ^
More? -DPYTHON_INCLUDE_DIR:PATH=C:\Users\SPIM\lux\comp_SE\Anaconda3\include ^
More? -DBUILD_EXAMPLES=OFF ^
More? -DBUILD_TESTING=OFF ^
More? -DSimpleITK_4D_IMAGES=ON ^
More? -DITK_USE_64BITS_IDS=ON ^
More? -DWRAP_PYTHON=ON ^
More? -DWRAP_DEFAULT=OFF ^
More? -DWRAP_CSHARP=OFF ^
More? -DWRAP_LUA=OFF ^
More? -DWRAP_R=OFF ^
More? -DWRAP_JAVA=OFF ^
More? -DWRAP_TCL=OFF ^
More? -DWRAP_RUBY=OFF ^
More? -DSimpleITK_OPENCL=ON ^
More? C:\comp_SE\SimpleElastix-opencl\SuperBuild

Then:
msbuild /p:configuration=release ALL_BUILD.vcxproj

But I got an error and several warnings (mostly linker issues) which I think I had already gotten before when building the opencl branch with SimpleElastix_OPENCL=OFF, though _not_ when building the master branch, which leads me to assume that these are issues with the opencl branch that are not related to OpenCL (?)
I attached the CMakeError.log and CMakeOutput.log files.

Any idea?

Thank you very much

[CMakeOutput.log](https://github.com/SuperElastix/SimpleElastix/files/1543128/CMakeOutput.log)

[CMakeError.log](https://github.com/SuperElastix/SimpleElastix/files/1543104/CMakeError.log)

**Comment by NHPatterson** [comment]
I also wasn't able to compile with OpenCL on Ubuntu 16.04. I had numerous errors during the SimpleITK build.

**Comment by kaspermarstal** [comment]
@richhend @NHPatterson Yes I have seen these dcfln.h errors before but I don't know what to do about them. They are related to SimpleITKs test of weak linking. Do you see the same errors when you compile SimpleITK?

**Comment by kaspermarstal** [comment]
@richhend your error log seems to be output from the cmake tests that run during configuration, not during the build. Is this correct? Could you cd into the SimpleITK-build directory and check if this is the case? Can you post the output from when you restart the build in this directory?

**Comment by kaspermarstal** [comment]
@jcfr Seeing that you contributed fcb4aa7af4cde22a364b59b13300fd744f64acac could you clarify if users need to install dlfcn.h on their own or if it something that is supposed to work out of the box with SimpleITK? A lot of elasting users have encountered missing dlfcn.h and I am wondering if the problem is with SimpleElastix. Thank you for your time!

**Comment by jcfr** [comment]
Hi @kaspermarstal , 

> could you clarify if users need to install dlfcn.h
No. This header should be available  on the system 

> A lot of SimpleElastix users have encountered the missing dlfcn.h error and I am wondering if the problem is with SimpleElastix. 

Could you share the steps allowing to reproduce the problem ? 

Thanks
Jc

**Comment by svankranen** [comment]
Hi Kasper, 

I simply followed the compilation instructions and I'm seeing the same _fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory_. I'm compiling at windows 7, 64 bits, MSbuild VS2015 Command prompt, with Anaconda 3, are there any suggestions I could try?

Cheers!

Simon

**Comment by kaspermarstal** [comment]
@svankranen Does the same thing happen if you try to build SimpleITK? I cannot reproduce the problem locally so it would be really helpful if you could try this!

**Comment by jcfr** [comment]
> I'm compiling at windows 7, 64 bits, MSbuild VS2015 Command prompt, with Anaconda 3, are there any suggestions I could try?

Could you be more specific ? 

For example:

1. Open Visual Studio 64-bit command line terminal
2. Type command ...

**Comment by svankranen** [comment]
Hi kasper and jcfr, I got it to work! The following discussion helped me in the right direction:
https://github.com/SuperElastix/SimpleElastix/issues/105
As it turned out, I downloaded the zip, and did not directly clone from github. That basically fixed things for me.
Thnx for following up!

**Comment by kaspermarstal** [comment]
@svankranen Great you got it up and working! Still, could you outline the steps required to reproduce the error?

**Comment by cipri-tom** [comment]
Hi all,

This is just to confirm that building with OpenCL works well on Linux.

For anyone new at this, here's what I did:
 - `git checkout opencl`
 - `mkdir build_opencl && cd build_opencl`
 - `ccmake ../SuperBuild/` and toggle the OpenCL setting (need to press `t` to show it); optionally also `OpenMP`
 - install openCL: on Ubuntu, `sudo apt install ocl-icd-opencl-dev`
 - `make -j4`
 - search for `OpenCL` [here](http://elastix.isi.uu.nl/doxygen/parameter.html) to see available parameters that can use OpenCL and replace them in the parameter map.

Cheers!

**Comment by kaspermarstal** [comment]
Thanks @cipri-tom!

**Comment by kaspermarstal** [comment]
The OpenCL features made the build unstable even for users who did not need OpenCL. We decided  to treat this as an advanced use case and not support it out of the box. The OpenCL branch was removed to reduce the burden of maintaining two separate builds. 

If you need OpenCL you can compile elastix as a standalone project and then pass `-DUSE_SYSTEM_ELASTIX=ON` and `-DELASTIX_DIR=/path/to/elastix/build/dir` the SuperBuild when compiling SimpleElastix.

**Comment by jackransomlovell** [comment]
@kaspermarstal, when compiling elastix as a standalone project for OpenCL use does one need to pass any tags to cmake when compiling? or are these now automatically set to compile with OpenCL?
