### ISSUE TITLE
Transforming point set

### ISSUE THREAD

**Issue by DarioFarotto** [SuperElastix/SimpleElastix#147]
## Hi all, Kasper

Thank you very much for your work
I hope I'll be able to find a solution to my problem here.

I'm using simpleElastix on Python and I following the last example of the documentation:
(https://simpleelastix.readthedocs.io/PointBasedRegistration.html)
Transforming Point Sets

import SimpleITK as sitk

Compute the transformation from moving image to the fixed image
elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(sitk.ReadImage("fixedImage.nii")
elastixImageFilter.SetMovingImage(sitk.ReadImage("movingImage.nii")
elastixImageFilter.Execute()

Warp point set. The transformed points will be written to a file named
 outputpoints.txt in the output directory determined by SetOutputDirectory()
(defaults to working directory)
transformixImageFilter = sitk.TransformixImageFilter()
transformixImageFilter.SetTransformParameterMap(elastixImageFilter.GetTransformParameterMap())
transformixImageFilter.SetFixedPointSet("fixedPointSet.pts")
transformixImageFilter.Execute()

If I use the same algorithm on the documentation I get an error unless I set a moving image as well, regardless on the moving image, and without an real effect on the results:
transformixImageFilter.SetMovingImage(movingImage=movingImage).

The error I get is:
RuntimeError: Exception thrown in SimpleITK TransformixImageFilter_Execute: E:\Software\SimpleElastix\src\Code\Elastix\src\sitkTransformixImageFilterImpl.cxx:109:
sitk::ERROR: 
itk::ExceptionObject (000000000031C3A0)
Location: "unknown" 
File: e:\software\se\bin\elastix\src\core\main\elxTransformixFilter.hxx
Line: 212
Description: itk::ERROR: Self(0000000002B69910): Internal transformix error: See transformix log (use LogToConsoleOn() or LogToFileOn())

Has anybody experienced the same problem?
Did anybody solve it?

PS. one extra thing:
The method 'SetFixedPointSet' indicated on the documentation  does not exist, one has to use  'SetFixedPointSetFileName'

Thank you in advance for the answer,
Dario

**Comment by kaspermarstal** [comment]
Hi Dario

Yes, you have to set the moving image as well. Transformix uses this to obtain information about the moving image dimension. This should ideally be fixed upstream in elastix. PRs are welcome.

Thank for the notice. Will update documentation.

Kasper

**Comment by DarioFarotto** [comment]
Hi Kasper,

Thank you a lot for your answer
It is possible that his has already been fixed?
If I call transformix from the command line it is not necessary to define a moving image, hence my confusion on why it's necessary on simpleElastix 

Kind regards,
Dario

**Comment by kaspermarstal** [comment]
It's for historic reasons mostly. The library API (which SimpleElastix is using) was added on to the command line code at a later stage and not all features were ported at the time.

**Comment by kaspermarstal** [comment]
This has since been fixed. You no longer need to pass TransformixImageFilter a moving image.

**Comment by MarHHM** [comment]
> This has since been fixed. You no longer need to pass TransformixImageFilter a moving image.

Hi Kasper,,

I've recently faced the same error when i don't supply a moving image to transformix (```
Description: itk::ERROR: Image(0x1a1f3b0): Bad direction, determinant is 0. Direction is 1 0
0 0
```)

Are you sure it was fixed??

**Comment by alexkaiser** [comment]
@MarHHM I was having a similar issue, and it appears to be related to the dimensions read by default of some images. Applying the solution in this comment resolved it for me: 
https://github.com/SuperElastix/SimpleElastix/issues/113#issuecomment-317417911

@kaspermarstal Thank you for the advice and very nice software library!
