### ISSUE TITLE
Can't visualize deformation field or spatial Jacobian results?

### ISSUE THREAD

**Issue by ascourtas** [SuperElastix/SimpleElastix#148]
Hello!

I'm having trouble understanding what is necessary to view the deformationField.mhd and spatialJacobian.mhd files. I'm using Snap-ITK to view the MetaImages, but they come out either entirely black or entirely white. 

Is the only purpose of having these in an mhd format so that it mirrors the original image, and the expectation is I loop through the raster to extract the values? Is there no actual image to view?

Also, the Elastix manual says I should be getting a determinant of Jacobian for the whole image, but I don't see that in the output.

Any help is greatly appreciated!

**Comment by kaspermarstal** [comment]
Is the registration successful? If so, what is the range of the deformation? If it is lover than 1.0, are the images being cast to integral type (thus implicitly runding to floor)?

In ITK-SNAP, have you set Multi-component Display to RGB? 

If you are not seeing the Jacobian of the whole image, what are you seeing? No region? A smaller region?

**Comment by ascourtas** [comment]
The registration is indeed successful. I don't know where to find the "range of deformation"? The transformix.log file has not been printing for me, so if it's in there I cannot see it. 

I don't have the option to set the multi-component display to RGB. Here are screenshots of my attempts to view both spatialJacobian.mhd and fullSpatialJacobian.mhd

<img width="703" alt="screen shot 2017-11-10 at 12 22 16 pm" src="https://user-images.githubusercontent.com/18538526/32670548-1ae4bc3c-c612-11e7-9309-27d2d6d2f695.png">
<img width="1358" alt="screen shot 2017-11-10 at 12 22 57 pm" src="https://user-images.githubusercontent.com/18538526/32670549-1aef43e6-c612-11e7-85b5-d093e21df2ad.png">


Maybe I am misunderstanding, but I thought the determinant of the Jacobian was one value? Not an image?

**Comment by PertuyF** [comment]
The Jacobian is indeed one value, for each pixel. Which creates another image in the end.
If the displacement is low, the jacobian values can be lower than 1 (as @kaspermarstal just said), you may have to adjust the histogram range for visualisation, and you should make sure the values are not converted to integer type.

**Comment by ascourtas** [comment]
ah ok, thank you @PertuyF and @kaspermarstal , that makes more sense now, I will check it out
