### ISSUE TITLE
bspline low swap fault

### ISSUE THREAD

**Issue by the4thchild** [SuperElastix/SimpleElastix#149]
I've been successfully registering 772x49x519 and 581x370x279 (x,y,z) images using ```translation``` and ```affine``` parameter maps. When I apply the ```bspline``` map, however, I get a low swap error leading to a killed process with this system error message:

```
kernel	low swap: killing largest compressed process with pid 95770 (python3.5) and size 728 MB
```

I tried to reduce as many parameter as I could one by one, going as far as these settings:
```
    param_map = sitk.GetDefaultParameterMap("bspline")
    param_map["MaximumNumberOfIterations"] = ["1"]
    param_map["MaximumNumberOfSamplingAttempts"] = ["1"]
    param_map["MaximumNumberOfIterations"] = ["1"]
    param_map["NumberOfSamplesForExactGradient"] = ["1"]
    param_map["NumberOfSpatialSamples"] = ["1"]
```

but get the same error, whether I apply bspline map after the other maps or by itself. Is there a way to further reduce the memory requirement, or is this a limitation of bspline on images of this size?

I've tested on both the master branch commit abf921e and develop branch commit 7e0ce6f.

Thanks!

**Comment by PertuyF** [comment]
Hi @the4thchild ,

You can try to reduce the `NumberOfResolution`, but it will not be a huge change. Other memory optimisation may be achieved in other parts of your code (not necessarily related to `SimpleElastix`).
Could you try to monitor memory usage dynamically? (Total memory available/used? Are there other large objects loaded into memory? Total swap size? etc...)

**Comment by kaspermarstal** [comment]
In addition to Fabiens suggestions you can also try to increase the FinalGridSpacingInPhysicalUnits. I think the default is 10mm. You could increase that depending on the structures you are registering.

**Comment by the4thchild** [comment]
Thanks so much for your helpful hints. I tried increasing ```FinalGridSpacingInPhysicalUnits``` from 8 to 20 and was able to avoid the segmentation fault, though the process has been stuck at ```Computing JacobianTerms ...``` for hours. If I increase the value to much higher, such as 50 or 100, the process aborts with the ```itk::ERROR: AdvancedMattesMutualInformationMetric(0x7fd5dd111e00): Too many samples map outside moving image buffer: 0 / 1``` error.

I also tried adjusting ```NumberOfResolution``` along with reducing the ```GridSpacingSchedule``` number of parameters to match in addition to the ```FinalGridSpacingInPhysicalUnits``` adjustment but still got stuck on JacobianTerms computation.

Memory usage is at 24GB with current settings of:
```
    param_map = sitk.GetDefaultParameterMap("bspline")
    param_map["MaximumNumberOfSamplingAttempts"] = ["1"]
    param_map["FinalGridSpacingInPhysicalUnits"] = ["20"]
```

Does this process normally take this much memory and time (went up to half a day before I stopped it)? Is there a way to turn on feedback for status on the progress of this process? (I set ```LogToConsoleOn``` but get the same feedback as before.)

Thanks for all your help.

**Comment by PertuyF** [comment]
I can't see how you could fill 24GB RAM with this registration. What is your memory usage immediately before you start `execute()`?
What are you using for the execution? (script? IPython?)

**Comment by the4thchild** [comment]
Yes the memory usage perplexes me. Using Memory Profiler, memory usage right before ``execute`` is about 500MB. When I run registration with just the ```translation``` parameter map, memory usage is about 1.1GB after ``execute``. I'm launching from a script/module (not IPython). Is there something about ```bspline``` that uses considerably more memory than the other parameter maps, perhaps for these image dimensions?

**Comment by PertuyF** [comment]
I would say the `FinalGridSpacing` would be an obvious suspect, as mentioned by @kaspermarstal.
Do you know the scale of your images? If it is large (close or above the mm/px scale) it could mean that your deformation grid is too dense.

You could try using `FinalGridSpacingInVoxels` instead, with a value of 64 for a start (just for testing). The advantage here is that the grid spacing will be absolute instead of relative to your image scaling.

**Comment by the4thchild** [comment]
```FinalGridSpacingInVoxels``` worked! The process completed and showed the bspline transformation. Memory usage was similar after ```Execute``` as with the ```translation``` parameter map. Here are the parameter map settings that I applied to ```bspline```, after transforming with ```translation``` and ```affine```:
```
    param_map["MaximumNumberOfSamplingAttempts"] = ["1"]
    param_map["FinalGridSpacingInPhysicalUnits"] = [] # turn off to avoid conflict with next param
    param_map["FinalGridSpacingInVoxels"] = ["64"]
```

The image dimensions and spacing that I used are (in x, y, z order):

- Fixed image: 772 x 49 x 519 with spacing of 18.26 x 98.7 x 18.26
- Moving image: 581 x 370 x 278 with spacing of 16 x 16 x 20

There is a pretty large discrepancy between the y-size/spacing of the two images. Do you think that changing ```FinalGridSpacingInVoxels``` was required because of the size or discrepancy of these dimensions?

Thanks again!

**Comment by PertuyF** [comment]
Well, to me this definitely explains why `FinalGridSpacingInPhysicalUnits` was consuming a lot of RAM. If the scaling you mention is in millimeters it means that a value of 10 in physical units is worth a very dense grid, which will be very large in memory. The resulting transform would also be far too precise (something like half a pixel for each weight) if I'm right.

Any thoughts related to using `FinalGridSpacingInVoxels` with such unevenly spaced images @kaspermarstal? I'm not used to this situation at all. 

---

BTW, you can "turn off" `FinalGridSpacingInPhysicalUnits` by deleting the key from your parameter map instead of setting it to and empty list.

```python
del param_map["FinalGridSpacingInPhysicalUnits"]
```

**Comment by the4thchild** [comment]
That's very helpful to know about the memory usage in ```FinalGridSpacingInPhysicalUnits``` compared with ```FinalGridSpacingInVoxels``` for this uneven spacing. My spacing is in microns (mouse images), though I haven't set the units (explicitly at least).

Thanks for pointing out the key deletion, certainly cleaner that way.
