### ISSUE TITLE
Documentation discrepancy in "Transforming Point Sets"

### ISSUE THREAD

**Issue by ascourtas** [SuperElastix/SimpleElastix#150]
In the "Transforming Point Sets" subsection of "Point-Based Registration", it reads as follows:
<img width="749" alt="screen shot 2017-11-16 at 11 49 47 am" src="https://user-images.githubusercontent.com/18538526/32904000-69d736ce-cac4-11e7-966d-984f10ccd2ad.png">

The first comment says we're computing the transformation from moving to fixed image, but then the warning box says if we want the transformation from moving to fixed image, we need to use the inverse transform. What is actually going on here? I thought we map points from fixed to moving image, and then deform the moving image based on those points?

**Comment by kaspermarstal** [comment]
> I thought we map points from fixed to moving image, and then deform the moving image based on those points?

You are right. The first comment is misleading.

**Comment by kaspermarstal** [comment]
Thanks!
