### ISSUE TITLE
Windows Python Binaries

### ISSUE THREAD

**Issue by erin5116** [SuperElastix/SimpleElastix#152]
Hi,

I just installed the python binaries on windows, and tried to do a simple example to test elastix by:
fImage = SimpleITK.ReadImage("fixedImage.nii")
mImage = SimpleITK.ReadImage("movingImage.nii")
result = SimpleITK.Elastix(fixedImage, movingImage)

Keep getting the following error, both in command line and in python shell. It seems to try access F drive, but I dont have one on my computer?!

Traceback (most recent call last):
  File "<pyshell#47>", line 1, in <module>
    result=SimpleITK.Elastix(fImg,mImg)
  File "C:\Python34\lib\site-packages\SimpleITK\SimpleITK.py", line 9189, in Elastix
    return _SimpleITK.Elastix(*args)
RuntimeError: Exception thrown in SimpleITK Elastix: F:\prog\SimpleElastix\src1\Code\Elastix\include\sitkSimpleElastix.hxx:63:
sitk::ERROR: 
itk::ExceptionObject (0000000000C0B6F8)
Location: "unknown" 
File: f:\prog\simpleelastix\bld2\elastix\src\core\main\elxElastixFilter.hxx
Line: 236
Description: itk::ERROR: Self(00000000059D74E0): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

**Comment by kaspermarstal** [comment]
The path refers the to computer on which the binary was compiled not on your computer. This just tells the programmer where the exception is thrown.

As the error message says, you can look in the elastix log to see what the real error is. You can see this message using `result = SimpleITK.Elastix(fixedImage, movingImage, True)` (or LogToConsoleOn() if you were using the object-oriented interface).

**Comment by erin5116** [comment]
The error log generated was empty, which was the most confusing part!

**Comment by kaspermarstal** [comment]
So the log file is created on disk, but it is an empty file? If so, can you log to console to see the error?

**Comment by erin5116** [comment]
Hi,

I have tried it again to see what happens. It didn't generate an error log (assuming it should generate in the directory I am working in)

_>>> result = sitk.Elastix(fimg, mimg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\SimpleITK\SimpleITK.py", line 9189, in Elastix
    return _SimpleITK.Elastix(*args)
RuntimeError: Exception thrown in SimpleITK Elastix: F:\prog\SimpleElastix\src1\Code\Elastix\include\sitkSimpleElastix.hxx:63:
sitk::ERROR:
itk::ExceptionObject (00000000005EBE98)
Location: "unknown"
File: f:\prog\simpleelastix\bld2\elastix\src\core\main\elxElastixFilter.hxx
Line: 236
Description: itk::ERROR: Self(0000000004F58B90): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn())._

All it generated was "IterationInfo.0.R0.txt" which is empty.
I tried using LogToConsoleOn() but it didn't appear to be a function in sitk. Is there a library I have to do this? 

I got someone to try the Python module on their computer, and he informed me that it might be because I am using a Win10 environment. Would you think this is the case?

**Comment by kaspermarstal** [comment]
`LogToConsoleOn()`and `LogToFileOn()` is part of the object-oriented interface, e.g.
 
    elastixImageFilter = sitk.ElastixImageFilter()
    elastixImageFilter.SetFixedImage(fixedImage)
    elastixImageFilter.SetMovingImage(movingImage)
    elastixImageFilter.LogToConsoleOn()
    elastixImageFilter.LogToFileOn()
    resultImage = elastixImageFilter.Execute()

To log with `Elastix()`, run `result = SimpleITK.Elastix(fixedImage, movingImage, True)`. Try both :)

**Comment by erin5116** [comment]
I ended up compiling it on my computer (ran into a problem because I didn't choose the right x64 compiler, but should be all fixed now), because I thought it might be because of my windows environment.

Now it is giving me a different error:

itk::ExceptionObject (0000000000FEB9E0)
Location: "ElastixTemplate - Run()"
File: d:\programs\elastix\elastix\common\costfunctions\itkAdvancedImageToImageMetric.hxx
Line: 1066
Description: itk::ERROR: AdvancedMattesMutualInformationMetric(0000000006777DD0): Too many samples map outside moving image buffer: 0 / 5250


Error occurred during actual registration.


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\simpleitk-1.0.1rc1.dev345+g9dfa8-py3.4-win-amd64.egg\SimpleITK\SimpleITK.py", line 10190, in Elastix
    return _SimpleITK.Elastix(*args)
RuntimeError: Exception thrown in SimpleITK Elastix: D:\Erin\Documents\GitHub\SimpleElastix\Code\Elastix\src\sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR:
itk::ExceptionObject (0000000000FEBE40)
Location: "unknown"
File: d:\programs\elastix\elastix\core\main\elxElastixFilter.hxx
Line: 253
Description: itk::ERROR: Self(0000000006773C30): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).


Is this something to do with how I compiled it?

**Comment by kaspermarstal** [comment]
No, this is because the images do not overlap in the world coordinate system. You can try to enable automatric transform initialization by setting "AutomaticTransformInitialization" to "true". More info [here](http://elastix.isi.uu.nl/doxygen/classelastix_1_1AdvancedAffineTransformElastix.html).

**Comment by erin5116** [comment]
The two images that I am testing the functions with are the same one, so they should have same coordinates right?

**Comment by erin5116** [comment]
I went back to the test files, copied the moving image and renamed it as fixed image, and tested it. It worked!
Thanks for your help!
