### ISSUE TITLE
Installation error at CMake/sitkSourceVersion.cmake with Visual Studio 2010

### ISSUE THREAD

**Issue by martinaberni** [SuperElastix/SimpleElastix#153]
Hi,
I'm trying to install SimpleElastix on Windows using Visual Studio 2010 using the instruction provided by the documentation. But the project building returns me the following error:
![image](https://user-images.githubusercontent.com/34073859/33340531-f4182e3e-d441-11e7-9fd5-d1eb36bfdee8.png)
Does anyone know how can I solve it?
Thank you

**Comment by kaspermarstal** [comment]
Try to use `git clone https://github.com/SuperElastix/SimpleElastix` to download the code. You probably downloaded it in some other way. This is an old error that will be fixed in the next release. Let me know if cloning does not help you.

**Comment by martinaberni** [comment]
Despite cloning, I still have the following error:
![image](https://user-images.githubusercontent.com/34073859/33457811-5daa1efe-d5e9-11e7-8276-11080f1d9201.png)

**Comment by kaspermarstal** [comment]
Can you double check that you are indeed pointing CMake the cloned directory? It still says "GITDIR-NOTFOUND" which shouldn't happen when using the git source directory.

**Comment by martinaberni** [comment]
Yes, to be sure of that I delete the downloaded directory. I have a Git directory in the source folder for CMake, while where the bin are built the Git directory is in ITK\Utilities. Should I have more Git directories? Where?

**Comment by kaspermarstal** [comment]
I am sorry, I don't know why you see this error. If anyone know this happens, suggestions are welcome.

**Comment by kaspermarstal** [comment]
This has been fixed upstream and therefore resolved in this project as well.
