### ISSUE TITLE
GPU memory leak from direct elastix call with OpenCL on

### ISSUE THREAD

**Issue by liu3xing3long** [SuperElastix/SimpleElastix#157]
I have extended the ElastixImageFilter with OpenCLResampler included in the original Elastix repo. When using **itkGPUImage**, the GPU memory will not be released since the reference counter is always set to at least 2. One ref is from the GPUImage itself, but the other ref is coming from the internal GPUImageDataManager inside the class (with **SetImagePointer** call ), which leads to a recurrent smart pointer counter. And the itkGPUImage allocated will never be released until the whole programme exits. 

I have simply altered the SetImagePointer signature to allow this method accept normal pointers but not smart pointer to avoid reference increment.  Not sure if this is the best solution, but it surely is the simplest. 

I believe this should be some bug to the original Elastix package, however I do not find any issue reporting for this package on Github, therefore I place it here to someone who may encounter the same problem.

**Comment by kaspermarstal** [comment]
Hi thanks for your bug report! Do you also see this error with normal images? I.e. not itkGPUImage but normal itkImage?

You can open an issue here https://github.com/SuperElastix/elastix.

**Comment by liu3xing3long** [comment]
Nope, the usual CPU image (itk::Image) works well, this can be observed by the Print function after image allocation. Typically, when you allocate a new itk::Image the default reference count is 1, and the image would be releases out of function scope. Meanwhile, when you allocate a new itk::GPUImage, the ref count is exactly the same 1, but after graft data using methods like GraftITK from CPU itk Images, the ref count is set as 2, in which the 2nd ref is set by GPUImageDataManager, making the GPU image not properly released.

**Comment by liu3xing3long** [comment]
Also, have open a new issue in elastix project. Please feel free to close this issue in this project. Thank you very much.

**Comment by kaspermarstal** [comment]
Great, thanks!
