### ISSUE TITLE
Installation Error Mac

### ISSUE THREAD

**Issue by TylerCork** [SuperElastix/SimpleElastix#163]
I am attempting to build SimpleElastix on a MacBook Pro. I have followed the installation guide and included the setup portion of my install. I believe the error occurs during the Ruby portion of the build.

Last login: Sat Jan 27 09:30:15 on console
s-164-67-206-230:~ TylerCork$ git clone https://github.com/SuperElastix/SimpleElastix
Cloning into 'SimpleElastix'...
remote: Counting objects: 37597, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 37597 (delta 18), reused 21 (delta 9), pack-reused 37561
Receiving objects: 100% (37597/37597), 15.35 MiB | 2.31 MiB/s, done.
Resolving deltas: 100% (22172/22172), done.
s-164-67-206-230:~ TylerCork$ mkdir build
s-164-67-206-230:~ TylerCork$ cd build
s-164-67-206-230:build TylerCork$ cmake -DCMAKE_CXX_COMPILER:STRING=/usr/bin/clang++ -DCMAKE_C_COMPILER:STRING=/usr/bin/clang ../SimpleElastix/SuperBuild
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.14.3 (Apple Git-98)") 
-- Setting build type to 'Release' as none was specified.
-- Performing Test CXX_HAS_stdcxx11
-- Performing Test CXX_HAS_stdcxx11 - Success
-- Checking if c++11 is required...
-- Checking if c++11 is required... YES
-- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Failed
-- Performing Test Weak Link MODULE -> SHARED (osx_dynamic_lookup) - Success
-- Found Tclsh: /Users/tylercork/anaconda2/bin/tclsh (found version "8.6") 
-- Found BISON: /usr/bin/bison (found version "2.3") 
-- Passing variable "ITK_BUILD_DEFAULT_MODULES=ON" to ITK external project.
-- Passing variable "Module_ITKReview=ON" to ITK external project.
-- Passing variable "SITK_CHECK_CXX11=FALSE" to SimpleITK external project.
-- Passing variable "SimpleITK_4D_IMAGES=ON" to SimpleITK external project.
-- Passing variable "SimpleITK_GIT_PROTOCOL=https" to SimpleITK external project.
-- Passing variable "SimpleITK_LUA_EXECUTABLE=/Users/tylercork/build/Lua/bin/lua" to SimpleITK external project.
-- Passing variable "SimpleITK_OPENMP=OFF" to SimpleITK external project.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tylercork/build
s-164-67-206-230:~ TylerCork$ make -j4
.
.
.
Scanning dependencies of target ImageRegistrationMethod1
[ 67%] Building CXX object Examples/ImageRegistrationMethod1/CMakeFiles/ImageRegistrationMethod1.dir/ImageRegistrationMethod1.cxx.o
[ 67%] Linking CXX executable ../../bin/ImageRegistrationMethod1
. (warnings)
[ 67%] Built target SimpleITKTclsh
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2

Thanks for your help!

**Comment by kaspermarstal** [comment]
Try to execute it without the `j4` so it stops when the error occurs, and then post the error message.

**Comment by TylerCork** [comment]
ran it with one CPU and got this result


3 errors generated.
make[5]: *** [Wrapping/Ruby/CMakeFiles/simpleitk_RUBY.dir/SimpleITKRUBY_wrap.cxx.o] Error 1
make[4]: *** [Wrapping/Ruby/CMakeFiles/simpleitk_RUBY.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2

**Comment by TylerCork** [comment]
Just checking to see if there was any updates

**Comment by kaspermarstal** [comment]
You can set WRAP_RUBY to OFF (if you don't need RUBY). SimpleITK 1.1 will be merged as soon as it's released and hopefully this will fix the issue, otherwise I will investigate once it is merged.

**Comment by jspatil7** [comment]
Can you tell me how to set WRAP_RUBY to OFF? I am new to linux and I have the same error.

**Comment by kshannon** [comment]
Hi @jspatil7 I am encountering the same error:
```
3 errors generated.
make[5]: *** [Wrapping/Ruby/CMakeFiles/simpleitk_RUBY.dir/SimpleITKRUBY_wrap.cxx.o] Error 1
make[4]: *** [Wrapping/Ruby/CMakeFiles/simpleitk_RUBY.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
```
Following @kaspermarstal advice, you can set WRAP_RUBY to OFF by going into the Build directory you created (after you have run: [$ cmake ../SimpleElastix/SuperBuild](https://simpleelastix.readthedocs.io/GettingStarted.html)) and with an editor open the file: 
**CMakeCache.txt** 

There search for this line:
```
//Wrap Ruby
WRAP_RUBY:BOOL=ON
```

Simply change ON to OFF and save the file. This seems to have worked for me. Hope this helps!

**Comment by kaspermarstal** [comment]
Closing :)

**Comment by LIN810116** [comment]
I was encountering a similar but R related error. It was solved by setting WRAP_R to OFF

```
ERROR: this R is version 3.0.2, package 'SimpleITK' requires R >= 3.3
make[5]: *** [Wrapping/R/Packaging/SimpleITK/src/SimpleITK.so] Error 1
make[5]: *** Deleting file `Wrapping/R/Packaging/SimpleITK/src/SimpleITK.so'
make[4]: *** [Wrapping/R/CMakeFiles/SimpleITK_R.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
```
