### ISSUE TITLE
Possibility to estimate transformation without resampling full image

### ISSUE THREAD

**Issue by NHPatterson** [SuperElastix/SimpleElastix#164]
Hello,

I am trying to grid search over a number of hyper parameters to find the best settings for a new and challenging registration problem. In order to speed up the experiment I would like to avoid re-sampling the moving image as the final step because with my images this tends to eat up 30-45s each time.  Is there a way to turn this off and just return the transformation map without the transformed image?

Thanks!

**Comment by PertuyF** [comment]
Yes, you can do this be setting `WriteResultImage` to `False` in the parameters file. More details in [Elastix documentation](http://elastix.isi.uu.nl/doxygen/classResampleBase.html).

**Comment by NHPatterson** [comment]
Thanks, that was the issue.  I thought that function was not integrated in SimpleElastix.
