### ISSUE TITLE
input and output of the hello world example

### ISSUE THREAD

**Issue by guist** [SuperElastix/SimpleElastix#165]
Hello,

I wanted to run the hello world example but I could not find where the .nii files are located, so I tried with png images as input:

`fixedImage` = sitk.ReadImage('../data/BrainProtonDensity.png')'
`movingImage` = sitk.ReadImage('../data/BrainProtonDensityTranslated13x17y.png')'
 
and a png image as output:

`sitk.WriteImage(transformixImageFilter.GetResultImage(),` "out.png")

Unfortunately I get the following error:

"PNG supports unsigned char and unsigned short"

Concerning the input images, I was wondering if the png format is authorized or only the nii format.

Concerning the output, I would like to know how to manipulate further the result image. Is it possible to store it in a numpy array?

Thank you!
Guillaume

**Comment by PertuyF** [comment]
Hi @guist ,
PNG is clearly not the best for this purpose. I guess your error comes from the output of SimpleElastix which has a pixeltype not supported by PNG, you should try to use another format for the output.

Regarding your last question, you can cast to result (an `sitk.Image`) to a `numpy.array` with
```python
a = sitk.GetArrayFromImage(transformixImageFilter.GetResultImage())
```
If you're new to simpleITK, you may find [these notebooks](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/) interesting.

**Comment by guist** [comment]
Thank you, I could get the array I wanted.
