### ISSUE TITLE
ExecuteInverse no longer exists

### ISSUE THREAD

**Issue by gaklein2007** [SuperElastix/SimpleElastix#167]
I have been trying to perform an inverse mapping to bring an altered mask to the proper image, but noticed that with the new update that ExecuteInverse was removed. What is the best way to perform this now, and/or does it need to be done fully manually now?

**Comment by kaspermarstal** [comment]
Yes it has to be done manually now as outlined in the [elastix manual](http://elastix.isi.uu.nl/download/elastix_manual_v4.8.pdf). 

It was remove because the implementation was not robust and would fail in some cases which was frustrating for a lot of users.
