### ISSUE TITLE
Using a ParameterMap as python dict with .update()

### ISSUE THREAD

**Issue by romangrothausmann** [SuperElastix/SimpleElastix#169]
It seems a ParameterMap (pM) can be interpreted as a dict (help(pM) lists .asdict()). Python also does not complain on:
```
import SimpleITK as sitk
selx = sitk.ElastixImageFilter()
pM= selx.ReadParameterFile("ParameterFile.txt")
pM['MaximumNumberOfIterations']= ['10', '50', '30', '20'] # has an effect
print pM['MaximumNumberOfIterations']
pM.asdict().update(MaximumNumberOfIterations=['1', '5', '3', '2']) # has no effect
print pM['MaximumNumberOfIterations']
```
but `.update()` seems to have no effect. I'd like to replace parameters of a default parameter file with some set of specifications (multiple parameters) also defined in a text file like a normal elastix ParameterFile.txt, containing e.g. only:
```
(NumberOfResolutions 4)
(ImagePyramidSchedule  256 256  128 128  64 64  32 32)
(MaximumNumberOfIterations 10 500 300 200)
```

**Comment by romangrothausmann** [comment]
Thanks @PertuyF for the quick reply. So selx is basically missing a set-method that allows to set multiple parameters in one go with a dict? I.e. strictly speaking, a parameter map is not a "dict of vectors" (https://github.com/SuperElastix/SimpleElastix/issues/119#issuecomment-319625926) but can only be interpreted as such?
The closest to get to that then is likely:
```
for key, value in updateDict.items():
     pM[key]= value
```

**Comment by kaspermarstal** [comment]
Yes I think you have to do this. `pM`  is a wrapped `std::map<std::string, std::vector<std::string>>` that behaves like a dict in most cases but lacks some functionality of a true dict.

**Comment by romangrothausmann** [comment]
Thanks @kaspermarstal for that clarification, I was not able to find that info in the docs. I found the definition in the code but was not sure what the wrapping was lacking to be exposed as a full python dict.
