### ISSUE TITLE
SplineKernelTransform not implemented?

### ISSUE THREAD

**Issue by mary-alegro** [SuperElastix/SimpleElastix#171]
I'm trying to run a simples test using ThinPlateSpline:
```
ref = sitk.ReadImage('1181_001-Whole-Brain_0457.png.nii')
mov = sitk.ReadImage('AT100_457_affine_centered.nii')

parameterMap = sitk.GetDefaultParameterMap("bspline")
parameterMap['Transform'] = ['SplineKernelTransform']
parameterMap['SplineKernelType'] = ['ThinPlateSpline']

parameterMapVector = sitk.VectorOfParameterMap()
parameterMapVector.append(parameterMap)

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetParameterMap(parameterMapVector)
elastixImageFilter.LogToConsoleOn()
elastixImageFilter.PrintParameterMap()

elastixImageFilter.SetFixedImage(ref)
elastixImageFilter.SetMovingImage(mov)
elastixImageFilter.SetFixedPointSetFileName('ref_ants_ctr.pts')
elastixImageFilter.SetMovingPointSetFileName('mov_ants_ctr.pts')

elastixImageFilter.Execute()
```
However, it returns the following error:

> itk::ExceptionObject (0x36b44e0)
> Location: "ElastixTemplate - Run()" 
> File: /home/maryana/bin/simpleelastixbuild/ITK/Modules/Core/Common/src/itkMultiThreader.cxx
> Line: 427
> Description: itk::ERROR: MultiThreader(0x46d97c0): Exception occurred during SingleMethodExecute
> /home/maryana/bin/simpleelastixbuild/Elastix/Components/Transforms/SplineKernelTransform/itkKernelTransform2.h:344:
> itk::ERROR: ThinPlateR2LogRSplineKernelTransform2(0x343ed30): Not implemented for KernelTransform2

I'm brand new to SimpleElastix but it is my understanding that it was supposed to work. At least that's what I understood from issue [#166](https://github.com/SuperElastix/SimpleElastix/issues/166). Is that correct? If so, would you guys a tip on how to use ThinPlateSpline?
I'm running a SimpleElastix version I just compiled on Linux Mint. 

Thank you!

**Comment by kaspermarstal** [comment]
Yes, it should work. You can see that it is enabled here https://github.com/SuperElastix/SimpleElastix/blob/master/SuperBuild/External_Elastix.cmake#L101. Do you use the SuperBuild to build SimpleElastix? Or do you build your own version of elastix?

**Comment by mary-alegro** [comment]
Hi Kasper,

Yes, I compiled the SuperBuild, following the instructions in: https://simpleelastix.readthedocs.io/GettingStarted.html#compiling-on-linux
I also checked the cmake file and indeed SplineKernelTransform is enabled. One thing that I forgot to mention, though, is that both images are 2D. Do you think that would be a problem? By the way, is there code above correct or have I forgotten to set some parameter?

Thanks!

**Comment by kaspermarstal** [comment]
The parameter file looks fine. What happens if you write the parameter map to disk (sitk.WriteParameterFile) and give it to the command line version of elastix? Does this work?

**Comment by kaspermarstal** [comment]
Sorry for no reply. Feel free to reopen if this is still an issue.

**Comment by KakaVlasic** [comment]
Same problem. Have you already solved?
