### ISSUE TITLE
Does SimpleElastix support PET-CT deformable registration?

### ISSUE THREAD

**Issue by glhfgg1024** [SuperElastix/SimpleElastix#172]
Hi all, thanks a lot for this great tool!

I have a this kind of data. For each case/patient, there are the following images:

    1. CT 
    2. PET

    3. CT for segmentation
    4. DICOM-RT segmentation based on 3

It seems 1,2,3 have different voxel spacing (thus they have different number of slices). Does SimpleElastix support this kind of registration? After registration, it is expected all the images have the same spacing. Thanks a lot! Any comments are greatly appreciated!

**Comment by kaspermarstal** [comment]
Hi @glhfgg1024, SimpleElastix supports different image spacing, yes. The final spacing will be determined by the fixed image since the moving image is transformed to the fixed image space. So, if you use the same fixed image for all registrations, all output images will have the same spacing.

**Comment by glhfgg1024** [comment]
Hi @kaspermarstal , thanks a lot for your kind reply and suggestions! 

https://discourse.slicer.org/t/does-slicer-support-this-kind-of-pet-ct-registration/2354/3

Thanks to Elastix and Slicer, I'm trying the SlicerElastix.

**Comment by MSC19950601** [comment]
@glhfgg1024 您好，请问最后使用SlicerElastix或simpleElastix能够实现PET/CT的配准吗？
