### ISSUE TITLE
Error while trying to use SimpleElastix

### ISSUE THREAD

**Issue by nunoloucao** [SuperElastix/SimpleElastix#173]
Hi,

I've just installed and build the library following the installation procedures, but i'm getting the following error when doing a "import SimpleITK as sitk":

import SimpleITK as sitk
Traceback (most recent call last):
  File "/anaconda3/envs/RegistrationPython36/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-macosx-10.7-x86_64.egg/SimpleITK/SimpleITK.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/anaconda3/envs/RegistrationPython36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/anaconda3/envs/RegistrationPython36/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-macosx-10.7-x86_64.egg/SimpleITK/_SimpleITK.cpython-36m-darwin.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /anaconda3/envs/RegistrationPython36/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-macosx-10.7-x86_64.egg/SimpleITK/_SimpleITK.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda3/envs/RegistrationPython36/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-macosx-10.7-x86_64.egg/SimpleITK/_SimpleITK.cpython-36m-darwin.so
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/RegistrationPython36/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-macosx-10.7-x86_64.egg/SimpleITK/__init__.py", line 1, in <module>
    from .SimpleITK import *
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/RegistrationPython36/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-macosx-10.7-x86_64.egg/SimpleITK/SimpleITK.py", line 17, in <module>
    _SimpleITK = swig_import_helper()
  File "/anaconda3/envs/RegistrationPython36/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-macosx-10.7-x86_64.egg/SimpleITK/SimpleITK.py", line 16, in swig_import_helper
    return importlib.import_module('_SimpleITK')
  File "/anaconda3/envs/RegistrationPython36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_SimpleITK'

Can you help me out?

Best, 
Nuno

**Comment by soupault** [comment]
I'm having the same error, although, the errorlog is different:
```
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import SimpleITK
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in module_from_spec(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in create_module(self, spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: /usr/local/lib/python3.6/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/_SimpleITK.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyInstance_Type

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-16932c3140a0> in <module>()
----> 1 import SimpleITK

/usr/local/lib/python3.6/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/__init__.py in <module>()
----> 1 from .SimpleITK import *

/usr/local/lib/python3.6/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py in <module>()
     15         except ImportError:
     16             return importlib.import_module('_SimpleITK')
---> 17     _SimpleITK = swig_import_helper()
     18     del swig_import_helper
     19 elif _swig_python_version_info >= (2, 6, 0):

/usr/local/lib/python3.6/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py in swig_import_helper()
     14             return importlib.import_module(mname)
     15         except ImportError:
---> 16             return importlib.import_module('_SimpleITK')
     17     _SimpleITK = swig_import_helper()
     18     del swig_import_helper

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ModuleNotFoundError: No module named '_SimpleITK'
```

**Comment by kaspermarstal** [comment]
It looks like python cannot find the lib file. How are you installing? Are you generating the wheel and installing via pip? Or?

**Comment by soupault** [comment]
@kaspermarstal I'm following exactly the installation guide from this page - https://simpleelastix.readthedocs.io/GettingStarted.html#compiling-on-linux, and using `sudo python setup.py install` to install the Python package (FYI, `pip install -e .` doesn't really work in this case).
I'm on Ubuntu 18.04 and Python 3.6, if it matters.

I'll try to reproduce this in a 16.04 docker container on Monday. Then we can try to debug further, if you are interested.

**Comment by NHPatterson** [comment]
You may want to verify that you are linking the build against python 3.6 and not python 2.7 which is the default python in ubuntu terminal when using ```sudo```. Try running ```sudo python``` by itself and looking at what version of python is loaded in the terminal. You can fix the default python in your path so ```sudo python``` loads python 3.6, or go to the ```sudo python3.6binary ...```.

**Comment by soupault** [comment]
@NHPatterson yes, I know. for that build I made the required modifications to the makefiles before building the library.

Actually, when I tried to build SimpleElastix with the default makefiles (which are meant to be linked to Py2.7), I didn't even get a `${BUILD_DIRECTORY}/SimpleITK-build/Wrapping/Python/Packaging` directory after the compilation. Never investigated this further, though...

**Comment by NHPatterson** [comment]
Sorry maybe I wasn't clear. You may be building against Python 3.6 with Cmake, but when running ```sudo python setup.py install``` at the terminal it may be running the setup.py with python 2.7 (natively installed python version in ubuntu 16.04 at least) rather than the python you'd prefer.  This is why just testing ```sudo python``` in the terminal will load the python prompt as well as the version. I had a similar problem.

**Comment by soupault** [comment]
Sorry, I'm pretty sure that's not the case. I've tried both `python setup.py install` inside my Py3 venv, and `sudo python3 setup.py install` system-wide.

**Comment by soupault** [comment]
Ok, I've managed to get SimpleElastix working by prioritizing Python 3 on a system level before configuring the build, i.e.:
```
# update-alternatives --install /usr/bin/python python /usr/bin/python2 1
# update-alternatives --install /usr/bin/python python /usr/bin/python3 2

$ cmake ../SimpleElastix/SuperBuild
...
```
Sorry for the noise.

**Comment by kaspermarstal** [comment]
No problem! Happy coding!

**Comment by zwep** [comment]
> Ok, I've managed to get SimpleElastix working by prioritizing Python 3 on a system level before configuring the build, i.e.:
> 
> ```
> # update-alternatives --install /usr/bin/python python /usr/bin/python2 1
> # update-alternatives --install /usr/bin/python python /usr/bin/python3 2
> 
> $ cmake ../SimpleElastix/SuperBuild
> ...
> ```
> 
> Sorry for the noise.

How is this prioritising python3 above python..? If I read this correctly, then you set python3 as a second option and python2 as a first..?

**Comment by soupault** [comment]
@zwep it is confusing. I don't remember precisely what I did, but the snippet looks correct: according to https://linux.die.net/man/8/update-alternatives:
```
Higher priorities take precendence if no alternative is manually selected.
```

**Comment by zwep** [comment]
Aah, of course. I double checked the `--help` info from the command.. And this is what it said

```<priority> is an integer; options with higher numbers have higher priority in
  automatic mode.```
