### ISSUE TITLE
Point Based Registration

### ISSUE THREAD

**Issue by DimitriosGk** [SuperElastix/SimpleElastix#174]
Hello,

I am using smple elastix wrapper for Python. Everything works perfect but i have a question on point based registration. Is there any way that we can have 2 point sets (taken by 2 images), calculate the transform between them and then apply the transform on the moving image?
The function explained in the point pased registration chapter,  is not exactly straightforward. In other words, assuming that we have two index sets (obtained by the fixed and moving image) that correlate with an affine transform. How can we fnd this trasform and then apply it on our moving image in Elastix (I already have an implemented manual way, and one using cv2).

Thank you in advance for your answer,
D.

**Comment by kaspermarstal** [comment]
You can look at the code in #176 for inspiration. Once we get that resolved perhaps you can use the code in there.
