### ISSUE TITLE
no pycharm intelisense hints

### ISSUE THREAD

**Issue by adizhol** [SuperElastix/SimpleElastix#177]
Hi,
Thanks for developing this project!

I compiled and installed using Windows10 SuperBuild as described in the docs.
I can import SimpleITK successfully, but Pycharm does not show any hints for methods etc, although the python console does.
Any idea what's wrong?

Thanks

**Comment by kaspermarstal** [comment]
I have no idea, sorry, this is most likely a PyCharm or configuration issue.
