### ISSUE TITLE
helloworld  came out blank result 

### ISSUE THREAD

**Issue by cswin** [SuperElastix/SimpleElastix#178]
why is my result white blank?   
import SimpleITK as sitk
resultImage = sitk.Elastix(sitk.ReadImage("fixedImage.tif"),
                           sitk.ReadImage("movingImage.tif"),
                           "translation")
sitk.WriteImage(resultImage, 'result_image.tif')

Thank you very much

**Comment by NHPatterson** [comment]
Internally images for registration are cast as 32-bit float and returned as such after registration by SimpleElastix. You can work with this by casting the image back to it's original pixel type using SimpleITK. 

Below is an example where we use two 8-bit unsigned integer images and cast the result output from 32-bit float to 8-bit unsigned and write the image to tif and it works as it should. You could also try using .mha or .nii to save the resulting float image as these are medical image formats with a lot more flexibility for different precisions. 
### Load moving image
```
import SimpleITK as sitk

moving = sitk.ReadImage("test_image1.tif")
moving.GetPixelIDTypeAsString() #'8-bit unsigned integer'
```

Console:
```
'8-bit unsigned integer'
```
### Load fixed image
```
fixed = sitk.ReadImage("test_image2.tif")
fixed.GetPixelIDTypeAsString() 
```
Console:
```
'8-bit unsigned integer'
```
### Register Images & see resultImage pixel type
```
#register using default
resultImage = sitk.Elastix(moving, fixed, "translation")
resultImage.GetPixelIDTypeAsString()
```
Console:
```
'32-bit float'
```
### Cast back to original data type & write
```
resultImage = sitk.Cast(resultImage, sitk.sitkUInt8) #cast back to 8-bit unsigned int
sitk.WriteImage(resultImage, 'result_image_recast.tif') #correct image
```

[Here is an excellent intro on accessing all the important info on the SimpleITK.Image()](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/01_Image_Basics.html)

**Comment by cswin** [comment]
Thank you so much. It works great!!
