### ISSUE TITLE
Does SimpleElastix support Super large size ( such as 12032x18176) images registration?

### ISSUE THREAD

**Issue by cswin** [SuperElastix/SimpleElastix#179]
I am using the following code to do this. but the result shows only part of the image can be registered. 

Note: the fixed image is RGB one and the moving image is ycbcr one
So I convert them to grayscale before registration. 

import SimpleITK as sitk
resultImage = sitk.Elastix(sitk.ReadImage("fixed.tif"),
                           sitk.ReadImage("moving.tif"),
                           "translation")
resultImage = sitk.Cast(resultImage, sitk.sitkUInt8)   
sitk.WriteImage(resultImage, 'result.tif')

I have shared super-images,  code, my own result in the below link.   
https://drive.google.com/drive/folders/1o5AMXvQ8-eA0SpPeaAK4yNEf_ycCsbzf?usp=sharing

Do I have to resize them to a smaller size before registration?

Thank you very much.

**Comment by kaspermarstal** [comment]
Yes, the only limit is the amount of memory in your computer. However, the result image is your moving image transformed to the fixed image domain. So if you fixed image has a smaller field of view than your moving image, your moving image will be cropped. In other words, only the part your moving image that overlap with the fixed image is included in your result image. 

To warp the whole image, you can edit the size of the domain in the transform parameter map to match your moving image, and pass your moving image and the transform parameter map to sitk.Transformix().

**Comment by cswin** [comment]
@kaspermarstal  thank you.   I resized the moving image to the same size as the fixed one.  it works now. 

@NHPatterson   I have tried the parameters setting you said, but the result is not a good match. 
Is this caused by the super-size?   but I don't wanna lost image resolution by resizing them to a smaller size.  Is there any way to improve my result?   Thank you. 

I attach the result here: https://drive.google.com/file/d/1STDG4QwvsBa2XsqsyPcg6UgzxnkqGHU-/view?usp=sharing

Note:  in fact, the pixel-to-pixel distance is 0.35, so I did not set it to be 0.5 as you said. 


**my code**: 
try:
            # read images and prepare the translation parameters
            fixedImage = sitk.ReadImage(self.fixedImagePath+fixedImage)
            movingImage = sitk.ReadImage(self.movingImagePath+movingImage)

            # set pixel-to-pixel distance to 0.5 (microns/pixel)
            # movingImage.SetSpacing((1, 1))
            # # if fixed is different...
            # fixedImage.SetSpacing((1, 1))

            parameterMap = sitk.GetDefaultParameterMap('translation')
            parameterMap["FixedImageDimension"] = ["2"]
            parameterMap["MovingImageDimension"] = ["2"]
            parameterMap["WriteResultImage"] = ["true"]
            parameterMap["ResultImageFormat"] = ["tif"]
            parameterMap['NumberOfResolutions'] = ['20']
            parameterMap['MaximumNumberOfIterations'] = ['200']
            parameterMap['MaximumStepLength'] = ['100']
            parameterMap['NumberOfSpatialSamples'] = ['16384']

            # run registrition
            elastixImageFilter = sitk.ElastixImageFilter()
            elastixImageFilter.SetFixedImage(fixedImage)
            elastixImageFilter.SetMovingImage(movingImage)
            elastixImageFilter.SetParameterMap(parameterMap)
            elastixImageFilter.Execute()

            # get result
            resultImage = elastixImageFilter.GetResultImage()
            transformParameterMap = elastixImageFilter.GetTransformParameterMap()
            # return registerred image and transformParameterMap
            return resultImage, transformParameterMap
        except Exception as e:
            print "error: " + str(e)

Thank you very much.

**Comment by cswin** [comment]
I think the unperfect match is due to the different scale between fixed and moving images.  if we wanna a good result, the two objects in two images should have the same size, right?  Thank you very much.

**Comment by cswin** [comment]
@kaspermarstal  you are right.  I cannot resize the moving images. This will change the object shape and in turn, result in bad matching.

**Comment by kaspermarstal** [comment]
Sure. Could you post your transform parameter map that needs to be edited, the output of `print(fixedImage)`, and the output of `print(movingImage)?

**Comment by cswin** [comment]
**ParameterMap 0:** 
  (AutomaticParameterEstimation "true")
  (CheckNumberOfSamples "true")
  (DefaultPixelValue 0.000000)
  (FinalBSplineInterpolationOrder 3.000000)
  (FixedImageDimension 2.000000)
  (FixedImagePyramid "FixedSmoothingImagePyramid")
  (ImageSampler "RandomCoordinate")
  (Interpolator "LinearInterpolator")
  (MaximumNumberOfIterations 60.000000)
  (MaximumNumberOfSamplingAttempts 8.000000)
  (MaximumStepLength 50.000000)
  (Metric "AdvancedMattesMutualInformation")
  (MovingImageDimension 2.000000)
  (MovingImagePyramid "MovingSmoothingImagePyramid")
  (NewSamplesEveryIteration "true")
  (NumberOfResolutions 5.000000)
  (NumberOfSamplesForExactGradient 4096.000000)
  (NumberOfSpatialSamples 8192.000000)
  (Optimizer "AdaptiveStochasticGradientDescent")
  (Registration "MultiResolutionRegistration")
  (ResampleInterpolator "FinalBSplineInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "tif")
  (Size 18176.000000)
  (Transform "TranslationTransform")
  (UseDirectionCosines "true")
  (WriteIterationInfo "false")
  (WriteResultImage "true")
**Image (0x2208730)** **fixedImage**
  RTTI typeinfo:   itk::Image<unsigned char, 2u>
  Reference Count: 2
  Modified Time: 928
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 916
  UpdateMTime: 927
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [12032, 18176]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [12032, 18176]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [12032, 18176]
  Spacing: [0.352778, 0.352778]
  Origin: [0, 0]
  Direction: 
1 0
0 1

  IndexToPointMatrix: 
0.352778 0
0 0.352778

  PointToIndexMatrix: 
2.83465 0
0 2.83465

  Inverse Direction: 
1 0
0 1

  PixelContainer: 
    ImportImageContainer (0x20f4f90)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned char>
      Reference Count: 1
      Modified Time: 924
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7f2fd1773010
      Container manages memory: true
      Size: 218693632
      Capacity: 218693632

**Image (0x21caa30) movingImage**
  RTTI typeinfo:   itk::Image<unsigned char, 2u>
  Reference Count: 3
  Modified Time: 1087
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1075
  UpdateMTime: 1086
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [18176, 29631]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [18176, 29631]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [18176, 29631]
  Spacing: [0.352778, 0.352778]
  Origin: [0, 0]
  Direction: 
1 0
0 1

  IndexToPointMatrix: 
0.352778 0
0 0.352778

  PointToIndexMatrix: 
2.83465 0
0 2.83465

  Inverse Direction: 
1 0
0 1

  PixelContainer: 
    ImportImageContainer (0x21c2b40)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned char>
      Reference Count: 1
      Modified Time: 1083
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7f2f931e0010
      Container manages memory: true
      Size: 538573056
      Capacity: 538573056

**Comment by cswin** [comment]
BTW,  the fixed image (12032 × 18176) is smaller than moving image(18176 × 29631).     
Can two different sizes of images be registered? 
[two direction result comparison](https://drive.google.com/file/d/1luyy7NvhCcwEHfuxL6hMf5kmTIAI9P4h/view?usp=sharing)

**Comment by kaspermarstal** [comment]
@cswin you should post your _transform_ parameter map (the map generated by elastix that you pass to transformix, not the one you pass to elastix) :)

**Comment by kaspermarstal** [comment]
Two different sizes can be registered, yes, that is not a problem.

**Comment by cswin** [comment]
**sitk.PrintParameterMap(transformParams)**
ParameterMap 0: 
  (CompressResultImage "false")
  (DefaultPixelValue 0.000000)
  (Direction 1.000000 0.000000 0.000000 1.000000)
  (FinalBSplineInterpolationOrder 3.000000)
  (FixedImageDimension 2.000000)
  (FixedInternalImagePixelType "float")
  (HowToCombineTransforms "Compose")
  (Index 0.000000 0.000000)
  (InitialTransformParametersFileName "NoInitialTransform")
  (MovingImageDimension 2.000000)
  (MovingInternalImagePixelType "float")
  (NumberOfParameters 2.000000)
  (Origin 0.000000 0.000000)
  (ResampleInterpolator "FinalBSplineInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "tif")
  (ResultImagePixelType "float")
  (Size 12032.000000 18176.000000)
  (Spacing 0.352778 0.352778)
  (Transform "TranslationTransform")
  (TransformParameters 75.561699 51.607601)
  (UseDirectionCosines "true")
    **print(fixedImage)**
Image (0x1fbb360)
  RTTI typeinfo:   itk::Image<unsigned char, 2u>
  Reference Count: 2
  Modified Time: 928
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 916
  UpdateMTime: 927
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [12032, 18176]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [12032, 18176]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [12032, 18176]
  Spacing: [0.352778, 0.352778]
  Origin: [0, 0]
  Direction: 
1 0
0 1

  IndexToPointMatrix: 
0.352778 0
0 0.352778

  PointToIndexMatrix: 
2.83465 0
0 2.83465

  Inverse Direction: 
1 0
0 1

  PixelContainer: 
    ImportImageContainer (0x1d54280)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned char>
      Reference Count: 1
      Modified Time: 924
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7f220c949010
      Container manages memory: true
      Size: 218693632
      Capacity: 218693632
**print(movingImage)**
Image (0x1ec8eb0)
  RTTI typeinfo:   itk::Image<unsigned char, 2u>
  Reference Count: 3
  Modified Time: 1087
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1075
  UpdateMTime: 1086
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [18176, 29631]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [18176, 29631]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [18176, 29631]
  Spacing: [0.352778, 0.352778]
  Origin: [0, 0]
  Direction: 
1 0
0 1

  IndexToPointMatrix: 
0.352778 0
0 0.352778

  PointToIndexMatrix: 
2.83465 0
0 2.83465

  Inverse Direction: 
1 0
0 1

  PixelContainer: 
    ImportImageContainer (0x14e9c10)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned char>
      Reference Count: 1
      Modified Time: 1083
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7f21ce3b6010
      Container manages memory: true
      Size: 538573056
      Capacity: 538573056

**Comment by kaspermarstal** [comment]
Feel free to reopen if this is still an issue.
