### ISSUE TITLE
Does SimpleElastix support RGB images registration?

### ISSUE THREAD

**Issue by cswin** [SuperElastix/SimpleElastix#180]
one new question for me:  How could I do RGB images registration?  Is there code samples in our document?

Thank you very much.

**Comment by kaspermarstal** [comment]
You can supply multiple fixed and moving images (one image for every color channel to elastix. 

Sorry for the late reply. Feel free to reopen if this is still an issue.

**Comment by markbuckup** [comment]
I am doing a Bspline registration for color images. Is it possible to perform the registration for one channel and apply it to the other two color channels so I don't need to repeat the algorithm 3 times? Then I can build the RGB image from the three transformed channels.

Or is there a way to output a color image by supplying all three channels to elastix?
