### ISSUE TITLE
Cannot get DeformationField output

### ISSUE THREAD

**Issue by YangCHY0** [SuperElastix/SimpleElastix#181]
When I run 
```
    transformix = sitk.TransformixImageFilter()
    transformix.SetOutputDirectory(ELASTIX_TEMP.name)
    transformix.ComputeDeformationFieldOn()
    transformix.SetTransformParameterMap(elastix.GetTransformParameterMap())
    transformix.Execute()
```
I did not get deformationField output in ELASTIX_TEMP directory. But as the console log showed 

> ELASTIX version: 4.801
Command line options from ElastixBase:
-out      C:\Users\chaoyu\AppData\Local\Temp\2\tmp4djma_3b/
-threads  unspecified, so all available threads are used
-def      all
-jac      unspecified, so no det(dT/dx) computed
-jacmat   unspecified, so no dT/dx computed
Calling all ReadFromFile()'s ...
  Calling all ReadFromFile()'s took 0.000099 s
Transforming points ...
  The transform is evaluated on all points. The result is a deformation field.
  Transforming points done, it took 0.03s
Compute determinant of spatial Jacobian ...
  The command-line option "-jac" is not used, so no det(dT/dx) computed.
  Computing determinant of spatial Jacobian done, it took 0.00s
Compute spatial Jacobian (full matrix) ...
  The command-line option "-jacmat" is not used, so no dT/dx computed.
  Computing spatial Jacobian done, it took 0.00s

the DeformationField is computed. And spatial Jacobian can output normally. These code works properly on older version.
My SimpleElastix version is SimpleITK-1.0.1rc1.dev350+g1af5d.

**Comment by silviaalmeida** [comment]
Hi @YangCHY0! I have the same problem. On what older version does this code works properly? Thank you!

**Comment by poyobe** [comment]
Hello,

I also would like to get the deformation field and I have the same issue, I tried it on OSX and on Ubuntu using the latest SimpleElastix version (9dfa8cb) compiled with the super build.

The following code : 

`##----------------
SimpleElastix = sitk.ElastixImageFilter()
SimpleElastix.SetParameterMap(sitk.GetDefaultParameterMap("bspline"))
SimpleElastix.SetFixedImage(sitk.GetImageFromArray(refImage))
SimpleElastix.SetMovingImage(sitk.GetImageFromArray(currImage))
SimpleElastix.Execute()
##----------------`

is writing a "TransformParameters.0.txt" file and nothing else, but this code : 

`##----------------
transformix = sitk.TransformixImageFilter()
transformix.SetOutputDirectory(outPutPath)

transformix.ComputeDeformationFieldOn()
transformix.ComputeDeterminantOfSpatialJacobianOn()
transformix.ComputeSpatialJacobianOn()

transformix.SetTransformParameterMap(transformParameterMap)
transformix.SetMovingImage(sitk.GetImageFromArray(currImage))

transformix.Execute()
##----------------`

isn't writing anything. 

And it seems there is no transformix.GetDeformationField() function to get it in a variable and save it ourselves ? Or did I miss something? 

Thx to anyone who can help :)

**Comment by poyobe** [comment]
I tried some other things without success:

1. Trying to set the resulting transformation of elastix into an sitk.Transform() and then use a sitk.TransformToDisplacementField() to get the field.

testTransform = sitk.Transform(2, sitk.sitkComposite)
affineTransform = sitk.AffineTransform(2)
affineTransform.SetParameters(transformParameterMap()[0]["TransformParameters"])
testTransform.AddTransform(affineTransform)

transformToDF = sitk.TransformToDisplacementField(testTransform)

Something is not used correctly I usualy get this error: 
TypeError: in method 'Transform_SetParameters', argument 2 of type 'std::vector< double,std::allocator< double > > const &'


2. Combine this registration example (https://tinyurl.com/y79ro3ch) with an ElastixImageFilter or TransformixImageFilter, by creating an empty def field and then trying to pass it to the filter so it can take the shape of the resulting transformation.

displacementField = sitk.Image(fixedImage.GetSize(), sitk.sitkVectorFloat64)
displacementField.CopyInformation(fixedImage)
displacementTx = sitk.DisplacementFieldTransform(displacementField)
displacementTx.SetSmoothingGaussianOnUpdate(varianceForUpdateField=0.0, varianceForTotalField=1.5)

myTransformTest.SetInitialTransform(displacementTx, inPlace=True)

myTransformTest.Execute()
field = displacementTx.GetDisplacementField()

But it’s only working for an sitk.ImageRegistrationMethod() and not with ElastixImageFilter or TransformixImageFilter.

3. Using the command line tool and the demo script "2B_SuperElastix_itkv4_MSD.sh"
I get this error related to the displacement field output : 
[debug] Finding component for 'ResultDisplacementField': 0 component(s) satisfies 'AcceptingInterface' {NameOfInterface: ItkDisplacementFieldInterface} and previous criteria.
[error] ResultDisplacementFielddoes not provide any connections with the given criteria.
[critical] Executing ... Error
[critical] ResultDisplacementFielddoes not provide any connections with the given criteria.

**Comment by zmani** [comment]
Hy, I have the same problem: the deformationfield.nii is not written. Someone fixed it?
Thank you!

**Comment by darrylbobo** [comment]
@poyobe @YangCHY0 

did you find the way to write the displacement fields? 
Would appreciate if if you can share.

**Comment by poyobe** [comment]
No I didn't sorry. Maybe I'll try again later.

**Comment by kaspermarstal** [comment]
Hi, try out develop which should now have support for getting the deformation field directly from memory. Let me know how it goes, and if successful, we can merge to master.

**Comment by kaspermarstal** [comment]
There is an example here on how to get the deformation field: https://github.com/SuperElastix/SimpleElastix/blob/develop/Testing/Unit/Python/sitkTransformixImageFilterTest.py

**Comment by darrylbobo** [comment]
@kaspermarstal 
Hi, thanks for the reply. However, there is no this function.
Should I rebuilt the simpleElastix?

AttributeError: 'TransformixImageFilter' object has no attribute 'GetDeformationField'


> Here is an example on how to get the deformation field: https://github.com/SuperElastix/SimpleElastix/blob/develop/Testing/Unit/Python/sitkTransformixImageFilterTest.py

**Comment by SouthAmericaB** [comment]
Hi @kaspermarstal!

I install simpleElastix a few days ago and although I have tried to do what you indicate in https://github.com/SuperElastix/SimpleElastix/blob/develop/Testing/Unit/Python/sitkTransformixImageFilterTest.py  I don't obtain some deformationField value.

The code run without errors but it doesn't generate deformationField result. 

My code:
```
`transformixImageFilter = sitk.TransformixImageFilter()

transformixImageFilter.ComputeDeformationFieldOn()
transformixImageFilter.ComputeDeformationFieldOn()
transformixImageFilter.ComputeDeterminantOfSpatialJacobianOn()
transformixImageFilter.ComputeSpatialJacobianOn()

transformixImageFilter.SetTransformParameterMap(elastixImageFilter.GetTransformParameterMap())
transformixImageFilter.SetMovingImage(sitk.ReadImage(variable))

transformixImageFilter.SetOutputDirectory("C:/Users/Usuario/Desktop/CNN/SimpleElastix")

transformixImageFilter.Execute()
deformationField = transformixImageFilter.GetDeformationField()`
```
"fullSpatialJacobian.nii" and "spatialJacobian.nii" is generated correctly. 

Could you help me?
Thank you very much in advance!

**Comment by ctorti** [comment]
Hi @SouthAmericaB ,

I can see that no one has provided a response to your question.  I am having the same issue - no output for the deformation field, although I do get output for the spatial Jacobian and its determinant.

I'm wondering if you managed to figure out how to resolve the issue and would be happy to share?

**Comment by XXZhou25** [comment]
I have exactly the same problem.

**Comment by SouthAmericaB** [comment]
> Hi @SouthAmericaB ,
> 
> I can see that no one has provided a response to your question. I am having the same issue - no output for the deformation field, although I do get output for the spatial Jacobian and its determinant.
> 
> I'm wondering if you managed to figure out how to resolve the issue and would be happy to share?

Hi!
Sorry, but I still haven't found a solution.
If I achieve it, I will share with you! :)

**Comment by RivettiLuciano** [comment]
I had some problems to get the displacement field of a registration. The registration work well but when I use **TransformixImageFilter** to get the displacement field I get an error. Below the code Im using:
``
CT = sitk.ReadImage('',sitk.sitkFloat32)
CBCT = sitk.ReadImage('',sitk.sitkFloat32)

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.LogToFileOff()
elastixImageFilter.LogToConsoleOff()
elastixImageFilter.SetOutputDirectory(ElastixOutputFile)
elastixImageFilter.SetFixedImage(CBCT)
parametermap = elastixImageFilter.ReadParameterFile(Parameter_File)
elastixImageFilter.SetParameterMap(parametermap)
elastixImageFilter.SetMovingImage(CT)
elastixImageFilter.Execute()

transformixImageFilter = sitk.TransformixImageFilter()
transformixImageFilter.SetTransformParameterMap(elastixImageFilter.GetTransformParameterMap())
transformixImageFilter.ComputeDeformationFieldOn()
transformixImageFilter.Execute()

Error:

RuntimeError: Exception thrown in SimpleITK TransformixImageFilter_Execute: /mnt/Luco/Modules/Elastix/SimpleElastix/Code/Elastix/src/sitkTransformixImageFilterImpl.cxx:116:
sitk::ERROR: 
itk::ExceptionObject (0x564e638b7190)
Location: "unknown" 
File: /mnt/Luco/Modules/Elastix/Build/ITK-prefix/include/ITK-5.1/itkImageBase.hxx
Line: 184
Description: itk::ERROR: Image(0x564e63aa0300): Bad direction, determinant is 0. Direction is 1 0
0 0

**Comment by pangyuteng** [comment]
For those stumbling upon this post, you need to specify the logic (last line in below code snippet) to save the deformation field.

`
# assuming `movingImage` is set, and `elastixImageFilter.Execute()` completed.

logdir = './'
deformation_file = 'deformation.nii.gz'
transformixImageFilter = sitk.TransformixImageFilter()
transformixImageFilter.SetMovingImage(movingImage)
transformixImageFilter.SetTransformParameterMap(elastixImageFilter.GetTransformParameterMap())
transformixImageFilter.ComputeDeformationFieldOn()
#transformix.ComputeDeterminantOfSpatialJacobianOn()
#transformix.ComputeSpatialJacobianOn()
transformixImageFilter.LogToConsoleOn()
transformixImageFilter.SetOutputDirectory(logdir)
transformixImageFilter.Execute()
sitk.WriteImage(transformixImageFilter.GetDeformationField(),deformation_file)
`
