### ISSUE TITLE
How to convert TransformParmaterMap to SimpleITK.Transform?

### ISSUE THREAD

**Issue by adizhol** [SuperElastix/SimpleElastix#182]
How to convert TransformParmaterMap to a SimpleITK Transform?

For exmple:
```
            eltx.SetParameterMap(rigid)
            eltx.Execute()
            tform = eltx.GetTransformParameterMap()
            euler_transofmr = sitk.Euler2DTransform(tform) # how to make this work?
```

**Comment by zmani** [comment]
Hi @adizhol ,
did you find a solution?

**Comment by zmani** [comment]
Hi @kaspermarstal,
thank you for the answer.
I need to perform this conversion because transformix does not write the deformationField.nii file (the issue is described here: https://github.com/SuperElastix/SimpleElastix/issues/181 ), so I would like to use the function  TransformToDisplacementFieldFilter( ) to calculate the deformation field.
Do you have any suggestions regarding the calculation of the deformation field with transformix?

**Comment by kaspermarstal** [comment]
Hi, try out develop which should now have support for getting the deformation field directly from memory. Let me know how it goes, and if successful, we can merge to master.

**Comment by kaspermarstal** [comment]
There is an example here on how to get the deformation field: https://github.com/SuperElastix/SimpleElastix/blob/develop/Testing/Unit/Python/sitkTransformixImageFilterTest.py

**Comment by zmani** [comment]
Hey @kaspermarstal,
it works properly. Thanks a lot for your help

**Comment by sedghi** [comment]
I'm trying to register two 3D volume images with the following code

```
elastixImageFilter = sitk.ElastixImageFilter() 
elastixImageFilter.SetFixedImage(fixed_image) 
elastixImageFilter.SetMovingImage(moving_image) 
elastixImageFilter.Execute() 
```

It runs successfully, but for generating the deformation field I used the code you put earlier and I'm getting this error


```
transformixImageFilter = sitk.TransformixImageFilter()
transformixImageFilter.SetTransformParameterMap(elastixImageFilter.GetTransformParameterMap())
transformixImageFilter.ComputeDeformationFieldOn()
transformixImageFilter.Execute()
deformationField = transformixImageFilter.GetDeformationField()


--------------- Exception ---------------

itk::ExceptionObject (0x556adfc967a0)
Location: "unknown" 
File: /home/user/github/build/Elastix/Common/Transforms/itkAdvancedBSplineDeformableTransformBase.hxx
Line: 302
Description: itk::ERROR: AdvancedBSplineDeformableTransform(0x556adfc626f0): Mismatched between parameters size 39366 and region size 729

-----------------------------------------

```

**Comment by ctorti** [comment]
Hi @zmani and others,

Would anyone be willing to shed some light on how they managed to get the deformation field?

I have followed the link:

https://github.com/SuperElastix/SimpleElastix/blob/develop/Testing/Unit/Python/sitkTransformixImageFilterTest.py

but I continue to not get the deformation field output.  I can get spatialJacobian.nii and fullSpatialJacobian.nii however.

It looks like my deformation field has the Image class (should I have expected this?:

> <SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'std::vector< itk::simple::Image >::value_type *' at 0x0000023919F8DE40> >

(Note I'm using Anaconda Jupyter).

Any advice would be much appreciated.

**Comment by zmani** [comment]
Hi @ctorti,
I also don't get the deformation field automatically, so I save it  manually:

    deformationField = transformix.GetDeformationField()
    sitk.WriteImage(deformationField,filepath)

I hope this works for you as well 👍

**Comment by ctorti** [comment]
Hi @zmani ,

Thanks very much.  I have tried that suggestion but it killed my kernel (Anaconda Jupyter).

I also tried:

`DeformationFieldNda = sitk.GetArrayFromImage(DeformationField) `

but that also killed the kernel. 

Do you mind me asking what IDE are you using?

**Comment by zmani** [comment]
Hi @ctorti ,

I use PyCharm.
