### ISSUE TITLE
transformixImageFilter gives no bspline transformation

### ISSUE THREAD

**Issue by JLegrand147** [SuperElastix/SimpleElastix#183]
Hi, 

I'm trying to perform a non-rigid transformation between two CT scans (healthy_1_V.nii and  healthy_2_V.nii). After registration and inspection of the obtained images with elastix, everything is fine, I obtain a correct non-rigid registration. 

However, when I use transformix to apply the transformation to my set of points, I just obtain my input set of points shifted from a few millimeters. 

When I impose manually the transformation by e.g.: 
elastixImageFilter.SetParameterMap(sitk.GetDefaultParameterMap("bspline") )
I notice in the outputpoints.txt file that my Deformation matrices are full of zero. 

Can you help me out ?  Here is the code I run: 

fixedImage = sitk.ReadImage("healthy_1_V.nii")
movingImage = sitk.ReadImage("healthy_2_V.nii")

# Compute the transformation
elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(fixedImage)
elastixImageFilter.SetMovingImage(movingImage)
elastixImageFilter.Execute()
sitk.WriteImage(elastixImageFilter.GetResultImage(), "OutputImage_Non_rigid_registration.nii")

# Apply transformation
transformixImageFilter = sitk.TransformixImageFilter()
transformixImageFilter.SetTransformParameterMap(elastixImageFilter.GetTransformParameterMap())
transformixImageFilter.SetFixedPointSetFileName("Healthy_1_L.asc")
transformixImageFilter.SetMovingImage(movingImage)
transformixImageFilter.Execute()

**Comment by kaspermarstal** [comment]
I don't think transformix recognizes the `.asc` extension. Feel free to reopen if this is still an issue.
