### ISSUE TITLE
Translation Along 1 Axis

### ISSUE THREAD

**Issue by ok37** [SuperElastix/SimpleElastix#185]
Hi 

I was wondering is there was a way to modify the parameter map to restrict translation to 1 or 2 axes for registering 3D images?

**Comment by PertuyF** [comment]
Register lines or slices instead of volumes?
Or edit the TransformParameters to set undesired axes to 0.

What would be your application?

**Comment by ok37** [comment]
So I have 2 multimodal 3D images which should be well aligned in xy but slightly displaced along z. These images happen to be very large so running the native 3D translational registration takes an extremely long time. My thought is I can execute faster if I limit the translation to only the z axis?

**Comment by PertuyF** [comment]
If you're 100% certain `xy` alignment is OK you could just extract two corresponding `xz` or `yz` slices  and register those. Then get the `z` translation value from the transform parameters and apply this to the 3D volume.

Else, extract corresponding subvolumes from each images and register those, then extract the translation parameters and apply those to the full volumes.
What's the size of these images exactly?

**Comment by ok37** [comment]
$

**Comment by ok37** [comment]
Great ideas thanks - I'm leaning towards the second option. Currently each image is about 10-15GB but have about 30 of these in the dataset
