### ISSUE TITLE
Groupwise registration result image

### ISSUE THREAD

**Issue by the4thchild** [SuperElastix/SimpleElastix#186]
I've been using SimpleElastix for the past year and have had really nice registrations with it. I've been trying groupwise registration and get it to run without error, but the resulting image appears to be almost the same as whatever the first image in the vector was. Is there a different method to extract a composite group image (if it's supposed to return that)? Or the individual images that have been aligned?

Here is the gist of what I am doing:
```
    img_vector = sitk.VectorOfImage()
    for img in imgs):
        img_vector.push_back(img)
    img_combined = sitk.JoinSeries(img_vector)
    
    elastix_img_filter = sitk.ElastixImageFilter()
    elastix_img_filter.SetFixedImage(img_combined)
    elastix_img_filter.SetMovingImage(img_combined)
    param_map = sitk.GetDefaultParameterMap("groupwise")
    elastix_img_filter.SetParameterMap(param_map)
    elastix_img_filter.Execute()
    transformed_img = elastix_img_filter.GetResultImage()
    sitk.Show(transformed_img)
```

Thanks for your help!

**Comment by the4thchild** [comment]
I found that I could extract individual groupwise-registered images using an ExtractImageFilter with the added 4D support that [you mentioned](https://github.com/SuperElastix/SimpleElastix/issues/19#issuecomment-191295064):

```
    extract_filter = sitk.ExtractImageFilter()
    size = list(transformed_img.GetSize())
    size[3] = 0 # set t to 0 to collapse this dimension
    extract_filter.SetSize(size)
    extract_filter.SetIndex([0, 0, 0, i]) # x, y, z, t
    img = extract_filter.Execute(transformed_img)
```

I also tried fusing the images together into a composite image using a ComposeImageFilter, but I only see the first image, which I presume is from this image obscuring the others. Is there a way to blend the images together?

**Comment by PertuyF** [comment]
Once you get the registered Vector, you should compute the mean over the last dimension (individuals from your population). This is easily done converting the vector to a numpy array and using `numpy.mean()`, but probably also using `SimpleITK` too.

**Comment by the4thchild** [comment]
Thanks for pointing this out! I combined the groupwise registered images along these lines to get a fused image:

```
transformed_img = elastix_img_filter.GetResultImage()
extract_filter = sitk.ExtractImageFilter()
size = list(transformed_img.GetSize())
size[3] = 0 # set t to 0 to collapse this dimension
extract_filter.SetSize(size)
imgs = []
for i in range(len(imgs_orig)):
    extract_filter.SetIndex([0, 0, 0, i]) # x, y, z, t
    img = extract_filter.Execute(transformed_img)
    imgs.append(sitk.GetArrayFromImage(img))
img_mean = np.mean(imgs, axis=0)
img_fused = sitk.GetImageFromArray(img_mean)
```

So is ComposeImageFilter for simply overlaying (rather than fusing) images? Do you typically recommend normalizing the amount of the sample in each image (eg the length of neck included from each subject) to get a better mean image, or does groupwise registration ideally account for this? Some of my subjects' heads are stretched into longer necks.

If the ExtractImageFilter step is the correct way to access each image, I could submit a PR to expand on the Extract comment [in the docs](https://simpleelastix.readthedocs.io/GroupwiseRegistration.html) if it would be helpful.

**Comment by kaspermarstal** [comment]
Thanks for the PR!
