### ISSUE TITLE
Using binary mask for registration

### ISSUE THREAD

**Issue by andreaurru** [SuperElastix/SimpleElastix#189]
Hey, 
I am using SimpleElastix with python, and I am trying to use a binary mask to improve registration.
After setting ErodeMask to true in the parameter map, how do I select the actual mask to be used for the images?

Thanks

**Comment by doctorblaze** [comment]
Hey,

The sitk.elastixImageFilter() module is the one doing all the heavy lifting for you. You feed it everything (the parameters you want to use, the fixed and moving images, .... and the masks!). In Python, type

`import SimpleITK as sitk
help(sitk.ElastixImageFilter)`

Bam! You have a list of ALL the arguments you can feed into elastixImageFilter!!! 

Here's some template code for you:

`import simpleITK as sitk
fixedImage = sitk.ReadImage('/Users/Superman/Documents/workdir/template.nii')
fixedMask = sitk.ReadImage('/Users/Superman/Documents/workdir/templatemask.nii)
movingImage = sitk.ReadImage('/Users/Superman/Documents/workdir/tobetransformed.nii)
movingMask = sitk.ReadImage('/Users/Superman/Documents/workdir/tobetransformedmask.nii)
parameterMap = sitk.GetDefaultParameterMap('affine')
elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(fixedImage)
elastixImageFilter.SetFixedMask(fixedMask)
elastixImageFilter.SetMovingImage(movingImage)
elastixImageFilter.SetMovingMask(movingMask)
elastixImageFilter.SetParameterMap(parameterMap)
elastixImageFilter.Execute()
newImg = elastixImageFilter.GetResultImage()
sitk.WriteImage(newImg,'/Users/Superman/Desktop/workdir/tobetransformed_affinetransformed.nii')`


note: always try Python help() function, there is often very useful information to be found... Remember, most software has documentation within the software code _somewhere_ (this is standard practice by software developers). Whether or not it is easy to find or to understand is often a different problem however...

**Comment by MSC19950601** [comment]
Come with problem!
Description: itk::ERROR: ImageGridSampler(0x55a92eb4df60): ERROR: the bounding box of the mask lies entirely out of the InputImageRegion!
