### ISSUE TITLE
Registering 3d images?

### ISSUE THREAD

**Issue by rhacking** [SuperElastix/SimpleElastix#191]
I'm trying to register 3d volumes (about 2048x2048x2048 in size, but for now I'm trying simpler cases). However, even [this](https://gist.github.com/rhacking/9d5f9ca8fafcdd53d114b3fcf7aa02cb) test case seems to fail (you can't see the plots unfortunately, but you can see from the last value that the registration is way off). It seems that in the registered image, the sphere is located at (17, 32, 26). Am I using SimpleElastix incorrectly?

**Comment by kaspermarstal** [comment]
Feel free to reopen if this is still an issue.
