### ISSUE TITLE
Is there any way of knowing all the possible errors?

### ISSUE THREAD

**Issue by jeekiii** [SuperElastix/SimpleElastix#192]
I would like to know what kind of error I can expect to encounter when running a registration. Is there any way to know all the possible errors I could get or do I have to go though the code?

I actually have the same question for the parameters. I know there exists http://elastix.isi.uu.nl/doxygen/parameter.html but it's not completely standardized and therefore not practical to parse with a script.

Thanks for the good work.

**Comment by kaspermarstal** [comment]
For all practical purposes, I am afraid not. Many, many things can go wrong before, during and after the registration procedure. The only thing you can do is try out a lot of different things until you end up with something that works. Like the deep learning people :)

**Comment by jeekiii** [comment]
Thanks a lot, it's what I expected.
