### ISSUE TITLE
Apply two downsampled images on full size images

### ISSUE THREAD

**Issue by abenchaaben** [SuperElastix/SimpleElastix#200]
Hi,

I performed a registartion on two downsampled that worked. I tried then to apply the transformation on the full size images. So i edit the transformation file and change the resolution to the full size images and i let the same spacing (equal to 1). Because it was the same for both downsampled and full size. But the transformation does not work for me as it worked for the downsampeld.

Any help please.

**Comment by kaspermarstal** [comment]
Sorry for the no reply. Feel free to reopen if this is still an issue.
