### ISSUE TITLE
fail to display RGB images

### ISSUE THREAD

**Issue by pranitapradhan91** [SuperElastix/SimpleElastix#201]
Hello all,

I am new to SimpleITK and have been trying to do some basic code. Currently, I am just trying to read a RGB image and display it. My code is as follows:
import SimpleITK as sitk
image = sitk.ReadImage('......./composite.jpg')
# show image
sitk.Show(image, title="Tissue")

I get an error RuntimeError: Exception thrown in SimpleITK Show: C:\Users\dashboard\Miniconda3\conda-bld\simpleitk_1521730316398\work\Code\IO\src\sitkShow.cxx:495:
sitk::ERROR: No appropriate executable found.

I am using Python 3.6.5 with anaconda. I am able to import sitk. Also when I run 'print(image.GetDepth())', I get output as 0 whereas it should be 3. Anything wrong here? Any help is appreciated.

**Comment by poyobe** [comment]
This is a SimpleITK issue, not related to SimpleElastix.

It's seems your image isn't read correctly.
Have you tried showing your image with another lib to confirm a reading issue?
For example like this
`
import matplotlib.pyplot as plt

arrayImage = sitk.GetArrayFromImage(image)

plt.figure
plt.imshow(arrayImage)
plt.show()
`

**Comment by pranitapradhan91** [comment]
Thank you for the reply. The error is resolved in this post [https://github.com/SimpleITK/SimpleITK/issues/485#issuecomment-395116013](url)

**Comment by kaspermarstal** [comment]
Glad the error is fixed!
