### ISSUE TITLE
Erosion on result image after affine registration

### ISSUE THREAD

**Issue by Schwarzarbeiter** [SuperElastix/SimpleElastix#203]
Hello,

I am currently developing a medical image search software in Java, which should include a registration module. I decided to give SimpleElastix a go but ran into the a problem. The result image seems to be eroded (white lines around object edges) and I have no clue why.

[Source image](https://i.imgur.com/OY1i7ue.jpg)
[Target image](https://i.imgur.com/eGdUsKi.jpg)
[Result image](https://i.imgur.com/bMj8yvG.jpg)

This are the steps i have done:
- I have two Java BufferedImage which I convert into itk.simple.Image (reading and writing the pixel values). This is how the pixels are written:

```
VectorUInt32 vector = new VectorUInt32();
//i and j are pixel coordinates
vector.add(i);
vector.add(j);
//images are unsigned. Since Java does not support unsigned data, 0xFF is "added" 
image.setPixelAsUInt16(vector, databuffer[i*width+j] & 0xFF);
```

- I register the two images using the following code:

```
VectorOfParameterMap parameterMapVector = new VectorOfParameterMap();
ParameterMap rigidMap = elastixImageFilter.getDefaultParameterMap("affine");
parameterMapVector.add(rigidMap);
elastixImageFilter.setParameterMap(parameterMapVector);
elastixImageFilter.execute();
Image result = elastixImageFilter.getResultImage();
```

- convert the itk.simple.Image to a Java BufferedImage. Here is a small code extract showing the basic logic:

``` 
VectorUInt32 vector = new VectorUInt32();
//i and j are the pixel coordinates
vector.add(i);
vector.add(j);
intPictureValues[t] = (int)itkImage.getPixelAsFloat(vector);
...
bytePictureValues[i] = (byte)intPictureValues[i];
DataBuffer dataBuffer = new DataBufferByte(bytePictureValues, 1);
```

**Comment by kaspermarstal** [comment]
Hi. Sorry for the late reply. Feel free to reopen if this is still an issue.
