### ISSUE TITLE
Corresponding intensity values change slightly

### ISSUE THREAD

**Issue by the4thchild** [SuperElastix/SimpleElastix#205]
I've been using SimpleElastix to register a label map whose intensity values correspond to specific label IDs. I noticed that the post-registration label map had slight differences in intensity values, leading to ID misidentification. To test, I applied an ``ElastixImageFilter`` with a ``translation`` parameter map where I set the ``MaximumNumberOfIterations`` to 0 so that the images pre- and post-registration remain in the same place (presumably; they appear in the exact same location by eye at least). Here is a sample of intensity values from matching regions.

Moving image before applying ``ElastixImageFilter``:
```
[[16247 16247 16247 16247 16247 16247 15666 15666 15666 15666]
 [16247 16247 16247 16247 16247 15666 15666 15666 15666 15666]
 [16247 16247 15666 15666 15666 15666 15666 15666 15666 15666]
 [16247 15666 15666 15666 15666 15666 15666 15666 15666 15666]
 [15666 15666 15666 15666 15666 15666 15666 15666 15666 15666]
 [15666 15666 15666 15666 15666 15666 15666 15666 15666 15666]
 [15666 15666 15666 15666 15666 15666 15666 15666 15666 15666]
 [15666 15666 15666 15666 15666 15666 15666 15666 15666 15666]
 [15666 15666 15666 15666 15666 15666 15666 15666 15666 15666]
 [15666 15666 15666 15666 15666 15666 15666 15666 15666 15666]]
```

Matching region from moving image after ``ElastixImageFilter`` (max iterations set to 0 to keep image in same place).  Many values are +/- 1 from corresponding values in the first image, but some have even more dramatic changes (eg 16247 to 16266.697), despite no shift in position:
```
[[16248.045  16248.608  16266.697  16268.647  16259.968  16211.529
  15647.567  15628.026  15679.322  15665.479 ]
 [16242.599  16261.436  16196.309  16195.086  16212.977  15647.442
  15675.424  15681.916  15665.939  15671.435 ]
 [16258.968  16208.517  15645.454  15630.551  15633.604  15682.731
  15683.197  15677.474  15669.397  15678.332 ]
 [16208.853  15644.345  15674.223  15680.427  15677.37   15665.564
  15667.296  15673.566  15673.844  15668.203 ]
 [15647.76   15673.664  15669.154  15667.582  15655.61   15668.333
  15668.263  15667.902  15667.224  15673.841 ]
 [15678.716  15667.827  15679.471  15680.242  15669.816  15665.079
  15665.0625 15668.02   15665.394  15665.364 ]
 [15666.089  15679.556  15667.293  15666.808  15664.868  15665.448
  15665.552  15665.143  15666.185  15666.254 ]
 [15668.782  15664.211  15665.434  15665.596  15665.635  15665.413
  15666.164  15666.2705 15666.129  15665.771 ]
 [15665.112  15665.768  15665.45   15666.126  15666.149  15665.991
  15666.121  15666.109  15665.948  15665.87  ]
 [15665.532  15666.102  15666.194  15665.94   15665.936  15665.94
  15665.94   15665.946  15665.954  15665.949 ]]

```

After casting back to original pixel ID (uint32), again showing changes that appear to be more than from simple rounding:
```
[[16248 16248 16266 16268 16259 16211 15647 15628 15679 15665]
 [16242 16261 16196 16195 16212 15647 15675 15681 15665 15671]
 [16258 16208 15645 15630 15633 15682 15683 15677 15669 15678]
 [16208 15644 15674 15680 15677 15665 15667 15673 15673 15668]
 [15647 15673 15669 15667 15655 15668 15668 15667 15667 15673]
 [15678 15667 15679 15680 15669 15665 15665 15668 15665 15665]
 [15666 15679 15667 15666 15664 15665 15665 15665 15666 15666]
 [15668 15664 15665 15665 15665 15665 15666 15666 15666 15665]
 [15665 15665 15665 15666 15666 15665 15666 15666 15665 15665]
 [15665 15666 15666 15665 15665 15665 15665 15665 15665 15665]]
```

Is there a way to preserve the exact intensity values for corresponding pixels during registration? I've tried casting the original image to float32 or applying the registration through ``TransformixImageFilter`` but get the same result.

Thanks for your help!

**Comment by NHPatterson** [comment]
This is likely related to the resampling/interpolation step. If you are using label data, you should set the ```FinalBSplineInterpolationOrder``` to 0 in your transformation parameter file. This issue has been discussed [here](https://groups.google.com/d/msg/elastix-imageregistration/hHXbSHdgzHs/fgFxnhGDAwAJ) and the link also includes the relevant discussion in the elastix manual.

**Comment by the4thchild** [comment]
Thanks @NHPatterson , that's extremely helpful! Does this mean that one should run the initial registration with ``FinalBSplineInterpolationOrder`` of 3, then change it to 0 in the transformation parameter file only? I would assume that this would maximize the registration quality for the non-label images, sacrificing the quality just for the labels (meaning the labels might not line up perfectly)?

When combining multiple parameter maps, should ``FinalBSplineInterpolationOrder`` be set to 0 for each parameter map? The labels appear to be fine even when I applied the setting to the final map alone, but not sure if this is generally the case.

Thanks!

**Comment by kaspermarstal** [comment]
Feel free to open if this is still an issue.

**Comment by ablot** [comment]
I want to register an atlas than consists of a 3D volume of labelled pixels (int32) and I seem to have the same issue even after changing `FinalBSplineInterpolationOrder` to 0. I also tried to cast the output back to the input pixel type but that didn't solve the issue. I tried to change `MovingInternalImagePixelType` or `ResultImagePixelType` but they don't seem to be used by `sitk.Transformix`.  I must be doing something fundamentally wrong somewhere but I have no idea.

Here is an example of what I run:

```
import SimpleITK as sitk
import numpy as np

atlas = sitk.ReadImage(path2atlas)
pixelID = atlas.GetPixelIDValue()
atlas_values = np.unique(sitk.GetArrayFromImage(atlas))

print('The atlas has %d regions' % len(atlas_values))

transmap = sitk.ParameterMap()
transmap['Origin'] = ("0", "0", "0")
transmap['Size'] = ("456", "320", "528")
transmap['Spacing'] = ("1", "1", "1")
transmap['Direction'] = ('1', '0', '0', '0', '1', '0', '0', '0', '1')
transmap['Resampler'] = 'DefaultResampler',
transmap['ResampleInterpolator'] = 'FinalBSplineInterpolator',
transmap['FinalBSplineInterpolationOrder'] = '0',
transmap['HowToCombineTransforms'] = "Compose",
transmap['Index'] = ("0", "0", "0")
transmap['InitialTransformParametersFileName'] = "NoInitialTransform",
transmap['Transform'] = "TranslationTransform",
transmap['NumberOfParameters'] = '3',
transmap['TransformParameters'] = ["1.2", "1", "1"]
transmap['UseDirectionCosines'] = "true",
transmap['UseBinaryFormatForTransformationParameters'] = 'false',

output = sitk.Transformix(atlas, transmap, True)

output_values = np.unique(sitk.GetArrayFromImage(output))
print('The output has %d regions' % len(output_values))
new_values = [v for v in output_values if not (v in atlas_values)]
print('and %d new regions' % len(new_values))

recast = sitk.Cast(output, pixelID)
recast_values = np.unique(sitk.GetArrayFromImage(recast))
print('The recast version of output has %d regions' % len(recast_values))
new_values = [v for v in recast_values if not(v in atlas_values)]
print('and %d new regions' % len(new_values))
print('Done')
```

And the output that I get
```
The atlas has 672 regions

Installing all components.
InstallingComponents was successful.
ELASTIX version: 4.900
Command line options from ElastixBase:
-out      ./
-threads  unspecified, so all available threads are used
-def      unspecified, so no input points transformed
-jac      unspecified, so no det(dT/dx) computed
-jacmat   unspecified, so no dT/dx computed
Reading input image ...
  Reading input image took 0.000012 s
Calling all ReadFromFile()'s ...
  Calling all ReadFromFile()'s took 0.000130 s
Transforming points ...
  The command-line option "-def" is not used, so no points are transformed
  Transforming points done, it took 0.00s
Compute determinant of spatial Jacobian ...
  The command-line option "-jac" is not used, so no det(dT/dx) computed.
  Computing determinant of spatial Jacobian done, it took 0.00s
Compute spatial Jacobian (full matrix) ...
  The command-line option "-jacmat" is not used, so no dT/dx computed.
  Computing spatial Jacobian done, it took 0.00s
Resampling image and writing to disk ...
  Resampling took 6.51s

The output has 619 regions
and 21 new regions
The recast version of output has 619 regions
and 21 new regions
Done
```

I don't want to have any pixel values that was not in the input (`atlas`) image. Is there a way to do that?

**Comment by ablot** [comment]
FYI, the issue was not in the interpolation but in the casting. My `int32` atlas labels got transformed when they were converted to single and then back to int32. "Translating" manually the labels in floating point numbers fixed the issue.

**Comment by yoda-vid** [comment]
Hi @ablot , I've also recently seen an issue where labels with very large values appear to undergo some rounding when applying Transformix. For example:

```
126651678 becomes 126651680
126651001 becomes 126651000
126651000 remains 126651000
16919 remains 16919
```

Is this similar to the issue you found? Did you manually translate labels by casting them to floating point beforehand, or manually translating large values to smaller values? I tried casting to `sitk.sitkFloat32` or `sitk.sitkFloat64` but got the same rounding errors.

**Comment by ablot** [comment]
That sounds similar. The labels that I was using were sparse, so I avoided the issue by just changing the labels to be continuous manually before applying the transform. They could then be casted into singles and then back into int without being shifted.

**Comment by yoda-vid** [comment]
Thanks, @ablot , that makes a lot of sense. My labels are sparse as well, and I will map them to their `np.unique` index values before the transformation to avoid the high values. Thanks for your suggestion.
