### ISSUE TITLE
Combining several ANTS + Elastix transforms using SimpleITK.

### ISSUE THREAD

**Issue by mary-alegro** [SuperElastix/SimpleElastix#208]
Hi all,

I'm in a situation where I have several ANTS affine transforms and Elastix bSpline transforms sequentially applied to an image (i.e. ANTS affine 1 + Elastix bSpline 1 + ANTS affine 2 + Elastix bSpline 2 + ... ANTS affine N + Elastix bSpline N) and I'm trying to combine them in order to avoid excessive interpolation errors. Is there a way to that? Maybe using SimpleITK or ITK directly? While was easy to load ANTS .mat file in SimpleITK, I tried to load the Elastix deformation field as suggested here [https://github.com/SuperElastix/SimpleElastix/issues/134](url) without success. 

If I try:
`tx = sitk.ReadTransform('deformationField.nii')`

I get the error:

>  Traceback (most recent call last):
>   File "/Users/.../bin/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-25-7415e91d9125>", line 1, in <module>
>     tx = sitk.ReadTransform('deformationField.nii')
>   File "/Users/.../bin/anaconda2/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 5148, in ReadTransform
>     return _SimpleITK.ReadTransform(filename)
> RuntimeError: Exception thrown in SimpleITK ReadTransform: /Users/dashboard/miniconda3/conda-bld/simpleitk_1521730858267/work/build/ITK/Modules/IO/TransformBase/include/itkTransformFileReader.hxx:130:
> itk::ERROR: TransformFileReaderTemplate(0x7f9d435e8550): Could not create Transform IO object for reading file deformationField.nii
>   Tried to create one of the following:
>     HDF5TransformIOTemplate
>     HDF5TransformIOTemplate
>     MatlabTransformIOTemplate
>     MatlabTransformIOTemplate
>     TxtTransformIOTemplate
>     TxtTransformIOTemplate
>   You probably failed to set a file suffix, or
>     set the suffix to an unsupported type.

Would anybody have suggestions? 

Thank you!

**Comment by mary-alegro** [comment]
Answering my own question as this may be useful to someone else:

`affine_tf = sitk.ReadTransform('affine2600GenericAffine.mat') #ANTS affine
elastix_def_img = sitk.ReadImage('deformationField.nii',sitk.sitkVectorFloat64) 
displacement_field_transform = sitk.DisplacementFieldTransform(elastix_def_img)
composite_transform = sitk.Transform(affine_tf)
composite_transform.AddTransform(displacement_field_transform)
ref_img = sitk.ReadImage('reference.nii',sitk.sitkFloat64)
mov_img = sitk.ReadImage('movable.nii',sitk.sitkFloat64)
reg_img = sitk.Resample(mov_img, ref_img, composite_transform, sitk.sitkLinear, 0.0, mov_img.GetPixelIDValue())
sitk.WriteImage(reg_img,'test_compose.nii')`

**Comment by kaspermarstal** [comment]
Thanks for posing your solution!

**Comment by romangrothausmann** [comment]
Also thanks from me. So this does not use SimpleElastix but only needs SimpleITK!? It's the first time I see an application of specifying a transform to the itkResampleFilter. The optional use of a transform seems to be the reason why it cannot stream (so far).
