### ISSUE TITLE
ISO C++1z does not allow  dynamic exception specifications

### ISSUE THREAD

**Issue by joellliu** [SuperElastix/SimpleElastix#211]
When I try to build SimpleElastix on my machine, I got the following errors:

`[ 45%] Building CXX object Modules/Numerics/Polynomials/src/CMakeFiles/ITKPolynomials.dir/itkMultivariateLegendrePolynomial.cxx.o
In file included from /data1/SimpleElastix/build/ITK/Modules/Numerics/Polynomials/src/itkMultivariateLegendrePolynomial.cxx:18:0:
/data1/SimpleElastix/build/ITK/Modules/Numerics/Polynomials/include/itkMultivariateLegendrePolynomial.h:145:3: error: ISO C++1z does not allow dynamic exception specifications
   throw ( CoefficientVectorSizeMismatch );
   ^~~~~
/data1/SimpleElastix/build/ITK/Modules/Numerics/Polynomials/include/itkMultivariateLegendrePolynomial.h:148:3: error: ISO C++1z does not allow dynamic exception specifications
   throw ( CoefficientVectorSizeMismatch );
   ^~~~~
/data1/SimpleElastix/build/ITK/Modules/Numerics/Polynomials/src/itkMultivariateLegendrePolynomial.cxx:126:1: error: ISO C++1z does not allow dynamic exception specifications
 throw ( MultivariateLegendrePolynomial::CoefficientVectorSizeMismatch )
 ^~~~~
/data1/SimpleElastix/build/ITK/Modules/Numerics/Polynomials/src/itkMultivariateLegendrePolynomial.cxx:149:1: error: ISO C++1z does not allow dynamic exception specifications
 throw ( MultivariateLegendrePolynomial::CoefficientVectorSizeMismatch )
 ^~~~~
`
I understand that it is because C++1z removed dynamic exception specifications,  but is that any way I can fix this? Is going back to C++14 the only way to solve it?
Thanks a lot.

**Comment by kaspermarstal** [comment]
I have not seen this error before. If you have a temp solution (e.g. by using C++14) you can use that until I get SimpleITK v1.1 merged.

**Comment by joellliu** [comment]
thank you for your reply @kaspermarstal

**Comment by kaspermarstal** [comment]
SimpleITK v1.1 has been merged.

**Comment by pollackscience** [comment]
I'm also getting this error:
`In file included from /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Common/CostFunctions/              itkAdvancedImageToImageMetric.h:28:0,
                  from /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Common/                            itkMultiResolutionImageRegistrationMethod2.h:43,
                  from /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Core/ComponentBaseClasses/         elxRegistrationBase.h:25,
                  from /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Core/Kernel/elxElastixTemplate.h:  30,
                  from /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Core/Install/elxIncludes.h:39,
                  from /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Components/FixedImagePyramids/     FixedRecursivePyramid/elxFixedRecursivePyramid.h:21,
                  from /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Components/FixedImagePyramids/     FixedRecursivePyramid/elxFixedRecursivePyramid.cxx:19:
 /pghbio/dbmi/batmanlab/bpollack/build/Elastix/Common/CostFunctions/itkLimiterFunctionBase.h:102:35:    error: ISO C++1z does not allow dynamic exception specifications
    virtual void Initialize( void ) throw ( ExceptionObject ) {}`

gcc v 8.2.0, cmake v 3.11.4, SimpleElastix head (1.2.0)

**Comment by kaspermarstal** [comment]
This was addressed in elastix in the following commit: https://github.com/SuperElastix/elastix/commit/33b41a2747cbd83db0aca9f18032d49a93395f8a. 

Will update elastix.

**Comment by pollackscience** [comment]
Can confirm, switching to updated version of elastix fixed error and allowed me to build.  Thanks!
