### ISSUE TITLE
Using masks

### ISSUE THREAD

**Issue by doctorblaze** [SuperElastix/SimpleElastix#213]
Hi,

I am trying to use a mask (on both fixed and moving images) to help guide the registration process. I've created individual masks for my images using matlab. These masks are of exactly the same dimension/voxel size and have exactly the same origin as their associated image. They are saved in UINT8 bits as required by elastix. However, I am getting a strange error

`Description: itk::ERROR: ImageGridSampler(0x7fcf10786ce0): ERROR: the bounding box of the mask lies entirely out of the InputImageRegion!`

I've browsed online and it isn't entirely clear why I am getting this error given that my mask and image are exactly the same size and have the same origin... I am currently using ['ImageSampler'] = ['RandomCoordinate'] (and have also tried 'Full' which isn't installed with SimpleElastix? and 'Grid' with no luck...)

Not sure how to fix this... Any help would be greatly appreciated

**Comment by doctorblaze** [comment]
I was also getting this related error
`Description: itk::ERROR: NormalizedMutualInformationMetric(0x7fbd9c8a7600): Too many samples map outside moving image buffer: 0 / 392`

Problem solved: when using the masks, I should have made sure I was only using it on the fixed image, and not both the fixed and moving image. Using it on both means that a voxel sampled within the fixed image mask **has** to be "sent/paired/mapped" to a voxel **strictly within** the moving image mask/volume... Which (obviously) causes quite a few problems... 

It helps to draw out the image volume (e.g. as a rectangular cuboid for example 128 x 128 x 95) and mentally picture how the fixed image is translated/rotated/sheared/stretched and bent onto the moving image. 

Using a mask on both fixed and moving image makes the optimisation problem way to restrictive and will crash the software. In essence, doing this double masking amounts to forcing voxels sampled in the fixed image to map directly into the volume defined by the moving image mask (and nowhere else)... Without the possibility for the algorithms to map voxels slightly outside of this moving image volume during early stages of the optimisation, there is no way to find a good solution because it is impossible for the algorithms to work properly (the iterative process is too restricted). 

note: If your (fixed) mask is way smaller than your image volume and you are using Adaptive Stochastic Gradient Descent with a random sampler, don't forget to change the ['ImageSampler'] parameter to ['RandomSparseMask'] in your parameter map.

`['ImageSampler'] = ['RandomSparseMask']`

**Comment by MSC19950601** [comment]
How to made sure only using fixed mask on the fixed image?

**Comment by MSC19950601** [comment]
Description: itk::ERROR: ImageGridSampler(0x55a92eb4df60): ERROR: the bounding box of the mask lies entirely out of the InputImageRegion!
