### ISSUE TITLE
Issue with the installation of the whl data

### ISSUE THREAD

**Issue by samieti02** [SuperElastix/SimpleElastix#215]
Hello dear sir ,

I have a issue with the installation of the wheel data and it is really annoying. I saw on the internet page that there are 2 methods on how to install; either with the binary files or with the wheel data. Since I want to use it with python , I ran the command pip install whl_data. And the installation with pip was successful
But now when I want to use the very simple codeline for registration of the documentation, i get that error

'return_load(spec)'
'ImportError: DLL load failed: The specified module was not found'

This the code that i used
`import SimpleITK as sitk`
`resultImage = sitk.Elastix(sitk.ReadImage("fixedImage.nii"), sitk.ReadImage("movingImage.nii"))`

. Could you plese help me to solve that error?

Thanks!

**Comment by kaspermarstal** [comment]
Sorry for the no reply. Feel free to reopen if this is still an issue.
