### ISSUE TITLE
Error using ConjugatedGradient as Optimizer

### ISSUE THREAD

**Issue by Bakedbee** [SuperElastix/SimpleElastix#216]
Hi, 

I am trying to use some different optimizers with the Python wrapper of SimpleElastix. At execution the programm exits with the following error message: 

> Installing all components.
> InstallingComponents was successful.
> 
> Error:
> ConjugateGradient(index 2) - This component is not installed!
> ERROR: error occurred while creating Optimizer 0.
> 
> itk::ExceptionObject (000000C0FFBE8A18)
> Location: "unknown"
> File: c:\data\build\simpleelastix\elastix\core\kernel\elxelastixmain.cxx
> Line: 819
> Description: itk::ERROR: ElastixMain(0000021202CB71E0): The following component could not be created: ConjugateGradient
> 
> 
> ERROR:
> One or more components could not be created.

For me the "AdaptiveStochasticGradientDescent" and also the "QuasiNewtonLBFGS" performs without problems.  I used SuperBuild for building. 
So my question is if I made a mistake during the setup of SimpleElastix or maybe someone has a solution for this particular problem.
Thanks!

**Comment by kaspermarstal** [comment]
Go info the ‘Elastix-build’ directory in the buold folder, type ‘ccmake .’, find the ‘ConjugateGradient’ component, enable it, and rebuild + reinstall. 

This should be enabled by default. Stay tuned.

**Comment by zwep** [comment]
Hi kaspermarstal,

I ran into the same issue today.. also used to Superbuild to install everything. Might be that I misread something, but is it still not installed by default?
