### ISSUE TITLE
Only support Python 2.7? 

### ISSUE THREAD

**Issue by AlanStark** [SuperElastix/SimpleElastix#217]
I run python setup.py install, but cannot install on my default Python 3.6. Does it only support python 2?

**Comment by PertuyF** [comment]
Which version of `python` did you used during the build?

**Comment by SWKoreaBME** [comment]
Hello I had same problem and I just solved it

Solution for this is omitting sudo,

``python setup.py install``

may solve your problem

**Comment by AlanStark** [comment]
My default Python is 3.6.5. I tried using sudo, but still does not work.

**Comment by the4thchild** [comment]
I've installed it with Python 3.6.6 in an Anaconda environment. Did you compile it with Python 2.7 or 3.6?

**Comment by markemus** [comment]
Build instructions for Python3: https://github.com/rcasero/pysto/wiki/Build-and-install-SimpleElastix-for-python-3.x

I also had to move `SimpleElastix/build/SimpleITK-build/Wrapping/Python/_SimpleITK.so` to `SimpleElastix/build/SimpleITK-build/Wrapping/Python/Packaging/` (one level down).

**Comment by kaspermarstal** [comment]
See above commit for resolution!
