### ISSUE TITLE
C# problem with SimpleITKExamples

### ISSUE THREAD

**Issue by Draspiratio** [SuperElastix/SimpleElastix#218]
I did everything like it was in Documentation -> Getting Started. But SimpleITKExamples did not build (Error - MSB6006). I try to use Elastix library but it did not work. Can i get code which work to check mine? I work 
 with Visual Studio 2017 (c#).

**Comment by kaspermarstal** [comment]
In the build directory, if you run `ccmake .`, is the `BUILD_EXAMPLES` CMake variable set to ON?
