### ISSUE TITLE
Result of non-rigid registration / ImportError: No module named '_SimpleITK' /

### ISSUE THREAD

**Issue by samieti02** [SuperElastix/SimpleElastix#221]
Hello dear Sir or Madam, 
thanks for the tool. I would like to mention a few points and a few questions I would have too.
I spent a lot of time getting the tool up and running. After that, I tried a non-rigid registration and those are the results I had. 

- Could you please explain why you have this light box around the skull (Image Regof12)?
![2pt](https://user-images.githubusercontent.com/23456648/43400501-29ac9efe-940e-11e8-80eb-07ce36c40300.PNG)
![regof2pt](https://user-images.githubusercontent.com/23456648/43400502-29d52e96-940e-11e8-9049-3cd0f914a242.PNG)

- I find that the documentation is not well described. for example you said for linux, we should use 
 `git clone https://github.com/SuperElastix/SimpleElastix`
and for windows
 `git clone https://github.com/kaspermarstal/SimpleElastix`
What is the different between both ? 
I have **Windows 10 64 bit** with **VS 2015**. I installed **anaconda 3** and the latest version of cmake.
I first tried with the second link for windows and always had compile errors, then i tried with the first link, and everything was Ok; i should also mention that i made some changes within cmake and VS2015. The build was successful and i was of course happy.

- Then i tried the first simple code and immediately the next error comes up
` (datapre) C:\Users\me\Datapre>cd c:\Users\me\Datapre && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Users\me\AppData\Local\Continuum\anaconda3\envs\datapre\python.exe c:\Users\me\.vscode\extensions\ms-python.python-2018.6.0\pythonFiles\PythonTools\visualstudio_py_launcher_nodebug.py c:\Users\me\Datapre 58302 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput c:\Users\me\Datapre\datapre.py "
Traceback (most recent call last):  File "c:\Users\me\.vscode\extensions\ms-python.python-2018.6.0\pythonFiles\PythonTools\visualstudio_py_launcher_nodebug.py", line 74, in run
    _vspu.exec_file(file, globals_obj) `
`  File "c:\Users\me\.vscode\extensions\ms-python.python-2018.6.0\pythonFiles\PythonTools\visualstudio_py_util.py", line 119, in exec_file `
`    exec_code(code, file, global_variables) `
`  File "c:\Users\me\.vscode\extensions\ms-python.python-2018.6.0\pythonFiles\PythonTools\visualstudio_py_util.py", line 95, in exec_code `
`    exec(code_obj, global_variables) `
`  File "c:\Users\me\Datapre\datapre.py", line 17, in <module> `
`    import SimpleITK as sitk `
`  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\datapre\lib\site-packages\simpleitk-1.0.1rc1.dev345+g9dfa8-py3.4-win-amd64.egg\SimpleITK\__init__.py", line 1, in <module> `
`    from .SimpleITK import * `
`  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\datapre\lib\site-packages\simpleitk-1.0.1rc1.dev345+g9dfa8-py3.4-win-amd64.egg\SimpleITK\SimpleITK.py", line 17, in <module> `
`    _SimpleITK = swig_import_helper() `
`  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\datapre\lib\site-packages\simpleitk-1.0.1rc1.dev345+g9dfa8-py3.4-win-amd64.egg\SimpleITK\SimpleITK.py", line 16, in swig_import_helper `
`    return importlib.import_module('_SimpleITK') `
`  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\datapre\lib\importlib\__init__.py", line 109, in import_module `
`    return _bootstrap._gcd_import(name[level:], package, level) `
`ImportError: No module named '_SimpleITK' `

It was really annoying, cause i passed a lot of time with the build.
I dowloaded the wheel data from the internet page and installed it,

`Installed c:\users\me\appdata\local\continuum\anaconda3\envs\datapre\lib\site-packages\simpleitk-1.0.1rc1.dev345+g9dfa8-py3.4-win-amd64.egg`
`Processing dependencies for SimpleITK==1.0.1rc1.dev345+g9dfa8`
`Finished processing dependencies for SimpleITK==1.0.1rc1.dev345+g9dfa8`

and everything was ok.
I would say that I was a bit lucky. The documentation also helped, but I'm not completely satisfied.
I would like to know if the process I took to install it, is reasonable?

Thanks and Regards
Sami

**Comment by samieti02** [comment]
Hello dear people,
could i have please a feedback? Why do i get a box around the skull? Which parameter should  I use to optimize the results? The number of iterations didnt help. Which do you have?
Thanks

**Comment by PertuyF** [comment]
It is not a "box", it is the background of your image that does not appear black.

Most likely your `pixeltype` changed during the registration (guessing from `int16`, somewhat standard for medical imaging, to `float32`, the default for `ElastiX` output) which modified the dynamic range of your image, and your viewer does not adjust.
Changing the contrast inside your viewer should make the background appear "black" again.

**Comment by kaspermarstal** [comment]
You are not the first user to come across the "No module" error. I don't know the cause at the moment, but working on a fix.

**Comment by kaspermarstal** [comment]
Run `sudo python Packaging/setup.py install` from the `Wrapping/Python` directory, _not_ `sudo python setup.py install` from the `Wrapping/Python/Packaging` directory

**Comment by martinneumann** [comment]
> Run `sudo python Packaging/setup.py install` from the `Wrapping/Python` directory, _not_ `sudo python setup.py install` from the `Wrapping/Python/Packaging` directory

I receive the error `IOError: [Errno 2] No such file or directory: '/home/mydrive/SimpleElastix/Wrapping/Python/Packaging/setup.py'`, since there is no `setup.py` in that directory but only a file called setupegg.py`. If I use that instead of `setup.py`, the error is the same. What am I doing wrong?
