### ISSUE TITLE
Are there any suggestions about how to get better registration result for brain image?

### ISSUE THREAD

**Issue by ZexinYan** [SuperElastix/SimpleElastix#222]
I use default parameters to register my data, but the result is real poor. Is there anyone who could give me some suggestions about how to get better registration result for brain image? 

One of images looks like that:

![im-0001-0017-0001](https://user-images.githubusercontent.com/21264150/43447750-be4ba69c-94de-11e8-9d0a-4314d933cf3c.jpg)

**Comment by kaspermarstal** [comment]
Which default parameters are you using? What do you mean by "poor"? Is the the images not overlapping? Is your evaluation (Dice Similarity Coefficient, Target Registration Error etc) bad? Can you add (like, pixelwise add using sitk.Add()) the fixed image to the result image and show the result?
