### ISSUE TITLE
Using SimpleElastix for stitching medical volumes with overlap

### ISSUE THREAD

**Issue by malekosh** [SuperElastix/SimpleElastix#223]
Hello All,

I am trying to stitch 2 MRI scans which have a region of overlap by first registering them together using Elastix Image Filter. Then in order to add (stitch) them together I have to align them both on the same plane with the same origin. My question is, how to use the results from the Elastix Image Filter to do the aligning?

Thanks!

**Comment by PertuyF** [comment]
Assuming that the offset of your MRI volumes is not already encoded in the metadata, basically you can:

 1. perform a `translation` registration
 0. get the transform parameters
 0. compute the final volume dimensions (fixed volume dimensions + absolute value of the translation parameters)
 0. create an empty volume with these dimensions
 0. Fill the non-overlaping parts with fixed/moving images, according to the transform parameters
 0. Use a composition of your choice for the overlap (`mean` value should reduce the noise if you registration is good)

Assuming you use the Python binding of `SimpleElastix`, this can all be done pretty easily using `numpy`, or `SimpleITK` directly.
