### ISSUE TITLE
No valid voxels when using a fixed mask

### ISSUE THREAD

**Issue by mauinz** [SuperElastix/SimpleElastix#225]
Hi,

I'm trying to use a fixed mask during registration. I pass the mask in and use the RandomSparseMask image sampler, if I pass mask which consists only of ones then it works fine. Could it be the wrong image sampler is being used?

`Description: itk::ERROR: ComputeJacobianTerms(0000000014035020): No valid voxels (0/1000) found to estimate the AdaptiveStochasticGradientDescent parameters.`

Many thanks,
Matt

**Comment by kaspermarstal** [comment]
Does the mask have the same world info (origin, direction spacing) as your fixed image?

**Comment by mauinz** [comment]
It does yes, I'll try and reproduce the issue with a minimum working example...

**Comment by mauinz** [comment]
Here's a minimum working example, it could be that my data types are wrong? I don't set world information in this example but in the data I do use, I copy over the information so the coords should be fine. I also find that When I set the threshold to 0.0 it works fine, anything higher causes the bug to persist. Thanks in advance!

```python
import argparse

import SimpleITK as sitk
import numpy as np


def main(args):
    image_moving = sitk.GetImageFromArray(np.random.randn(100, 100, 100))
    image_fixed = sitk.GetImageFromArray(np.random.randn(100, 100, 100))
    mask = np.random.uniform(0, 1, 100 ** 3).reshape([100, 100, 100])
    mask = mask > args.threshold
    fixed_mask = sitk.GetImageFromArray(mask.astype(np.uint8))

    elastix = sitk.ElastixImageFilter()

    elastix.SetFixedImage(image_fixed)
    elastix.SetMovingImage(image_moving)
    parameterMap = sitk.GetDefaultParameterMap("rigid")
    parameterMap["Transform"] = ["AffineTransform"]
    parameterMap["ImageSampler"] = ["RandomSparseMask"]

    elastix.SetParameterMap(parameterMap)

    elastix.SetFixedMask(fixed_mask)
    elastix.Execute()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Toy example to test masked image registration SimpleElastixs')

    parser.add_argument('--threshold', type=float, default=0.00)

    args = parser.parse_args()
    print('Using arguments: {}'.format(args))
    main(args)```

**Comment by kaspermarstal** [comment]
Mhm. This is strange. Can you share the images you use?

**Comment by mauinz** [comment]
The code snippet above reproduces the bug with synthetic random images, setting the threshold arg to anything other than zero seems to make the bug occur

**Comment by kaspermarstal** [comment]
Ah, yes sorry. Will have a look.

**Comment by mauinz** [comment]
Hi Kasper, I managed to get this working now. I had to use the following settings for anyone else facing this issue

```
(FixedImagePyramid "FixedSmoothingImagePyramid")
(MovingImagePyramid "MovingSmoothingImagePyramid")
```

Hope this helps! I'll mark the issue as closed

**Comment by MSC19950601** [comment]
However, I get ERROR "Description: itk::ERROR: ImageGridSampler(0x55a92eb4df60): ERROR: the bounding box of the mask lies entirely out of the InputImageRegion!".
