### ISSUE TITLE
How to save the transformationMap for later use?

### ISSUE THREAD

**Issue by LiYingwei** [SuperElastix/SimpleElastix#227]
Hi,

I am trying to save the transformationMap parameter. I tried to do save it by using pickle/dill:

```
transformationMap = elastixImageFilter.GetTransformParameterMap()
pickle.dumps(transformationMap)
```

I will get this error:
TypeError: can't pickle SwigPyObject objects

Also I tried to get all parameters by 

```
for key in transformationMap[0]:
    print(transformationMap[0][key])
    print(dill.dumps(transformationMap[0][key]))
```
And then reconstruct transformationMap, but I don't know how can I reconstruct transformationMap
So I am wondering if there is some other solutions or I made some mistakes.

**Comment by kaspermarstal** [comment]
You can use the 'WriteParameterFile(transformationMap, filename)' to save it to disk and 'ReadParameterFile(filename)' to load it again later. Does this work for you?

**Comment by LiYingwei** [comment]
Thanks a lot for your helping!
When I want to save something like  `sitk.GetDefaultParameterMap("rigid")`, it works by using:
`sitk.WriteParameterFile(sitk.GetDefaultParameterMap("rigid"), '/tmp/param.txt')`
However, when I tried to save transformationMap by:
`sitk.WriteParameterFile(elastixImageFilter.GetTransformParameterMap(), '/tmp/param.txt')`
There will be a type error:

>TypeError: in method 'WriteParameterFile', argument 1 of type 'std::map< std::string,std::vector< std::string,std::allocator< std::string > >,std::less< std::string >,std::allocator< std::pair< std::string const,std::vector< std::string,std::allocator< std::string > > > > > const'

I am wondering  if I made some mistakes. 
Thanks.

**Comment by kaspermarstal** [comment]
GetTransformParameterMap() returns a vector of transform parameter maps. You need to provide them one at a time e.g. `sitk.WriteParameterFile(elastixImageFilter.GetTransformParameterMap()[0], '/tmp/param0.txt'`. This could be made more intuitive or at least throw a more useful error. Thanks for your feedback (and sorry for late reply).

**Comment by farhanone** [comment]
Hi

Thanks for the help.

It worked for me `sitk.WriteParameterFile(elastixImageFilter.GetTransformParameterMap()[0], '/tmp/param0.txt'` Is it possible to write a single composite parameter file for all performed transformations?
And it would be helpful if one can specify the filename (that show up like filename0.txt, filename2.txt OR only single combined ) for the output of `elastixImageFilter.Execute()` ,since it automatically generates the names (e.g  _TransformParameters.0.txt_ and so )
