### ISSUE TITLE
 warnings occurred during the registration via elastix 4.9 

### ISSUE THREAD

**Issue by Wafamah** [SuperElastix/SimpleElastix#228]
### **Hi all, 

 I'm trying to register 2D fixed image to 2D moving image by running CMD.  (Masks were applied to both images). 

There are many warnings occurred during the registration and I wasn't able to figure out why. I tried most of the trouble shooting strategies that are recommended in the manual but they didn't work. 

May you please help me to find out why there are many warnings and how to fix them? (I'm not expert in using elastix. )

Here is the elastix.log content:** 

Installing all components.
InstallingComponents was successful.

ELASTIX version: 4.900
Command line options from ElastixBase:
-f        C:\Users\Wadha\Documents\Elastix_IN\179_1_structurertestim.nii
-m        C:\Users\Wadha\Documents\Elastix_IN\1_179_structurertestim_moving.nii
-fMask    C:\Users\Wadha\Documents\Elastix_IN\179_1_structurertestim_Mask.nii
-mMask    C:\Users\Wadha\Documents\Elastix_IN\1_179_structurertestim_mask.nii
-out      C:\Users\Wadha\Documents\Elastix_OUT\
-p        C:\Users\Wadha\Documents\Elastix_PARS\parameters__Affine_AMSradians_modified_10_0.001.txt
-priority unspecified, so NORMAL process priority
-threads  unspecified, so all available threads are used
Command line options from TransformBase:
-t0       unspecified, so no initial transform used

=============== start of ParameterFile: C:\Users\Wadha\Documents\Elastix_PARS\parameters__Affine_AMSradians_modified_10_0.001.txt ===============
// Example parameter file for rotation registration
// C-style comments: //

// The internal pixel type, used for internal computations
// Leave to float in general. 
// NB: this is not the type of the input images! The pixel 
// type of the input images is automatically read from the 
// images themselves.
// This setting can be changed to "short" to save some memory
// in case of very large 3D images.
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")

// The dimensions of the fixed and moving image
// Up to elastix 4.5 this had to be specified by the user.
// From elastix 4.6, this is not necessary anymore.
//(FixedImageDimension 2)
//(MovingImageDimension 2)

// Specify whether you want to take into account the so-called
// direction cosines of the images. Recommended: true.
// In some cases, the direction cosines of the image are corrupt,
// due to image format conversions for example. In that case, you 
// may want to set this option to "false".
(UseDirectionCosines "true")

// **************** Main Components **************************

// The following components should usually be left as they are:
(Registration "MultiResolutionRegistration")
(Interpolator "BSplineInterpolator")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")

// These may be changed to Fixed/MovingSmoothingImagePyramid.
// See the manual.
(FixedImagePyramid "FixedRecursiveImagePyramid")
(MovingImagePyramid "MovingRecursiveImagePyramid")

// The following components are most important:
// The optimizer AdaptiveStochasticGradientDescent (ASGD) works
// quite ok in general. The Transform and Metric are important
// and need to be chosen careful for each application. See manual.
(Optimizer "AdaptiveStochasticGradientDescent")
(Transform "AffineTransform")
//(Metric "AdvancedMattesMutualInformation")
(Metric "AdvancedMeanSquares_Radians")

// ***************** Transformation **************************

// Scales the rotations compared to the translations, to make
// sure they are in the same range. In general, it's best to  
// use automatic scales estimation:
(AutomaticScalesEstimation "true")

// Automatically guess an initial translation by aligning the
// geometric centers of the fixed and moving.
(AutomaticTransformInitialization "true")

// Whether transforms are combined by composition or by addition.
// In generally, Compose is the best option in most cases.
// It does not influence the results very much.
(HowToCombineTransforms "Compose")

// ******************* Similarity measure *********************

// Number of grey level bins in each resolution level,
// for the mutual information. 16 or 32 usually works fine.
// You could also employ a hierarchical strategy:
//(NumberOfHistogramBins 16 32 64)
(NumberOfHistogramBins 32)

// If you use a mask, this option is important. 
// If the mask serves as region of interest, set it to false.
// If the mask indicates which pixels are valid, then set it to true.
// If you do not use a mask, the option doesn't matter.
(ErodeMask "true")

// ******************** Multiresolution **********************

// The number of resolutions. 1 Is only enough if the expected
// deformations are small. 3 or 4 mostly works fine. For large
// images and large deformations, 5 or 6 may even be useful.
(NumberOfResolutions 4)

// The downsampling/blurring factors for the image pyramids.
// By default, the images are downsampled by a factor of 2
// compared to the next resolution.
// So, in 2D, with 4 resolutions, the following schedule is used:
//(ImagePyramidSchedule 8 8  4 4  2 2  1 1 )
// And in 3D:
//(ImagePyramidSchedule 8 8 8  4 4 4  2 2 2  1 1 1 )
// You can specify any schedule, for example:
//(ImagePyramidSchedule 4 4  4 3  2 1  1 1 )
// Make sure that the number of elements equals the number
// of resolutions times the image dimension.

// ******************* Optimizer ****************************

// Maximum number of iterations in each resolution level:
// 200-500 works usually fine for rigid registration.
// For more robustness, you may increase this to 1000-2000.
//(MaximumNumberOfIterations 250)
(MaximumNumberOfIterations 10)

// The step size of the optimizer, in mm. By default the voxel size is used.
// which usually works well. In case of unusual high-resolution images
// (eg histology) it is necessary to increase this value a bit, to the size
// of the "smallest visible structure" in the image:
//(MaximumStepLength 0.001)

// **************** Image sampling **********************

// Number of spatial samples used to compute the mutual
// information (and its derivative) in each iteration.
// With an AdaptiveStochasticGradientDescent optimizer,
// in combination with the two options below, around 2000
// samples may already suffice.
(NumberOfSpatialSamples 2048)

// Refresh these spatial samples in every iteration, and select
// them randomly. See the manual for information on other sampling
// strategies.
(NewSamplesEveryIteration "true")
(ImageSampler "Random")

// ************* Interpolation and Resampling ****************

// Order of B-Spline interpolation used during registration/optimisation.
// It may improve accuracy if you set this to 3. Never use 0.
// An order of 1 gives linear interpolation. This is in most 
// applications a good choice.
(BSplineInterpolationOrder 1)

// Order of B-Spline interpolation used for applying the final
// deformation.
// 3 gives good accuracy; recommended in most cases.
// 1 gives worse accuracy (linear interpolation)
// 0 gives worst accuracy, but is appropriate for binary images
// (masks, segmentations); equivalent to nearest neighbor interpolation.
(FinalBSplineInterpolationOrder 3)

//Default pixel value for pixels that come from outside the picture:
(DefaultPixelValue 0)

// Choose whether to generate the deformed moving image.
// You can save some time by setting this to false, if you are
// only interested in the final (nonrigidly) deformed moving image
// for example.
(WriteResultImage "true")

// The pixel type and format of the resulting deformed moving image
//(ResultImagePixelType "short")
(ResultImagePixelType "float")
//ResultImageFormat "mhd")
(ResultImageFormat "nii")

=============== end of ParameterFile: C:\Users\Wadha\Documents\Elastix_PARS\parameters__Affine_AMSradians_modified_10_0.001.txt ===============

Reading images...
Reading images took 29 ms.

WARNING: the fixed pyramid schedule is not fully specified!
  A default pyramid schedule is used.
WARNING: the moving pyramid schedule is not fully specified!
  A default pyramid schedule is used.
WARNING: The parameter "AutomaticTransformInitializationMethod", requested at entry number 0, does not exist at all.
  The default value "GeometricalCenter" is used instead.
Transform parameters are initialized as: [1, 0, 0, 1, 0, -69]
Scales are estimated automatically.
Scales for transform parameters are: [22100.25, 22100.25, 22100.25, 22100.25, 1, 1]
Initialization of all components (before registration) took: 42 ms.
Preparation of the image pyramids took: 27 ms.

Resolution: 0
WARNING: The parameter "ShowExactMetricValue", requested at entry number 0, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "CheckNumberOfSamples", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseMultiThreadingForMetrics", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeFixedMask", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeMovingMask", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.
Setting the fixed masks took: 4 ms.
Setting the moving masks took: 3 ms.
WARNING: The parameter "UseNormalization", requested at entry number 0, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "NumberOfSamplesForSelfHessian", requested at entry number 0, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SelfHessianSmoothingSigma", requested at entry number 0, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SelfHessianNoiseRange", requested at entry number 0, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SP_A", requested at entry number 0, does not exist at all.
  The default value "20" is used instead.
WARNING: The parameter "MaximumNumberOfSamplingAttempts", requested at entry number 0, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "SigmoidInitialTime", requested at entry number 0, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "MaxBandCovSize", requested at entry number 0, does not exist at all.
  The default value "192" is used instead.
WARNING: The parameter "NumberOfBandStructureSamples", requested at entry number 0, does not exist at all.
  The default value "10" is used instead.
WARNING: The parameter "UseAdaptiveStepSizes", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "AutomaticParameterEstimation", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseConstantStep", requested at entry number 0, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "MaximumStepLength", requested at entry number 0, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "NumberOfGradientMeasurements", requested at entry number 0, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "NumberOfJacobianMeasurements", requested at entry number 0, does not exist at all.
  The default value "1000" is used instead.
WARNING: The parameter "NumberOfSamplesForExactGradient", requested at entry number 0, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SigmoidScaleFactor", requested at entry number 0, does not exist at all.
  The default value "0.1" is used instead.
Elastix initialization of all components (for this resolution) took: 303 ms.
Initialization of AdvancedMeanSquares metric took: 0 ms.
Starting automatic parameter estimation for AdaptiveStochasticGradientDescent ...
WARNING: The parameter "ASGDParameterEstimationMethod", requested at entry number 0, does not exist at all.
  The default value "Original" is used instead.
  Computing JacobianTerms ...
  Computing the Jacobian terms took 0.001860s
  NumberOfGradientMeasurements to estimate sigma_i: 8
  Sampling gradients ...
  Sampling the gradients took 0.019760s
Automatic parameter estimation took 0.25s
1:ItNr	2:Metric	3a:Time	3b:StepSize	4:||Gradient||	Time[ms]
0	0.360400	0.000000	41.317166	0.017277	468.3
1	0.286847	0.000000	41.317166	0.013357	1.1
2	0.333587	0.000000	41.317166	0.013474	0.9
3	0.338812	0.000000	41.317166	0.018200	1.1
4	0.262944	0.000000	41.317166	0.011771	1.2
5	0.219035	0.000000	41.317166	0.008961	1.1
6	0.270016	0.000000	41.317166	0.010089	0.9
7	0.282543	0.000000	41.317166	0.012199	1.1
8	0.251193	0.000000	41.317166	0.009555	0.9
9	0.309987	0.000000	41.317166	0.015041	1.1
Time spent in resolution 0 (ITK initialization and iterating): 0.504 s.
Stopping condition: Maximum number of iterations has been reached.
Settings of AdaptiveStochasticGradientDescent in resolution 0:
( SP_a 867.660494 )
( SP_A 20.000000 )
( SP_alpha 1.000000 )
( SigmoidMax 1.000000 )
( SigmoidMin -0.067178 )
( SigmoidScale 0.000001 )

Resolution: 1
WARNING: The parameter "ShowExactMetricValue", requested at entry number 1, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "CheckNumberOfSamples", requested at entry number 1, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseMultiThreadingForMetrics", requested at entry number 1, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeFixedMask", requested at entry number 1, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeMovingMask", requested at entry number 1, does not exist at all.
  The default value "true" is used instead.
Setting the fixed masks took: 4 ms.
Setting the moving masks took: 4 ms.
WARNING: The parameter "UseNormalization", requested at entry number 1, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "NumberOfSamplesForSelfHessian", requested at entry number 1, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SelfHessianSmoothingSigma", requested at entry number 1, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SelfHessianNoiseRange", requested at entry number 1, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SP_A", requested at entry number 1, does not exist at all.
  The default value "20" is used instead.
WARNING: The parameter "MaximumNumberOfSamplingAttempts", requested at entry number 1, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "SigmoidInitialTime", requested at entry number 1, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "MaxBandCovSize", requested at entry number 1, does not exist at all.
  The default value "192" is used instead.
WARNING: The parameter "NumberOfBandStructureSamples", requested at entry number 1, does not exist at all.
  The default value "10" is used instead.
WARNING: The parameter "UseAdaptiveStepSizes", requested at entry number 1, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "AutomaticParameterEstimation", requested at entry number 1, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseConstantStep", requested at entry number 1, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "MaximumStepLength", requested at entry number 1, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "NumberOfGradientMeasurements", requested at entry number 1, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "NumberOfJacobianMeasurements", requested at entry number 1, does not exist at all.
  The default value "1000" is used instead.
WARNING: The parameter "NumberOfSamplesForExactGradient", requested at entry number 1, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SigmoidScaleFactor", requested at entry number 1, does not exist at all.
  The default value "0.1" is used instead.
Elastix initialization of all components (for this resolution) took: 305 ms.
Initialization of AdvancedMeanSquares metric took: 0 ms.
Starting automatic parameter estimation for AdaptiveStochasticGradientDescent ...
WARNING: The parameter "ASGDParameterEstimationMethod", requested at entry number 0, does not exist at all.
  The default value "Original" is used instead.
  Computing JacobianTerms ...
  Computing the Jacobian terms took 0.000483s
  NumberOfGradientMeasurements to estimate sigma_i: 8
  Sampling gradients ...
  Sampling the gradients took 0.023453s
Automatic parameter estimation took 0.25s
1:ItNr	2:Metric	3a:Time	3b:StepSize	4:||Gradient||	Time[ms]
0	0.249414	0.000000	57.911832	0.009607	469.7
1	0.233597	0.000000	57.911832	0.007710	1.1
2	0.221900	0.000000	57.911832	0.009297	0.9
3	0.239387	0.000000	57.911832	0.008099	1.1
4	0.222711	0.000000	57.911832	0.009251	0.9
5	0.207279	0.000000	57.911832	0.009606	1.1
6	0.241069	0.000000	57.911832	0.011779	1.0
7	0.217964	0.000000	57.911832	0.010161	1.2
8	0.233371	0.000000	57.911832	0.010568	0.9
9	0.238945	0.000000	57.911832	0.012206	1.1
Time spent in resolution 1 (ITK initialization and iterating): 0.507 s.
Stopping condition: Maximum number of iterations has been reached.
Settings of AdaptiveStochasticGradientDescent in resolution 1:
( SP_a 1216.148482 )
( SP_A 20.000000 )
( SP_alpha 1.000000 )
( SigmoidMax 1.000000 )
( SigmoidMin -0.105013 )
( SigmoidScale 0.000000 )

Resolution: 2
WARNING: The parameter "ShowExactMetricValue", requested at entry number 2, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "CheckNumberOfSamples", requested at entry number 2, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseMultiThreadingForMetrics", requested at entry number 2, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeFixedMask", requested at entry number 2, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeMovingMask", requested at entry number 2, does not exist at all.
  The default value "true" is used instead.
Setting the fixed masks took: 3 ms.
Setting the moving masks took: 4 ms.
WARNING: The parameter "UseNormalization", requested at entry number 2, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "NumberOfSamplesForSelfHessian", requested at entry number 2, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SelfHessianSmoothingSigma", requested at entry number 2, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SelfHessianNoiseRange", requested at entry number 2, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SP_A", requested at entry number 2, does not exist at all.
  The default value "20" is used instead.
WARNING: The parameter "MaximumNumberOfSamplingAttempts", requested at entry number 2, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "SigmoidInitialTime", requested at entry number 2, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "MaxBandCovSize", requested at entry number 2, does not exist at all.
  The default value "192" is used instead.
WARNING: The parameter "NumberOfBandStructureSamples", requested at entry number 2, does not exist at all.
  The default value "10" is used instead.
WARNING: The parameter "UseAdaptiveStepSizes", requested at entry number 2, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "AutomaticParameterEstimation", requested at entry number 2, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseConstantStep", requested at entry number 2, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "MaximumStepLength", requested at entry number 2, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "NumberOfGradientMeasurements", requested at entry number 2, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "NumberOfJacobianMeasurements", requested at entry number 2, does not exist at all.
  The default value "1000" is used instead.
WARNING: The parameter "NumberOfSamplesForExactGradient", requested at entry number 2, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SigmoidScaleFactor", requested at entry number 2, does not exist at all.
  The default value "0.1" is used instead.
Elastix initialization of all components (for this resolution) took: 291 ms.
Initialization of AdvancedMeanSquares metric took: 1 ms.
Starting automatic parameter estimation for AdaptiveStochasticGradientDescent ...
WARNING: The parameter "ASGDParameterEstimationMethod", requested at entry number 0, does not exist at all.
  The default value "Original" is used instead.
  Computing JacobianTerms ...
  Computing the Jacobian terms took 0.000652s
  NumberOfGradientMeasurements to estimate sigma_i: 8
  Sampling gradients ...
  Sampling the gradients took 0.043817s
Automatic parameter estimation took 0.27s
1:ItNr	2:Metric	3a:Time	3b:StepSize	4:||Gradient||	Time[ms]
0	0.219443	0.000000	54.752862	0.010011	490.5
1	0.221858	0.000000	54.752862	0.009671	1.3
2	0.225277	0.000000	54.752862	0.010210	0.9
3	0.197533	0.000000	54.752862	0.008054	1.1
4	0.244061	0.000000	54.752862	0.011798	0.9
5	0.253483	0.000000	54.752862	0.010811	1.0
6	0.266736	0.000000	54.752862	0.009668	0.9
7	0.253743	0.000000	54.752862	0.010586	1.1
8	0.254324	0.000000	54.752862	0.010411	0.9
9	0.255782	0.000000	54.752862	0.012760	1.2
Time spent in resolution 2 (ITK initialization and iterating): 0.526 s.
Stopping condition: Maximum number of iterations has been reached.
Settings of AdaptiveStochasticGradientDescent in resolution 2:
( SP_a 1149.810103 )
( SP_A 20.000000 )
( SP_alpha 1.000000 )
( SigmoidMax 1.000000 )
( SigmoidMin -0.044269 )
( SigmoidScale 0.000000 )

Resolution: 3
WARNING: The parameter "ShowExactMetricValue", requested at entry number 3, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "CheckNumberOfSamples", requested at entry number 3, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseMultiThreadingForMetrics", requested at entry number 3, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeFixedMask", requested at entry number 3, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "ErodeMovingMask", requested at entry number 3, does not exist at all.
  The default value "true" is used instead.
Setting the fixed masks took: 3 ms.
Setting the moving masks took: 3 ms.
WARNING: The parameter "UseNormalization", requested at entry number 3, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "NumberOfSamplesForSelfHessian", requested at entry number 3, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SelfHessianSmoothingSigma", requested at entry number 3, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SelfHessianNoiseRange", requested at entry number 3, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "SP_A", requested at entry number 3, does not exist at all.
  The default value "20" is used instead.
WARNING: The parameter "MaximumNumberOfSamplingAttempts", requested at entry number 3, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "SigmoidInitialTime", requested at entry number 3, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "MaxBandCovSize", requested at entry number 3, does not exist at all.
  The default value "192" is used instead.
WARNING: The parameter "NumberOfBandStructureSamples", requested at entry number 3, does not exist at all.
  The default value "10" is used instead.
WARNING: The parameter "UseAdaptiveStepSizes", requested at entry number 3, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "AutomaticParameterEstimation", requested at entry number 3, does not exist at all.
  The default value "true" is used instead.
WARNING: The parameter "UseConstantStep", requested at entry number 3, does not exist at all.
  The default value "false" is used instead.
WARNING: The parameter "MaximumStepLength", requested at entry number 3, does not exist at all.
  The default value "1" is used instead.
WARNING: The parameter "NumberOfGradientMeasurements", requested at entry number 3, does not exist at all.
  The default value "0" is used instead.
WARNING: The parameter "NumberOfJacobianMeasurements", requested at entry number 3, does not exist at all.
  The default value "1000" is used instead.
WARNING: The parameter "NumberOfSamplesForExactGradient", requested at entry number 3, does not exist at all.
  The default value "100000" is used instead.
WARNING: The parameter "SigmoidScaleFactor", requested at entry number 3, does not exist at all.
  The default value "0.1" is used instead.
Elastix initialization of all components (for this resolution) took: 275 ms.
Initialization of AdvancedMeanSquares metric took: 7 ms.
Starting automatic parameter estimation for AdaptiveStochasticGradientDescent ...
WARNING: The parameter "ASGDParameterEstimationMethod", requested at entry number 0, does not exist at all.
  The default value "Original" is used instead.
  Computing JacobianTerms ...
  Computing the Jacobian terms took 0.000618s
  NumberOfGradientMeasurements to estimate sigma_i: 8
  Sampling gradients ...
  Sampling the gradients took 0.117546s
Automatic parameter estimation took 0.34s
1:ItNr	2:Metric	3a:Time	3b:StepSize	4:||Gradient||	Time[ms]
0	0.232069	0.000000	58.760462	0.009344	570.1
1	0.261359	0.000000	58.760462	0.009991	1.3
2	0.224457	0.000000	58.760462	0.007200	1.0
3	0.240425	0.000000	58.760462	0.011437	1.2
4	0.250694	0.000000	58.760462	0.009372	0.9
5	0.272025	0.000000	58.760462	0.008186	1.2
6	0.235345	0.000000	58.760462	0.009675	0.9
7	0.251222	0.000000	58.760462	0.011866	1.1
8	0.287714	0.000000	58.760462	0.010157	1.0
9	0.264319	0.000000	58.760462	0.009273	1.2
Time spent in resolution 3 (ITK initialization and iterating): 0.607 s.
Stopping condition: Maximum number of iterations has been reached.
Settings of AdaptiveStochasticGradientDescent in resolution 3:
( SP_a 1233.969706 )
( SP_A 20.000000 )
( SP_alpha 1.000000 )
( SigmoidMax 1.000000 )
( SigmoidMin -0.049272 )
( SigmoidScale 0.000000 )

=============== start of TransformParameterFile ===============
(Transform "AffineTransform")
(NumberOfParameters 6)
(TransformParameters 0.997247 0.056419 0.049189 0.998649 -11.981473 -55.294642)
(InitialTransformParametersFileName "NoInitialTransform")
(HowToCombineTransforms "Compose")

// Image specific
(FixedImageDimension 2)
(MovingImageDimension 2)
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(Size 512 512)
(Index 0 0)
(Spacing 1.0000000000 1.0000000000)
(Origin -1.0000000000 -1.0000000000)
(Direction -1.0000000000 0.0000000000 0.0000000000 -1.0000000000)
(UseDirectionCosines "true")

// AdvancedAffineTransform specific
(CenterOfRotationPoint -256.5000000000 -256.5000000000)

// ResampleInterpolator specific
(ResampleInterpolator "FinalBSplineInterpolator")
(FinalBSplineInterpolationOrder 3)

// Resampler specific
(Resampler "DefaultResampler")
(DefaultPixelValue 0.000000)
(ResultImageFormat "nii")
(ResultImagePixelType "float")
(CompressResultImage "false")

=============== end of TransformParameterFile ===============

Creating the TransformParameterFile took 0.00s

Registration result checksum: 3198895987

Applying final transform ...
  Applying final transform took 0.14s

Final metric value  = 0.264319
Settings of AdaptiveStochasticGradientDescent for all resolutions:
( SP_a 867.660494 1216.148482 1149.810103 1233.969706 )
( SP_A 20.000000 20.000000 20.000000 20.000000 )
( SP_alpha 1.000000 1.000000 1.000000 1.000000 )
( SigmoidMax 1.000000 1.000000 1.000000 1.000000 )
( SigmoidMin -0.067178 -0.105013 -0.044269 -0.049272 )
( SigmoidScale 0.000001 0.000000 0.000000 0.000000 )

Time spent on saving the results, applying the final transform etc.: 378 ms.
Running elastix with parameter file 0: "C:\Users\Wadha\Documents\Elastix_PARS\parameters__Affine_AMSradians_modified_10_0.001.txt", has finished.

Current time: Wed Sep 12 01:26:19 2018.
Time used for running elastix with this parameter file:
  4.3s.

-------------------------------------------------------------------------

Total time elapsed: 4.5s.

**Comment by kaspermarstal** [comment]
The warnings serve mainly to inform users about the default settings when no parameter is specified. Is there any warning in particular that concerns you? Otherwise I wouldn't worry about it.

**Comment by Wafamah** [comment]
I appreciate your quick response. 

I'm facing a problem to fully activate the AffineTransform. When I tried the default settings I got an error message(Too many samples out side the moving image). So, I reduced the optimizer step length to be 0.001 instead of 1.0. I got the (result 1) as you can see. Then I increased the iterations numbers to be 2000 instead of 250. I got the (result 2). In both cases Affine didn't scale or register the moving to the fixed. It is just handling the shifting.  **Is there an explanation of why Affinetransform didn't work properly ? and How can I fix that?.** I attached the parameter file that I used. (I masked both images)

Your response is highly appreciated. 

![fixed_image](https://user-images.githubusercontent.com/43178260/45412121-46ede180-b6b9-11e8-97fa-0dff220f894e.png)
![moving_image](https://user-images.githubusercontent.com/43178260/45412124-47867800-b6b9-11e8-9d2e-c9c9ddaa2483.png)
![result 1](https://user-images.githubusercontent.com/43178260/45412126-47867800-b6b9-11e8-9b76-b44be14318f2.png)
![result 2](https://user-images.githubusercontent.com/43178260/45412129-481f0e80-b6b9-11e8-9609-bc6577b9d3d5.png)
[Parameterfile.txt](https://github.com/SuperElastix/SimpleElastix/files/2374174/Parameterfile.txt)

**Comment by kaspermarstal** [comment]
"Too many samples outside the moving images" mean that the images do not overlap. Do your images have the same world coordinate information (origin, spacing direction)? Also, for this problem, the rigid transform might be more appropriate.

**Comment by Wafamah** [comment]
The option of (AutomaticTransformInitialization "true") is activated in the parameter file that should enable  the overlapping between two images. Too many samples could be caused by too large steps are taken during the registration. So,  initially the images have an overlap, but during the registration the moving image is moved such that the overlap disappears. Usually, this is because too large steps are taken during the registration and I solved that by decreasing the step size(length) of the optimizer to be 0.001 instead of 1.0. 

The rigid are not able to scale the moving image it should handle the shifting only. 

Is there a suggestion to solve this issue?

**Comment by kaspermarstal** [comment]
I don't think the B-spline transform does automatic initialization. You can do an affine registration first with AutomaticTransformInitialization set to "true". Sorry for the late reply. Feel free to open if this is still an issue.
