### ISSUE TITLE
Transforming a set of points

### ISSUE THREAD

**Issue by CChazo** [SuperElastix/SimpleElastix#229]
Hi all,

I am trying to rotate a set of 3D points with the transformation resulting from registering two 3D volumes. This is my Python code.

`
import SimpleITK as sitk

if __name__ == "__main__":

	mI = sitk.ReadImage("./pat1/sa.nii")
	fI = sitk.ReadImage("./pat1/pc.nii")

	## No initial transform - rigid
	selx_noinit = sitk.SimpleElastix()
	stfx = sitk.SimpleTransformix()

	selx_noinit.SetFixedImage(fI)
	selx_noinit.SetMovingImage(mI)
	selx_noinit.SetParameterMap(sitk.GetDefaultParameterMap("rigid"))
	selx_noinit.Execute()

	selx_noinit.ExecuteInverse()
	stfx.SetMovingPointSetFileName("./pat1/segm.pts")
	pM = selx_noinit.GetInverseTransformParameterMap()
	
	stfx.SetTransformParameterMap(pM)
	stfx.Execute()
`
The file containing the point set, segm.txt, follows the elastix format described in the manual:

`
point
75000
94.614449 -84.493205 -20.494166

94.115330 -84.520082 -22.083630

93.529649 -84.648437 -23.647707
...
`

However, outpoints.txt reveals that the input has been treated as 2D points. Notice how Point1-xcoord should be Point0-zcoord:

`
Point	0	; InputIndex = [ 382 -280 ]	; InputPoint = [ 94.614449 -84.493205 ]	; OutputIndexFixed = [ 386 -283 ]	; OutputPoint = [ 92.899027 -86.570405 ]	; Deformation = [ -1.715422 -2.077199 ]

Point	1	; InputIndex = [ -18 166 ]	; InputPoint = [ -20.494166 94.115330 ]	; OutputIndexFixed = [ -22 167 ]	; OutputPoint = [ -15.426690 96.231513 ]	; Deformation = [ 5.067476 2.116183 ]

Point	2	; InputIndex = [ 237 -22 ]	; InputPoint = [ -84.520082 -22.083630 ]	; OutputIndexFixed = [ 226 -13 ]	; OutputPoint = [ -83.767592 -17.483206 ]	; Deformation = [ 0.752490 4.600424 ]
`

The transform parameter file  (https://github.com/SuperElastix/SimpleElastix/files/2374761/TransformParameters.0.txt) has FixedImageDimension  and MovingImageDimension set to 3.

The issue has also been reproduced using the command line executable transformix.exe.

Maybe I'm missing a parameter meant to specify the point dimensions. If there is one, I couldn't find it. I'd appreciate some help on the issue.

Many thanks

**Comment by kaspermarstal** [comment]
Just a sanity check: What happens if you use the forward transform parameter map and the inverse one? ExecuteInverse() was removed a long time ago because it was difficult to make it work consistently. Perhaps you are running into the some of the problems that caused it to be removed.

**Comment by kaspermarstal** [comment]
Can you show the contents of the transform parameter map?

**Comment by CChazo** [comment]
sitk.PrintParameterMap(pM)

```
ParameterMap 0:

  (CenterOfRotationPoint 40.118401 -36.165401 17.171301)

  (CompressResultImage "false")

  (ComputeZYX "false")

  (DefaultPixelValue 0.000000)

  (Direction -0.656120 -0.238475 -0.715986 -0.013248 -0.944972 0.326884 -0.754540 0.223960 0.616856)

  (FinalBSplineInterpolationOrder 3.000000)

  (FixedImageDimension 3.000000)

  (FixedInternalImagePixelType "float")

  (HowToCombineTransforms "Compose")

  (Index 0.000000 0.000000 0.000000)

  (InitialTransformParametersFileName "NoInitialTransform")

  (MovingImageDimension 3.000000)

  (MovingInternalImagePixelType "float")

  (NumberOfParameters 6.000000)

  (Origin 194.345993 90.160599 -97.800201)

  (ResampleInterpolator "FinalBSplineInterpolator")

  (Resampler "DefaultResampler")

  (ResultImageFormat "nii")

  (ResultImagePixelType "float")

  (Size 50.000000 160.000000 160.000000)

  (Spacing 1.999990 2.000000 2.000000)

  (Transform "EulerTransform")

  (TransformParameters 0.040317 0.002128 -0.000520 -1.103700 -3.295130 -9.063050)

  (UseDirectionCosines "true")
```

**Comment by kaspermarstal** [comment]
Transformix was recently upgraded and this issue should now be fixed. Feel free to re-open if you still experience this issue.
