### ISSUE TITLE
.../Wrapping/Python/Packaging/_SimpleITK.so:' doesn't exist or not a regular file

### ISSUE THREAD

**Issue by cwule** [SuperElastix/SimpleElastix#230]
I successfully built SimpleElastix according to this description:
https://simpleelastix.readthedocs.io/GettingStarted.html

When trying to install it with `sudo python setup.py install` in the Packaging folder, it stops with the following error message:

`error: can't copy '/homeFolder/SimpleElastix/build/SimpleITK-build/Wrapping/Python/Packaging/_SimpleITK.so': doesn't exist or not a regular file`

**Comment by cwule** [comment]
This was an issue with my anaconda installation.

**Comment by thatguy14** [comment]
How did you fix this issue? I think I am having the same problem

**Comment by cwule** [comment]
Unfortunately no elegant solution, just checked my python version and it was managed by anaconda. Tried it on a different machine without anaconda and it worked.

**Comment by kaspermarstal** [comment]
Thanks for the information!

**Comment by vfmatzkin** [comment]
I've reached the same error when trying to install with a conda environment active :(.

**Comment by JLrumberger** [comment]
I also encountered this issue with anaconda and solved this by copying 
`SimpleElastix/build/SimpleITK-build/Wrapping/Python/_SimpleITK.so` 
to 
`SimpleElastix/build/SimpleITK-build/Wrapping/Python/Packaging/_SimpleITK.so`
and running `python setup.py install` again.

**Comment by vfmatzkin** [comment]
@JLrumberger check [this tutorial](https://gist.github.com/vfmatzkin/0fcc79a61f9bafcc2113fd83a8900937) I've made some months ago (I've managed to install it under a specific set of conditions). I've ended up using [ANTspyx](https://pypi.org/project/antspyx/) since it's way easier to install.
