### ISSUE TITLE
Errors in installing

### ISSUE THREAD

**Issue by zhuxin77** [SuperElastix/SimpleElastix#231]
Dear all,

I met some errors when I installed SimpleElastix. Would you please kindly help me find any solutions?

My OS is ubuntu 16.04 LTS

Scanning dependencies of target ElastixFilter
[ 47%] Building CXX object Examples/ITKIntegration/CMakeFiles/ElastixFilter.dir/ElastixFilter.cxx.o
In file included from /home/bit/build/Elastix/Core/Main/elxTransformixFilter.h:184:0,
                 from /home/bit/SimpleElastix/Code/Elastix/src/sitkTransformixImageFilterImpl.h:9,
                 from /home/bit/SimpleElastix/Code/Elastix/src/sitkTransformixImageFilterImpl.cxx:5:
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx: In member function ‘virtual void elastix::TransformixFilter<TMovingImage>::GenerateOutputInformation()’:
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:289:47: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( spacingMapIter == transformParameterMap.cend() )
                                               ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:296:44: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( sizeMapIter == transformParameterMap.cend() )
                                            ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:303:45: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( indexMapIter == transformParameterMap.cend() )
                                             ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:310:46: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( originMapIter == transformParameterMap.cend() )
                                              ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:317:49: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( directionMapIter == transformParameterMap.cend() )
                                                 ^
In file included from /home/bit/build/Elastix/Core/Main/elxTransformixFilter.h:184:0,
                 from /home/bit/SimpleElastix/Code/Elastix/src/sitkTransformixImageFilterImpl.h:9,
                 from /home/bit/SimpleElastix/Code/Elastix/src/sitkTransformixImageFilter.cxx:5:
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx: In member function ‘virtual void elastix::TransformixFilter<TMovingImage>::GenerateOutputInformation()’:
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:289:47: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( spacingMapIter == transformParameterMap.cend() )
                                               ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:296:44: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( sizeMapIter == transformParameterMap.cend() )
                                            ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:303:45: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( indexMapIter == transformParameterMap.cend() )
                                             ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:310:46: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( originMapIter == transformParameterMap.cend() )
                                              ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:317:49: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( directionMapIter == transformParameterMap.cend() )
                                                 ^
In file included from /home/bit/build/Elastix/Core/Main/elxTransformixFilter.h:184:0,
                 from /home/bit/SimpleElastix/Examples/ITKIntegration/TransformixFilter.cxx:4:
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx: In member function ‘virtual void elastix::TransformixFilter<TMovingImage>::GenerateOutputInformation()’:
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:289:47: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( spacingMapIter == transformParameterMap.cend() )
                                               ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:296:44: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( sizeMapIter == transformParameterMap.cend() )
                                            ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:303:45: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( indexMapIter == transformParameterMap.cend() )
                                             ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:310:46: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( originMapIter == transformParameterMap.cend() )
                                              ^
/home/bit/build/Elastix/Core/Main/elxTransformixFilter.hxx:317:49: error: ‘const ParameterMapType {aka const class std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >}’ has no member named ‘cend’
   if( directionMapIter == transformParameterMap.cend() )
                                                 ^
Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/build.make:62: recipe for target 'Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/sitkTransformixImageFilter.cxx.o' failed
make[5]: *** [Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/sitkTransformixImageFilter.cxx.o] Error 1
make[5]: *** Waiting for unfinished jobs....
Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/build.make:86: recipe for target 'Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/sitkTransformixImageFilterImpl.cxx.o' failed
make[5]: *** [Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/sitkTransformixImageFilterImpl.cxx.o] Error 1
Examples/ITKIntegration/CMakeFiles/TransformixFilter.dir/build.make:62: recipe for target 'Examples/ITKIntegration/CMakeFiles/TransformixFilter.dir/TransformixFilter.cxx.o' failed
make[5]: *** [Examples/ITKIntegration/CMakeFiles/TransformixFilter.dir/TransformixFilter.cxx.o] Error 1
CMakeFiles/Makefile2:1235: recipe for target 'Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/all' failed
make[4]: *** [Code/Elastix/src/CMakeFiles/TransformixImageFilter.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5304: recipe for target 'Examples/ITKIntegration/CMakeFiles/TransformixFilter.dir/all' failed
make[4]: *** [Examples/ITKIntegration/CMakeFiles/TransformixFilter.dir/all] Error 2
[ 47%] Linking CXX executable ../../bin/ElastixFilter
[ 47%] Built target ElastixFilter
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:117: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:400: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kaspermarstal** [comment]
Looks like the call to `cend` requires C++11. Not sure what is going on here as your types does mention C++11. Anyway, let's revert to just using `end` instead of `cend`. This section is not performance-critical. Stay tuned.

**Comment by zhuxin77** [comment]
Dear Dr.  Kaspermarstal 
Thank you very much!

By the way, I successfully compiled SimpleElastix using Visual Studio 2017.

**Comment by romangrothausmann** [comment]
@kaspermarstal any news on this? I experience the same problem when trying to create a docker image based on ubuntu:18.04 with [SE-1.1.0](https://github.com/romangrothausmann/elastix_scripts/blob/ea6da2cfa3bd1a9ebc7faaf5392e8c9776a80abb/Dockerfile#L23) . See e.g. this GL-CI log:
https://gitlab.com/romangrothausmann/elastix_scripts/-/jobs/201479237
which originates from building with this DF:
https://github.com/romangrothausmann/elastix_scripts/blob/ea6da2cfa3bd1a9ebc7faaf5392e8c9776a80abb/Dockerfile
I have been able to compile SE-1.1.0 outside docker before. Using current master (https://github.com/SuperElastix/SimpleElastix/commit/2a79d151894021c66dceeb2c8a64ff61506e7155) leads to other compilation problems such as:
```
In file included from /SimpleElastix/Examples/ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx:21:0:
/opt/SimpleElastix/include/SimpleITK-1.2/SimpleITK.h:86:10: fatal error: sitkElastixImageFilter.h: No such file or directory
 #include "sitkElastixImageFilter.h"
```
see e.g. https://gitlab.com/romangrothausmann/elastix_scripts/-/jobs/201046779

**Comment by romangrothausmann** [comment]
With specification of `CMAKE_CXX_STANDARD=11` such as in https://github.com/romangrothausmann/elastix_scripts/commit/8ca31054061c5150bba4d81097325f16e6174892 compilation of SE-1.1.0 works.
Many thanks @kaspermarstal for that hint. Not sure why this was not needed before.
