### ISSUE TITLE
oblique image resulted from a registration via elastix  

### ISSUE THREAD

**Issue by Wafamah** [SuperElastix/SimpleElastix#232]
Hi all, 

I registered two images with masking the fixed image only and I got an oblique image as a result of the registration process. See the attached image please. 

Do you have an idea or suggestion on the parameters that could fix this problem and bring the 'in plane of the image' to the front (fixing the oblique issue)? 

Thanks u,
![result 0](https://user-images.githubusercontent.com/43178260/45860902-083ce300-bdad-11e8-861d-72461fced71d.png)

**Comment by kaspermarstal** [comment]
I don't inderstand the problem from your description. Feel free to reopen if this is still an issue.
