### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Alxaline** [SuperElastix/SimpleElastix#234]
Hello,

I try to compile with superbuild but the process stop at [ 60%] Built target Swig : 

[  4%] Performing download step (git clone) for 'ITK'
[  8%] Built target SuperBuildSimpleITKSourceReal
Cloning into 'ITK'...
[  8%] Built target SuperBuildSimpleITKSource
[ 47%] Built target virtualenv
[ 47%] Built target Lua
[ 47%] Built target PCRE
[ 60%] Built target Swig
^CCMakeFiles/ITK.dir/build.make:89: recipe for target 'ITK-prefix/src/ITK-stamp/ITK-download' failed
make[2]: *** [ITK-prefix/src/ITK-stamp/ITK-download] Interrupt
CMakeFiles/Makefile2:546: recipe for target 'CMakeFiles/ITK.dir/all' failed
make[1]: *** [CMakeFiles/ITK.dir/all] Interrupt
Makefile:83: recipe for target 'all' failed
make: *** [all] Interrupt

My os is Ubuntu 18.04.1 LTS
cmake version 3.10.2
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

Best regards

**Comment by Alxaline** [comment]
I just solved my compilation issue passing in root.

**Comment by PertuyF** [comment]
Looks like it is the same issue as #233

**Comment by Alxaline** [comment]
Thanks for your help PertuyF, i did what you mentionned copying _SimpleITK.so in Packagind directory and the step : sudo python setup.py install   works.
But now when i try to use SimpleElastix, i get this kind of error AttributeError: module 'SimpleITK' has no attribute 'ElastixImageFilter' ...

**Comment by Alxaline** [comment]
I solved my problem, I write the steps for people who have similar issue : 
 
1) Uninstall simpleitk for my environment : conda uninstall simpleitk
2) Install SimpleElastix
3) chmod my environnment
4) python setup.py install

**Comment by kaspermarstal** [comment]
Thanks for the detailed feedback!
