### ISSUE TITLE
install SimpleElastix someMD5 is not found

### ISSUE THREAD

**Issue by icetomato** [SuperElastix/SimpleElastix#236]
system : CENTOS7

git clone https://github.com/SuperElastix/SimpleElastix
 mkdir build
 cd build
cmake ../SimpleElastix/SuperBuild
 make -j4

[ 15%] Generating /home/data/tr/build/ExternalData/.ExternalSource/virtualenv-15.1.0.tar.gz
-- Fetching "https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/2e115fe26e435e33b0d5c022e4490567"
-- Fetching "https://simpleitk.github.io/SimpleITKExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c"
-- Fetching "https://itk.org/files/ExternalData/MD5/2e115fe26e435e33b0d5c022e4490567"
-- Fetching "https://data.kitware.com:443/api/v1/file/hashsum/MD5/82133dfa7bba75ff9ad98a7046be687c/download"
-- Fetching "https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=890c808122bd90f398e6bc40ec862102&algorithm=MD5"
CMake Error at /home/data/tr/SimpleElastix/CMake/ExternalData.cmake:1122 (message):
  

  Object MD5=2e115fe26e435e33b0d5c022e4490567 not found at:

    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/2e115fe26e435e33b0d5c022e4490567/download ("Unsupported protocol")
    https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5 ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")

-- Fetching "https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=82133dfa7bba75ff9ad98a7046be687c&algorithm=MD5"
make[2]: *** [ExternalData/.ExternalSource/lua-5.1.5.tar.gz-hash-stamp] Error 1
make[2]: *** Waiting for unfinished jobs....
-- Fetching "https://simpleitk.github.io/SimpleITKExternalData/MD5/890c808122bd90f398e6bc40ec862102"
-- Fetching "https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/82133dfa7bba75ff9ad98a7046be687c"
-- Fetching "https://data.kitware.com:443/api/v1/file/hashsum/MD5/890c808122bd90f398e6bc40ec862102/download"
-- Fetching "https://itk.org/files/ExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c"
-- Fetching "https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=890c808122bd90f398e6bc40ec862102&algorithm=MD5"
CMake Error at /home/data/tr/SimpleElastix/CMake/ExternalData.cmake:1122 (message):
  

  Object MD5=82133dfa7bba75ff9ad98a7046be687c not found at:

    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=82133dfa7bba75ff9ad98a7046be687c&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/82133dfa7bba75ff9ad98a7046be687c/download ("Unsupported protocol")
    https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=82133dfa7bba75ff9ad98a7046be687c&algorithm=MD5 ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/82133dfa7bba75ff9ad98a7046be687c ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c ("Unsupported protocol")

make[2]: *** [ExternalData/.ExternalSource/swig-3.0.12.tar.gz-hash-stamp] Error 1
-- Fetching "https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/890c808122bd90f398e6bc40ec862102"
-- Fetching "https://itk.org/files/ExternalData/MD5/890c808122bd90f398e6bc40ec862102"
CMake Error at /home/data/tr/SimpleElastix/CMake/ExternalData.cmake:1122 (message):
  

  Object MD5=890c808122bd90f398e6bc40ec862102 not found at:

    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=890c808122bd90f398e6bc40ec862102&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/890c808122bd90f398e6bc40ec862102 ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/890c808122bd90f398e6bc40ec862102/download ("Unsupported protocol")
    https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=890c808122bd90f398e6bc40ec862102&algorithm=MD5 ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/890c808122bd90f398e6bc40ec862102 ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/890c808122bd90f398e6bc40ec862102 ("Unsupported protocol")

make[2]: *** [ExternalData/.ExternalSource/pcre-8.40.tar.gz-hash-stamp] Error 1
-- Fetching "https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=44e19f4134906fe2d75124427dc9b716&algorithm=MD5"
-- Fetching "https://simpleitk.github.io/SimpleITKExternalData/MD5/44e19f4134906fe2d75124427dc9b716"
-- Fetching "https://data.kitware.com:443/api/v1/file/hashsum/MD5/44e19f4134906fe2d75124427dc9b716/download"
-- Fetching "https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=44e19f4134906fe2d75124427dc9b716&algorithm=MD5"
-- Fetching "https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/44e19f4134906fe2d75124427dc9b716"
-- Fetching "https://itk.org/files/ExternalData/MD5/44e19f4134906fe2d75124427dc9b716"
CMake Error at /home/data/tr/SimpleElastix/CMake/ExternalData.cmake:1122 (message):
  

  Object MD5=44e19f4134906fe2d75124427dc9b716 not found at:

    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=44e19f4134906fe2d75124427dc9b716&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/44e19f4134906fe2d75124427dc9b716 ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/44e19f4134906fe2d75124427dc9b716/download ("Unsupported protocol")
    https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=44e19f4134906fe2d75124427dc9b716&algorithm=MD5 ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/44e19f4134906fe2d75124427dc9b716 ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/44e19f4134906fe2d75124427dc9b716 ("Unsupported protocol")

make[2]: *** [ExternalData/.ExternalSource/virtualenv-15.1.0.tar.gz-hash-stamp] Error 1
make[1]: *** [CMakeFiles/SuperBuildSimpleITKSourceReal.dir/all] Error 2
make: *** [all] Error 2

**Comment by icetomato** [comment]
mayday  mayday

**Comment by hellodmp** [comment]
This indicates that CMake was not compiles with SSL support. The "Unsupported protocol" message indicate that CMake can not communicate via "https".

The solution is to use a compiled version of CMake which supports SSL. If you compile CMake yourself, simply reconfigure CMake with the "CMAKE_USE_OPENSSL option enabled.

**Comment by icetomato** [comment]
thank you very much



chenbenqiangstx@163.com
 
From: hellodmp
Date: 2018-10-14 15:59
To: SuperElastix/SimpleElastix
CC: icetomato; Author
Subject: Re: [SuperElastix/SimpleElastix] install SimpleElastix someMD5 is not found (#236)
This indicates that CMake was not compiles with SSL support. The "Unsupported protocol" message indicate that CMake can not communicate via "https".
The solution is to use a compiled version of CMake which supports SSL. If you compile CMake yourself, simply reconfigure CMake with the "CMAKE_USE_OPENSSL option enabled.

**Comment by aradhyamathur** [comment]
I ran into similar issue. When I enabled CMAKE_USE_OPENSSL it showed that this flag is not used and upon make leads to the similar unsupported protocol error.
`
 make -j 4
[  2%] Generating /home/thor/soft/SimpleElastix/build/ExternalData/.ExternalSource/lua-5.1.5.tar.gz
[  2%] Generating /home/thor/soft/SimpleElastix/build/ExternalData/.ExternalSource/pcre-8.40.tar.gz
[  3%] Performing configure step for 'ITK'
[  5%] Generating /home/thor/soft/SimpleElastix/build/ExternalData/.ExternalSource/swig-3.0.12.tar.gz
Not searching for unused variables given on the command line.
-- Fetching "https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/890c808122bd90f398e6bc40ec862102"
-- Fetching "https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/2e115fe26e435e33b0d5c022e4490567"
-- Fetching "https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=890c808122bd90f398e6bc40ec862102&algorithm=MD5"
-- Fetching "https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5"
-- Fetching "https://simpleitk.github.io/SimpleITKExternalData/MD5/890c808122bd90f398e6bc40ec862102"
-- Fetching "https://simpleitk.github.io/SimpleITKExternalData/MD5/2e115fe26e435e33b0d5c022e4490567"
-- Fetching "https://data.kitware.com:443/api/v1/file/hashsum/MD5/2e115fe26e435e33b0d5c022e4490567/download"
-- Fetching "https://data.kitware.com:443/api/v1/file/hashsum/MD5/890c808122bd90f398e6bc40ec862102/download"
-- Fetching "https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c"
-- Fetching "https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/890c808122bd90f398e6bc40ec862102"
-- Fetching "https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/2e115fe26e435e33b0d5c022e4490567"
-- Fetching "https://itk.org/files/ExternalData/MD5/890c808122bd90f398e6bc40ec862102"
-- Fetching "https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=82133dfa7bba75ff9ad98a7046be687c&algorithm=MD5"
-- Fetching "https://itk.org/files/ExternalData/MD5/2e115fe26e435e33b0d5c022e4490567"
CMake Error at /usr/local/share/cmake-3.15/Modules/ExternalData.cmake:1121 (message):
  

  Object MD5=2e115fe26e435e33b0d5c022e4490567 not found at:

    https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/2e115fe26e435e33b0d5c022e4490567/download ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")

CMake Error at /usr/local/share/cmake-3.15/Modules/ExternalData.cmake:1121 (message):
  

  Object MD5=890c808122bd90f398e6bc40ec862102 not found at:

    https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/890c808122bd90f398e6bc40ec862102 ("Unsupported protocol")
    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=890c808122bd90f398e6bc40ec862102&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/890c808122bd90f398e6bc40ec862102 ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/890c808122bd90f398e6bc40ec862102/download ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/890c808122bd90f398e6bc40ec862102 ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/890c808122bd90f398e6bc40ec862102 ("Unsupported protocol")


-- Fetching "https://simpleitk.github.io/SimpleITKExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c"

loading initial cache file /home/thor/soft/SimpleElastix/build/ITK-build/CMakeCacheInit.txt
CMakeFiles/SuperBuildSimpleITKSourceReal.dir/build.make:63: recipe for target 'ExternalData/.ExternalSource/lua-5.1.5.tar.gz-hash-stamp' failed
make[2]: *** [ExternalData/.ExternalSource/lua-5.1.5.tar.gz-hash-stamp] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/SuperBuildSimpleITKSourceReal.dir/build.make:70: recipe for target 'ExternalData/.ExternalSource/pcre-8.40.tar.gz-hash-stamp' failed
make[2]: *** [ExternalData/.ExternalSource/pcre-8.40.tar.gz-hash-stamp] Error 1
-- Fetching "https://data.kitware.com:443/api/v1/file/hashsum/MD5/82133dfa7bba75ff9ad98a7046be687c/download"
-- Fetching "https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/82133dfa7bba75ff9ad98a7046be687c"
-- Fetching "https://itk.org/files/ExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c"
CMake Error at /usr/local/share/cmake-3.15/Modules/ExternalData.cmake:1121 (message):
  

  Object MD5=82133dfa7bba75ff9ad98a7046be687c not found at:

    https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c ("Unsupported protocol")
    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=82133dfa7bba75ff9ad98a7046be687c&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c ("Unsupported protocol")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/82133dfa7bba75ff9ad98a7046be687c/download ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/82133dfa7bba75ff9ad98a7046be687c ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/82133dfa7bba75ff9ad98a7046be687c ("Unsupported protocol")


CMakeFiles/SuperBuildSimpleITKSourceReal.dir/build.make:77: recipe for target 'ExternalData/.ExternalSource/swig-3.0.12.tar.gz-hash-stamp' failed
make[2]: *** [ExternalData/.ExternalSource/swig-3.0.12.tar.gz-hash-stamp] Error 1
`
