### ISSUE TITLE
Segmentation fault when computing deformation field

### ISSUE THREAD

**Issue by DavidDreher** [SuperElastix/SimpleElastix#241]
Hey everyone,
I'm evaluating elastix for non-rigid image registration.
I got it compiled and ran the non-rigid example from the documentation.
When I try to output a deformation field I get a segmentation fault.

elastix is the elastixImageFilter from the docs example
I only want the b-spline deformation field, not the affine one.

    p = elastix.GetTransformParameterMap(1)
    transformix = sitk.TransformixImageFilter()
    transformix.ComputeDeformationFieldOn() 
    transformix.SetTransformParameterMap(p)
    transformix.Execute()

It then repeats the following a lot (>100 times):

     WARNING: The parameter "UseBinaryFormatForTransformationParameters", requested at entry number 0, does not exist at all.
    The default value "false" is used instead.

And then it simply crashes the python console:

    Segmentation fault (core dumped)

**Comment by kaspermarstal** [comment]
What happens if you use all parameter maps, e.g. `p = elastix.GetTransformParameterMap(1)`?

**Comment by kaspermarstal** [comment]
You set ComputeDeformationFieldOn() and then run Execute(). The deformation field will be saved to disk. At the moment there is no way of getting it back in python directly unfortunately.

To get separate deformation fields, you can run the affine registration and compute the deformation field, and then use the result image from that registration as your new moving image. This has the downside that the moving image is resampled twice, but I think this is the only way. good luck!

**Comment by DavidDreher** [comment]
1. Still I think the first use case should be handled more graceful than a seg fault.

2. There is no deformation field output. No file is created. I can see the transformation parameters being written to the current folder and when I set `ComputeSpatialJacobianOn()` I can see a file called `fullSpatialJacobian.nii` but there is no new file showing the deformation field.

3. For me at least the ideas of having python bindings is to use the results directly onward in python. Otherwise I can write files, issue terminal commands and read results. But working with large data sets makes these approaches too slow. So it would be great to have the functionality to get the results of the transformix command back in memory.

Thanks for your effort and support!

**Comment by kaspermarstal** [comment]
I completely agree with all your points.

For 1), this happens internally in elastix, not much we can do from this side. For 2), that is definitely error. Elastix recently gained the ability to output the deformation field directly to memory, maybe some of this work broke the writing of deformation field to disk. More work is probably required to address this (which would also address 3). For 3), I completely agree, that is why this library was created in the first place. However, I don't have time to fix this issue atm (at least not until after I finish my phd). If somebody wants to dive into it and make a PR, I am happy to provide guidance.

**Comment by kaspermarstal** [comment]
This was recently added to `SimpleTransformix`. Set `ComputeDeformationFieldOn()`, execute, and then call `GetDeformationField()` to retrieve the deformation field as an SimpleITK image.
