### ISSUE TITLE
Superbuild error

### ISSUE THREAD

**Issue by woutdenolf** [SuperElastix/SimpleElastix#242]
OS: Debian 8
Python: 2.7.9
cmake: 3.0.2
commit: 21cf70d526208a23c8d9349cb1a71f798f29a69a

Got this error after "make":
```
[ 22%] Built target ITK
[ 25%] Built target SuperBuildSimpleITKSourceReal
[ 25%] Built target SuperBuildSimpleITKSource
[ 48%] Built target virtualenv
[ 71%] Built target Elastix
make[2]: *** No rule to make target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-1', needed by 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-doc'.  Stop.
CMakeFiles/Makefile2:133: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried switching off documentation building without effect:
```
"-DBUILD_EXAMPLES:BOOL=OFF \
-DBUILD_DOCUMENTATION:BOOL=OFF \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DBUILD_TESTING:BOOL=OFF \
-DSimpleITK_USE_SYSTEM_VIRTUALENV:BOOL=OFF \
-DSimpleITK_USE_SYSTEM_ELASTIX:BOOL=OFF \
-DSimpleITK_USE_SYSTEM_ITK:BOOL=OFF \
-DPYTHON_EXECUTABLE:FILEPATH=$(python_bin) \
-DPYTHON_INCLUDE_DIR:PATH=$(python_include) \
-DPYTHON_LIBRARY:FILEPATH=$(python_lib) \
-DWRAP_DEFAULT:BOOL=OFF \
-DWRAP_PYTHON:BOOL=ON"
```

**Comment by woutdenolf** [comment]
That is the output from a single thread build (just typed "make" without any options). Actually it is the output after running it for the second time.

**Comment by kaspermarstal** [comment]
Mhm, okay. The `make[2]: ...` indicates that make was run with multiple threads though. Don't know how to make your system use only one make job then. Perhaps build again from scratch?

**Comment by kaspermarstal** [comment]
I think this naming is internal to CMake and not related to the SimpleITK version. I am sorry but I don't know why you see this error or what causes it. I have not seen it before myself.

**Comment by woutdenolf** [comment]
For future reference, this error was caused by this section in SuperBuild.cmake:
```
ExternalProject_Add_Step(${proj} doc
  COMMAND ${CMAKE_COMMAND}
      --build <BINARY_DIR>
      --target Documentation
  DEPENDEES configure
  EXCLUDE_FROM_MAIN 1
  LOG 1
)
```
"EXCLUDE_FROM_MAIN" was introduced in cmake 3.1 while I was used cmake 3.0.2 (debian 8).
