### ISSUE TITLE
Python wrapper installation

### ISSUE THREAD

**Issue by the4thchild** [SuperElastix/SimpleElastix#243]
I compiled the latest version on `master` (commit 665d65f5) without issue except for a small problem while trying to install the resulting Python wrapper. When I ran `python setup.py install`, I received this output:

```
running install
running bdist_egg
running egg_info
writing SimpleITK.egg-info/PKG-INFO
writing dependency_links to SimpleITK.egg-info/dependency_links.txt
writing top-level names to SimpleITK.egg-info/top_level.txt
reading manifest file 'SimpleITK.egg-info/SOURCES.txt'
writing manifest file 'SimpleITK.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
error: can't copy '/Users/david/src/build_se/SimpleITK-build/Wrapping/Python/Packaging/_SimpleITK.so': doesn't exist or not a regular file
```

I noticed that `_SimpleITK.so` existed but in the `Python` rather than the `Python/Packaging` folder, so I just copied the file to `Python/Packaging`. The wrapper installation completeled successfully on the next run.

Note that `_SimpleITK.so` also appears to be in the `Python` folder when I last built SimpleElastix from awhile back (commit 9dfa8cb7) and installed it without issue.

Could be similar to #235 , though I didn't run into any make errors.

**Comment by kaspermarstal** [comment]
Thanks for this report @the4thchild! Will investigate.

**Comment by kaspermarstal** [comment]
It is really weird because the two commits you mention is entirely unrelated to the python build process. On some machines the _SimpleITK.so just seems to be built in the Packaging folder but I have no idea why.

**Comment by kaspermarstal** [comment]
I am trying to reproduce, can you tell me what python distribution and version you were using when you encountered this error?

**Comment by the4thchild** [comment]
Thanks, @kaspermarstal ! I built it in an Anaconda environment with Python 3.6.7. The SimpleElastix commit numbers I mentioned are just for reference for when I built them (the most recent one from the latest on master, the last one from about a year ago, when I didn't encounter the error). Both times I built on Mac with a Python 3 from Anaconda (can't remember the exact versions for the build last year).

**Comment by kaspermarstal** [comment]
By now this bug is thoroughly confirmed by many users. It looks like it occurs when building with Python 3. I have not yet been able to figure out the underlying cause but if anyone know, help is very much appreciated!

**Comment by kaspermarstal** [comment]
The trick is to run `sudo python Packaging/setup.py install` in the `Wrapping/Python` directory, _not_  `sudo python setup.py install` in the `Wrapping/Python/Packaging` directory. Will update the documentation.

**Comment by markbuckup** [comment]
I'm running the installation on Ubuntu and have had everything work up until this last step. Even though I'm following your latest advice, when I return to my Jupyter Notebook and import the package, it isn't found. I've provided a screenshot of my performing the last step and me trying to import the package into my environment. Is the issue that it's writing to python2.7 and not python3.7? If so, how do I fix that?
<img width="1071" alt="Screen Shot 2020-07-30 at 14 52 21" src="https://user-images.githubusercontent.com/56090031/88962716-cfa5a480-d274-11ea-87c3-765604072989.png">
<img width="724" alt="Screen Shot 2020-07-30 at 14 55 20" src="https://user-images.githubusercontent.com/56090031/88962721-d0d6d180-d274-11ea-8cf3-3a48fee6f243.png">
