### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by wf-ai** [SuperElastix/SimpleElastix#244]
HI,good afternoon!
this error is occured when I cmake the source.
my environment: window10,cmake 3.13,vs2017,ITK 4.13,elastix 4.9

[Error messages]
CMake Error at Code/BasicFilters/src/CMakeLists.txt:14 (add_library):
  add_library cannot create target "SimpleITKBasicFilters1" because another
  target with the same name already exists.  The existing target is a static
  library created in source directory
  "E:/VC_Package/SimpleElastix_0.1/Source/Code/BasicFilters/src".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  Code/BasicFilters/src/CMakeLists.txt:189 (add_filter_library)

Help me,please!!!

**Comment by kaspermarstal** [comment]
Hi @wf-ai, I am not able to reproduce. The problem might have been introduced at the configuration stage. Try to delete the build folder and compile from scratch.

**Comment by wf-ai** [comment]
Hi, @kaspermarstal ,thank you for your reply.
Just as you say,this problem have been introduced at the configuration stage. Follow your advice,I deleted the build folder and compile from scratch,but The problem remains unresolved.
What shall I do next?

**Comment by kaspermarstal** [comment]
Are you using the latest version (i.e. tip of master)? Are you following the steps outlined on https://simpleelastix.readthedocs.io/GettingStarted.html?

**Comment by wf-ai** [comment]
Hi, @kaspermarstal ,thank you for your reply.
First,I used the latest version download from github (SimpleElastix-master.zip,2018/11/21).
Second,I followed the steps outlined on https://simpleelastix.readthedocs.io/GettingStarted.html?#compiling-on-windows
my environment: window10,cmake 3.13,vs2017,ITK 4.13,elastix 4.9
I compiled elastix and ITK successfully by using CMAKE,but I did not compile simpleelastix.
I am puzzled,What shall I do next?

**Comment by wf-ai** [comment]
[Error messages] as above:
CMake Error at Code/BasicFilters/src/CMakeLists.txt:14 (add_library):
  add_library cannot create target "SimpleITKBasicFilters1" because another
  target with the same name already exists.  The existing target is a static
  library created in source directory
  "E:/VC_Package/SE/Source/Code/BasicFilters/src".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  Code/BasicFilters/src/CMakeLists.txt:189 (add_filter_library)


Found PythonLibs: E:/Python36/libs/python36.lib (found version "3.6.3") 
Configuring incomplete, errors occurred!

**Comment by kaspermarstal** [comment]
Try to delete build folder and build from scratch.

**Comment by kaspermarstal** [comment]
I cannot reproduce this error. I am sorry, but don't know why you see this.

**Comment by feature-engineer** [comment]
I get this error as well, using the 1.1.0 tag.
