### ISSUE TITLE
how to make it run without too much output?

### ISSUE THREAD

**Issue by xyx251330415** [SuperElastix/SimpleElastix#245]
Hello! My code runs well and the result is good, but there are too many outputs when it runs. execute() prints a lot of running progress and the printing costs a lot of time. I don't need it. How to turn off the display of progress? Thank you very much.
This is the running time display:
`171	-1.922113	24.180223	16.632889	0.002153	1.8
172	-1.922872	24.164007	16.638861	0.002698	1.8
173	-1.937961	24.147804	16.644833	0.003536	2.3
174	-1.934966	24.136878	16.648862	0.004609	1.8
175	-1.933324	25.136878	16.288004	0.002196	2.0
176	-1.944629	26.136878	15.942457	0.004689	1.9
177	-1.923098	27.136878	15.611267	0.001724	1.9
178	-1.941192	28.136878	15.293557	0.002432	1.9
179	-1.911176	29.136878	14.988521	0.002334	1.9
180	-1.956031	30.136878	14.695415	0.001917	1.9
181	-1.939475	30.758073	14.519042	0.002681	2.0
182	-1.925557	30.954148	14.464247	0.003649	2.0
183	-1.939949	30.937932	14.468763	0.003187	1.7
184	-1.944396	30.921716	14.473282	0.003461	2.0
185	-1.886033	31.921716	14.199797	0.003167	2.0
186	-1.938048	32.921716	13.936456	0.003088	2.0
187	-1.929551	32.905501	13.940649	0.003050	1.9
188	-1.940260	32.889285	13.944844	0.001689	1.9
189	-1.908108	32.873069	13.949041	0.004701	1.6
190	-1.926963	32.856853	13.953241	0.001405	1.7
191	-1.942439	33.856853	13.698884	0.002335	1.9
192	-1.918033	34.856812	13.453644	0.006507	5.1
193	-1.930645	34.840597	13.457550	0.002462	1.9
194	-1.926224	35.840597	13.220791	0.001651	2.0
195	-1.907996	35.824381	13.224564	0.002955	1.8
196	-1.910022	36.824375	12.995863	0.004126	2.1
197	-1.904000	37.824375	12.774936	0.001835	2.8
198	-1.920707	38.824375	12.561396	0.003306	5.1
199	-1.915886	39.824375	12.354877	0.002408	1.8
200	-1.953615	39.808159	12.358171	0.001994	2.2
201	-1.948978	39.791943	12.361468	0.003033	2.9
202	-1.925903	40.791943	12.161418	0.002861	2.6
203	-1.919252	40.775727	12.164610	0.003211	2.6
204	-1.941318	41.775727	11.970831	0.005300	2.9
205	-1.921221	42.775727	11.783129	0.003013	3.3
206	-1.923749	42.759511	11.786126	0.002730	2.7
207	-1.955807	43.759511	11.604128	0.004309	2.6
208	-1.915765	43.743301	11.607033	0.004019	2.0
209	-1.938787	44.743301	11.430482	0.002196	2.0
210	-1.931351	44.727085	11.433302	0.002844	2.4
211	-1.923994	45.727085	11.261958	0.001315	3.6
212	-1.957565	46.727082	11.095674	0.002387	1.9
213	-1.919222	46.710867	11.098332	0.001195	1.8
214	-1.911404	47.710866	10.936809	0.002030	2.3
215	-1.952193	47.694651	10.939391	0.001919	2.9
216	-1.920624	48.020735	10.887709	0.003548	2.8
217	-1.938142	48.004519	10.890267	0.002875	2.9
218	-1.922910	49.004171	10.734755	0.002806	2.8
219	-1.902364	50.004171	10.583571	0.002706	2.8
220	-1.937950	51.004171	10.436585	0.000910	2.2
221	-1.942797	50.987955	10.438936	0.002947	2.2
222	-1.932278	51.938654	10.302872	0.000982	2.1
223	-1.916502	52.938654	10.163529	0.002185	2.1
224	-1.914211	52.927870	10.165011	0.002046	2.2
225	-1.916806	53.927865	10.029348	0.002838	2.0
226	-1.947586	54.927865	9.897258	0.001569	3.9
227	-1.910027	55.927865	9.768601	0.003151	2.8
228	-1.951812	56.896468	9.647134	0.003948	2.9
229	-1.977067	56.880253	9.649142	0.001684	2.8
230	-1.932415	56.864037	9.651152	0.002021	2.8
231	-1.922261	57.802110	9.536263	0.003083	2.7
232	-1.923601	57.785894	9.538226	0.002563	2.3
233	-1.929081	58.771070	9.420428	0.002788	2.1
234	-1.956077	59.771066	9.303798	0.001944	2.3
235	-1.940570	59.754851	9.305666	0.001377	2.1
236	-1.923622	60.698594	9.198171	0.005057	1.9
237	-1.956979	61.698594	9.086946	0.002168	2.1
238	-1.945393	61.682378	9.088728	0.002870	1.9
239	-1.922749	61.666162	9.090511	0.003448	2.9
240	-1.952073	62.666162	8.981859	0.002831	1.9
241	-1.891728	63.666162	8.875773	0.003588	1.9
242	-1.926607	64.666162	8.772164	0.003598	1.9
243	-1.932601	64.660570	8.772737	0.001412	1.9
244	-1.926341	65.660570	8.671506	0.000788	3.7
245	-1.949489	65.644480	8.673116	0.003278	1.8
246	-1.947424	66.390514	8.599076	0.001948	1.8
247	-1.921318	66.374298	8.600672	0.001352	2.0
248	-1.930244	67.374289	8.503352	0.002019	1.9
249	-1.948328	67.358073	8.504912	0.000399	1.8
250	-1.918794	67.353200	8.505381	0.004417	1.7
251	-1.949840	67.338154	8.506830	0.001772	1.8
252	-1.947869	67.321938	8.508392	0.001325	1.7
253	-1.922525	67.305723	8.509954	0.001564	1.7
254	-1.923166	67.289507	8.511517	0.003343	1.7
255	-1.928027	67.273406	8.513070	0.001637	1.7
Time spent in resolution 0 (ITK initialization and iterating): 0.672 s.
Stopping condition: Maximum number of iterations has been reached.
Settings of AdaptiveStochasticGradientDescent in resolution 0:
( SP_a 751.477647 )
( SP_A 20.000000 )
( SP_alpha 1.000000 )
( SigmoidMax 1.000000 )
( SigmoidMin -0.016216 )
( SigmoidScale 0.000000 )`

**Comment by kaspermarstal** [comment]
Have you tried `elastixImageFilter.LogToConsoleOff()`? Or do you see this output even when having turned off logging to console?

**Comment by xyx251330415** [comment]
@kaspermarstal Thank you very much! It works!
