### ISSUE TITLE
correct way to apply multiple transforms to a new image?

### ISSUE THREAD

**Issue by tiaplautz** [SuperElastix/SimpleElastix#251]
Hello,

I am wondering, what is the correct way to apply a sequence of transforms?

To clarify, I have applied rigid-->affine-->bslpline transformations to an image. I would now like to apply this transform to a new image, however the transform parameters are saved in 3 different txt files, and  likewise:

transformParameterMapVector = elastixImageFilter.GetTransformParameterMap()

Am I just supposed to write a loop to apply the 3 transforms in order? Or is there a more elegant intended solution?

Thanks very much!

**Comment by kaspermarstal** [comment]
You can just supply `transformParameterMapVector` to transformix:

    transformedNewImage = sitk.Transformix(newImage, transformParameterMapVector)

Transformix will handle composition of the transforms.

**Comment by tiaplautz** [comment]
Ah, how simple. Thank you! 

One more question -- In order to transform a binary mask, I know I must set the parameter "FinalBSplineInterpolationOrder" = 0. Of course I can accomplish this in a for loop but is there a better way to do this? Perhaps a way that does not permanently change the value in the TransformParameterMapVector?

Best Regards, and my apologies for the very simplistic questions!

**Comment by kaspermarstal** [comment]
No problem! 

You can use `ElastixImageFilter.SetParameter('FinalBSplineInterpolationOrder', 0)` or `TransformixImageFilter.SetParameter('FinalBSplineInterpolationOrder', 0)` to apply the change the change to all parameter maps. If you have a "naked" vector of parameter maps (i.e. outside of either `ElastixImageFilter` or `TransformixImageFilter` as in you example above) you have to use a for loop. 

All these commands will change the value permanently however. You can make a deep copy perhaps.

**Comment by kaspermarstal** [comment]
Feel free to reopen if you have further questions.
