### ISSUE TITLE
How to customize optimizer parameters?

### ISSUE THREAD

**Issue by tiaplautz** [SuperElastix/SimpleElastix#258]
Hello, I am trying to do a Translation followed by a Bspline registration with the parameter map:

p=sitk.ParameterMap()

##Multi Resolution
p['Registration'] = ['MultiResolutionRegistration']
p['FixedImagePyramid'] = ['FixedSmoothingImagePyramid']
p['MovingImagePyramid'] = ['MovingSmoothingImagePyramid']
p['Interpolator'] = ['LinearInterpolator']
p['ResampleInterpolator'] = ['FinalBSplineInterpolator']
p['Resampler'] = ['DefaultResampler']

p['Metric'] = ['AdvancedMattesMutualInformation']
p['Optimizer'] = ['AdaptiveStochasticGradientDescent']
p['Transform'] = ['BSplineTransform']

p['NumberOfResolutions'] = ['3']

#p['ImagePyramidSchedule'] = ['4', '4', '2', '2', '2', '1', '1', '1', '1']
#p['FinalGridSpacingInVoxels'] = ['8.0', '8.0', '2.0']
#p['GridSpacingSchedule'] = ['4.0' '4.0' '2.0' '2.0' '2.0' '1.0' '1.0' '1.0' '1.0' ]

##Sampling
p['ImageSampler'] = ['RandomCoordinate']
p['NewSamplesEveryIteration'] = ["true", 'true', 'true']
p['NumberOfSpatialSamples'] = ['10000', '10000', '20000']

p['NumberOfHistogramBins'] = ['32', '32', '32'] #for Matte's Mutual Information
p['BSplineInterpolationOrder'] = ['1', '1', '1']
p['FinalBSplineInterpolationOrder'] = ['3']
p['DefaultPixelValue'] = ['-1000']

p['MaximumNumberOfIterations'] = ['2000']

##Output
p['WriteTransformParametersEachIteration'] = ["false", "false", "false"]
p['WriteTransformParametersEachResolution'] = ["true",  "true", "true"]
p['ShowExactMetricValue'] = ["false", 'false', 'false']
p['WriteResultImageAfterEachResolution'] = ["false"]

p['SP_a'] = ['10000.0' '10000.0' '10000.0']

The code I am using to perform the registration is:

elastixImageFilter.SetFixedImage(fixedImg)
elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(fixedImg)
elastixImageFilter.SetMovingImage(movingImgMatched)
​
​
parameterMapVector = sitk.VectorOfParameterMap()
parameterMapVector.append(sitk.GetDefaultParameterMap('rigid'))
parameterMapVector.append(p)
elastixImageFilter.SetParameterMap(parameterMapVector)
​
elastixImageFilter.Execute()

The problem is that it does not seem to be allowing me to specify the optimizer parameter SP_a and instead just uses default values. Can you tell me how to do this correctly? or perhaps point out what I am doing wrong?

Kindest Regards,
Tia

**Comment by kaspermarstal** [comment]
Do get out the same registration results regardless of the SP_a parameters you use? 

Elastix is originally a command-line program, and the messages you see about default values is because of missing command line parameters. I suspect your custom values are indeed used even though the output tells you otherwise. I guess you can confirm this if you get different results for different values of SP_a.

**Comment by tiaplautz** [comment]
Yes I get the same registration results regardless of output parameters. For example I did 3 different registrations with SP_a differing by an order of magnitude and the resulting transformed image was identical in every case.

It seems to allow me to set SP_A to whatever I prefer, but it selects its own values for SP_a and SP_alpha.  For SP_alpha it always chooses (SP_alpha 1.0 1.0 1.0)
It varies SP_a at each resolution choosing (SP_a 7970.901577 19460.362537 57645.365788) no matter what I tell it to set these values to.

**Comment by kaspermarstal** [comment]
@stefanklein do you know if this is intended behaviour?

**Comment by stefanklein** [comment]
Hi, yes, if you want to overrule the automatic step size parameters there are two methods:
1) Add (AutomaticParameterEstimation "false" ), then the SP_a parameter becomes available, and also SP_A, SP_alpha, and a few more, see: http://elastix.isi.uu.nl/doxygen/classelastix_1_1AdaptiveStochasticGradientDescent.html
2) If you just want to tune the maximum step length, then leave AutomaticParameterEstimation to its default "true"  setting, and set (MaximumStepLength <value>) to the value you like.
I would recommend the second option!
Best, Stefan
