### ISSUE TITLE
Building with OpenCL 

### ISSUE THREAD

**Issue by mavanb** [SuperElastix/SimpleElastix#260]
I am not able to build SimpleElastix with OpenCL. When I try to use any CL parameters I get: 

itk::ExceptionObject (0x5568d8d58740)
Location: "unknown" 
File: /home/mart/build_opencl/Elastix/Core/Kernel/elxElastixMain.cxx
Line: 819
Description: itk::ERROR: ElastixMain(0x5568d8561bd0): The following component could not be created: OpenCLResampler

I am trying to follow the steps of @cipri-tom: 
 - `git checkout opencl`
 - `mkdir build_opencl && cd build_opencl`
 - `ccmake ../SuperBuild/` and toggle the OpenCL setting (need to press `t` to show it); optionally also `OpenMP`
 - install openCL: on Ubuntu, `sudo apt install ocl-icd-opencl-dev`
 - `make -j4`
 - search for `OpenCL` [here](http://elastix.isi.uu.nl/doxygen/parameter.html) to see available parameters that can use OpenCL and replace them in the parameter map.
_Originally posted by @cipri-tom in https://github.com/SuperElastix/SimpleElastix/issues/145#issuecomment-416516974_

Problems: 
* The opencl branch does no longer exists (I assume that it has been merged in the master). 
* `ccmake ../SuperBuild/` does not show any OpenCL options.

OpenCL seems to work fine, as I can run the test provide [here](https://wiki.tiker.net/OpenCLHowTo)

**Comment by kaspermarstal** [comment]
The OpenCL features made the build unstable even for users who did not need OpenCL. We decided to treat this as an advanced use case and not support it out of the box. The OpenCL branch was removed to reduce the burden of maintaining two separate builds.

If you need OpenCL you can compile elastix as a standalone project and then pass -DUSE_SYSTEM_ELASTIX=ON and -DELASTIX_DIR=/path/to/elastix/build/dir the SuperBuild when compiling SimpleElastix.

(We talked on Skype, posting this information in case other users have problems with OpenCL and end up here)
