### ISSUE TITLE
How to use the “TransformParameters” to drive label images deformation?

### ISSUE THREAD

**Issue by oasis-github** [SuperElastix/SimpleElastix#269]
Thanks for your sharing!
I am new to  the superElastix, I have successfully run the b-spline registration and obtained the “TransformParameters.0.txt” and the resulting image. Now I want to use the “TransformParameters.0.txt” to drive  label images deformation, but I did not find out how to implement this process in the "SimpleElastix Documentation".
Can you provide examples or a more detailed "SimpleElastix Software Guide"? thank you very much！

**Comment by kaspermarstal** [comment]
The example in the README on the front page of this repository shows you how to use transformix to warp a label image. But I agree that this is lacking from the documentation. Will add it.

**Comment by oasis-github** [comment]
I found this example, thank you very much for your sharing and help.
