### ISSUE TITLE
How to run multiple registration processes on the same images 

### ISSUE THREAD

**Issue by Wafamah** [SuperElastix/SimpleElastix#276]
Hi everyone,

I'm trying to register two images I want to apply affine and mean squares advances first then Bspline and mean squares advances.

I'm using cmd as attached. I read a suggestion on the guideline saying (Running multiple registrations in succession, each possibly of a different type, and with the output of a
previous registration as input to the next, can be done with elastix in several ways. The first one is to run
elastix once with the first registration, and use its output (the TransformParameter.0.txt that can be
found in the output directory) as input for a new run of elastix with the command line argument -t0. So:
elastix -f ... -m ... -out out1 -p param1.txt
elastix -f ... -m ... -out out2 -p param2.txt -t0 out1/TransformParameters.0.txt
elastix -f ... -m ... -out out3 -p param3.txt -t0 out2/TransformParameters.0.txt
and so on. Another possibility is combine the registrations with one run of elastix:
elastix ... -p param1.txt -p param2.txt -p param3.txt) 

in CMD i wrote :+1: 

C:\"Program FIles"\Elastix\elastix ^
-f C:\Users\Wadha\Documents\Elastix_IN\147by149_MRI.nii ^
-m C:\Users\Wadha\Documents\Elastix_IN\copypastehisto147_149.nii ^
-out C:\Users\Wadha\Documents\Elastix_OUT ^
**_-p C:\Users\Wadha\Documents\Elastix_PARS\parameters_Affine_MSD.txt_**

-f C:\Users\Wadha\Documents\Elastix_IN\147by149_MRI.nii ^
-m C:\Users\Wadha\Documents\Elastix_IN\copypastehisto147_149.nii ^
-out C:\Users\Wadha\Documents\Elastix_OUT ^
### _-p C:\Users\Wadha\Documents\Elastix_PARS\parameters_BSplineAMS.txt_
-t0 C:\Users\Wadha\Documents\Elastix_OUT\TransformParameters.0.txt 

Can Any one help me to figure what I have done wrong ? 

Thanks,

**Comment by kaspermarstal** [comment]
What is the error message?

Also this probably belongs at http://github.com/SuperElastix/elastix

**Comment by Wafamah** [comment]
I didn't receive error message. When I opened elastix.log, I got these info : 
ELASTIX version: 4.900
Command line options from ElastixBase:
-f        C:\Users\Wadha\Documents\Elastix_IN\147by149_MRI.nii
-m        C:\Users\Wadha\Documents\Elastix_IN\copypastehisto147_149.nii
-fMask    unspecified, so no fixed mask used
-mMask    unspecified, so no moving mask used
-out      C:\Users\Wadha\Documents\Elastix_OUT\
-p        C:\Users\Wadha\Documents\Elastix_PARS\parameters_Affine_MSD.txt
-priority unspecified, so NORMAL process priority
-threads  unspecified, so all available threads are used
Command line options from TransformBase:
**-t0       unspecified, so no initial transform used**

So I believe Elastix just activate one parameter file and ignore the another one. 

I don't know how to run two parameters files at the same time on the same images. Any suggestion?

**Comment by kaspermarstal** [comment]
What does the registration result show? Do you get the expected output? Or do you get output that confirms that t0 was ignored? Also, to get help from people more familiar with the command line interface, you could consider posting this at http://github.com/SuperElastix/elastix. If this is indeed a bug in elastix this also where it should be reported.
