### ISSUE TITLE
3D image registration malfunction

### ISSUE THREAD

**Issue by Grainger-Sasso** [SuperElastix/SimpleElastix#279]
Greetings,

I have had some issues recently getting SimpleElastix to register 3D images. I have successfully registered 2D test images that have been rotated and translated slightly. However, I am getting some strange outputs when I try to register 3D brain images onto itself.

Here is the image of the brain
[Brain_Slices.zip](https://github.com/SuperElastix/SimpleElastix/files/2963613/Brain_Slices.zip)

Here is the code that is being run
```py
import SimpleITK as sitk
from os.path import join, dirname

root = dirname(__file__)
filename = join(root,'Brain_Slices.tiff')

fix_image =  sitk.ReadImage(filename)
mov_image = sitk.ReadImage(filename)

simpleElastix = sitk.ElastixImageFilter()
simpleElastix.SetFixedImage(fixImage)
simpleElastix.SetMovingImage(movingImage)
simpleElastix.SetParameterMap(sitk.GetDefaultParameterMap('rigid'))
simpleElastix.Execute()

img = simpleElastix.GetResultImage()
sitk.Show(img, title='Result', debugOn=True)
```

Here is what the output looks like
![Screenshot](https://user-images.githubusercontent.com/35379929/54313963-cbf67c80-45b0-11e9-8970-330c9c43638a.png)

I have tried several iterations with varying parameter maps and I would like some guidance as to why this simple registration example fails to produce an image that I would expect to see. Thank you

**Comment by Grainger-Sasso** [comment]
The output is displayed in Fiji

**Comment by kaspermarstal** [comment]
It looks like Fiji is clamping intensities or that you need to adjust the intensity range with which the image is displaued. Try to display the image with anpther viewer, e.g. ITK-SNAP, or use the sitk.RescaleIntensity() function prior to displaying the image with Fiji.

**Comment by Grainger-Sasso** [comment]
Thank you for getting back to me on this issue. 

So I took your suggestion and here is the updated code:

```python
import SimpleITK as sitk
from os.path import join, dirname

root = dirname(__file__)
 filename = join(root,'Brain_Slices.tiff')

fix_image = sitk.ReadImage(filename)
mov_image = sitk.ReadImage(filename)

simpleElastix = sitk.ElastixImageFilter()
simpleElastix.SetFixedImage(fix_image)
simpleElastix.SetMovingImage(mov_image)
simpleElastix.SetParameterMap(sitk.GetDefaultParameterMap('rigid'))
simpleElastix.Execute()

img = simpleElastix.GetResultImage()

img = sitk.RescaleIntensity(img)

sitk.Show(img, title='Result', debugOn=True)
sitk.Show(fix_image, title='Fixed', debugOn=True)
sitk.Show(mov_image, title='Moving', debugOn=True)
```
Here is the result in Fiji :

![image](https://user-images.githubusercontent.com/35379929/56318297-e6ca8c80-612c-11e9-8559-ddf6034a42fc.png)

As you can see, rescaling the intensities did not make much of an impact on the problem.

A potentially relevant detail came to light when reviewing this issue on my end. So I ran the same code for the original image files stored on my computer (pixel type of 16-bit unsigned integer) and for the files that were posted in the original issue which I downloaded, the Brain_Slices.zip (pixel type of 32-bit float).

The code that I attached above fails for the files that I have stored on my computer as you can see above. However, the very same code works just fine on the images I posted in the zip file. 

Here is the result in Fiji for the posted files:

![image](https://user-images.githubusercontent.com/35379929/56320937-4fb50300-6133-11e9-982a-42ba1f593578.png)

That may be relevant information to help diagnose the issue.

Thanks again!

**Comment by PertuyF** [comment]
@Grainger-Sasso can you try to manually adjust `Brightness/Contrast` in Fiji?

**Comment by Grainger-Sasso** [comment]
Thank you, @PertuyF !! This seems to have resolved the issue completely. Increasing the minimum brightness setting in `Brightness/Contrast` in ImageJ allowed the image to come into view. The image is now completely clear. Also, thanks @kaspermarstal for the input as well. We believe that the image may have had some pixels of a very high intensity that prevented the rescaling function from working effectively.
