### ISSUE TITLE
Error while setting SetFixedMask

### ISSUE THREAD

**Issue by farhanone** [SuperElastix/SimpleElastix#284]
Hi,

There is the error:

>     return _SimpleITK.ElastixImageFilter_Execute(self)
>     RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /media/farhan/Volume/Project/SimpleElastix/src/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:133:
>     sitk::ERROR: Fixed masks must have same direction cosines as fixed images (fixed image at index 0 has direction cosine [ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ], fixed mask at index 0 has direction cosine "[ 0.999979, 2.21315e-10, 0.00648954, -0.000825654, 0.991873, 0.127226, -0.0064368, -0.127228, 0.991853 ]").

With code

`elastixImageFilter = sitk.ElastixImageFilter() elastixImageFilter.SetFixedImage(sitk.ReadImage(targetImage)) elastixImageFilter.SetMovingImage(sitk.ReadImage(movingImage)) elastixImageFilter.SetFixedMask(sitk.ReadImage(fixedMask)) #elastixImageFilter.SetMovingMask(sitk.ReadImage(movingMask)) elastixImageFilter.SetParameterMap(sitk.GetDefaultParameterMap("affine")) elastixImageFilter.Execute() sitk.WriteImage(elastixImageFilter.GetResultImage(), path)`

it says direction cosines must be the same for fixed image and fixed mask, but these are the same indeed.
thanks in advance

**Comment by kaspermarstal** [comment]
The directions probably differ on decimals smaller that what is printed. You can use `fixedMask.CopyInformation(targetImage)` to make sure they are identical. This is a bit of a hack but it will solve you problem.

**Comment by farhanone** [comment]
It worked. Thanks again

**Comment by MSC19950601** [comment]
However, I get ERROR "Description: itk::ERROR: ImageGridSampler(0x55a92eb4df60): ERROR: the bounding box of the mask lies entirely out of the InputImageRegion!".
