### ISSUE TITLE
I get WriteTransform error

### ISSUE THREAD

**Issue by youngminpark2559** [SuperElastix/SimpleElastix#285]
Hi, I'm new to image registration and SimpleITK, Elastix, and SimpleElastix.  

I'm trying to test following example code  
https://github.com/SuperElastix/SimpleElastix/blob/master/Examples/ImageRegistrationMethod2/ImageRegistrationMethod2.py

My question is
1. I wonder fixedImageFilter was supposed to be fixedImageFile from following line?
https://github.com/SuperElastix/SimpleElastix/blob/master/Examples/ImageRegistrationMethod2/ImageRegistrationMethod2.py#L37

2. fixedImageFile and movingImageFile make sense in their meaning but I don't know what outputTransformFile means

3. When I use following running command
```
python temp.py \
"/home/young/Downloads/BrainProtonDensity.png" \
"/home/young/Downloads/BrainProtonDensityTranslated13x17y.png" \
"png"
```

I get following error around the code which uses `outputTransformFile`
```
Traceback (most recent call last):
  File "temp.py", line 77, in <module>
    sitk.WriteTransform(outTx,sys.argv[3])
  File "/home/young/SimpleElastix/build/SimpleITK-build/Wrapping/Python/SimpleITK.py", line 5306, in WriteTransform
    return _SimpleITK.WriteTransform(transform, filename)
RuntimeError: Exception thrown in SimpleITK WriteTransform: /home/young/SimpleElastix/build/ITK/Modules/IO/TransformBase/include/itkTransformFileWriter.hxx:167:
itk::ERROR: TransformFileWriterTemplate(0x27ff8e0): Could not create Transform IO object for writing file png
  Tried to create one of the following:
    HDF5TransformIOTemplate
    HDF5TransformIOTemplate
    MatlabTransformIOTemplate
    MatlabTransformIOTemplate
    TxtTransformIOTemplate
    TxtTransformIOTemplate
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.
```

**Comment by kaspermarstal** [comment]
This is a SimpleITK method, not SimpleElastix. I get that it can be confusing to figure out what is what. 

Do you want to use the SimpleElastix registration method? Then take look at https://github.com/SuperElastix/SimpleElastix/blob/master/Examples/Python/SimpleElastix.py. 

Do you want to use the SimpleITK registration method? Then use e.g. "outputTransformFile.hdf5" instead of "png" as the last argument.

**Comment by youngminpark2559** [comment]
Thanks. It helps a lot.
