### ISSUE TITLE
Compile Java in MacOS, will that work on other OSs?

### ISSUE THREAD

**Issue by ctr26** [SuperElastix/SimpleElastix#291]
Hi all,

If I compile elastix as java on Mac OS will that built package work on other OSs

Best

Craig

**Comment by kaspermarstal** [comment]
Hi Craig,

Unfortunately not. The project will be compiled as native code which Java calls through JNI. The native code will not work on other platforms. 

Take a look at our CI setup if you wish to compile the project for many platforms.

Kasper
