### ISSUE TITLE
RayCastInterpolator(index 2) - This component is not installed!

### ISSUE THREAD

**Issue by Hurley-Evil** [SuperElastix/SimpleElastix#297]
I want to use SimpleElastix to 2d/3d registration.
I refer to the website "http://elastix.bigr.nl/wiki/index.php/Par0013" and write the following code. 
fixed = sitk.ReadImage("../Data_Par0013/xrayimage1.mhd", sitk.sitkFloat32)
mask = sitk.ReadImage("../Data_Par0013/xrayMask1.mhd", sitk.sitkUInt8)
moving = sitk.ReadImage("../Data_Par0013/volumeData.mhd", sitk.sitkFloat32)

parameterMap = sitk.ParameterMap()
parameterMap['FixedInternalImagePixelType'] = ["float"]
parameterMap['MovingInternalImagePixelType'] = ["float"]
parameterMap['FixedImageDimension'] = ['3']
parameterMap['MovingImageDimension'] = ['3']
parameterMap['UseDirectionCosines'] = ["false"]
parameterMap['Registration'] = ["MultiResolutionRegistration"]
parameterMap['Interpolator'] = ["RayCastInterpolator"]
parameterMap['ResampleInterpolator'] = ["FinalRayCastInterpolator"]
parameterMap['Resampler'] = ["DefaultResampler"]
parameterMap['FixedImagePyramid'] = ["FixedRecursiveImagePyramid"]
parameterMap['MovingImagePyramid'] = ["MovingRecursiveImagePyramid"]

parameterMap['Optimizer'] = ["Powell"]
parameterMap['Transform'] = ["EulerTransform"]
parameterMap['Metric'] = ["NormalizedGradientCorrelation"]

# ***************** Transformation **************************

parameterMap['Scales'] = ['57.3']
parameterMap['AutomaticTransformInitialization'] = ["false"]
parameterMap['HowToCombineTransforms'] = ["Compose"]
parameterMap['CenterOfRotationPoint'] = ['0.0 0.0 0.0']

# ******************* Similarity measure *********************

parameterMap['UseNormalization'] = ["true"]

# ******************** Multiresolution **********************

parameterMap['NumberOfResolutions'] = ['1']

# ******************* Optimizer ****************************

parameterMap['MaximumNumberOfIterations'] = ['10']
parameterMap['MaximumStepLength'] = ['1.0']
parameterMap['StepTolerance'] = ['0.0001']
parameterMap['ValueTolerance'] = ['0.000001']

# **************** Image sampling **********************

parameterMap['ImageSampler'] = ["Full"]
parameterMap['NewSamplesEveryIteration'] = ["false"]

# ************* Interpolation and Resampling ****************

parameterMap['Origin'] = ['-145.498 -146.889 381.766']

parameterMap['Interpolator0PreParameters'] = ['-0.009475 -0.006807 -0.030067 0.0 0.0 0.0']
parameterMap['ResampleInterpolator0PreParameters'] = ['-0.009475 -0.006807 -0.030067 0.0 0.0 0.0']

parameterMap['Interpolator0FocalPoint'] = ['0.54 -0.85 -813.234']
parameterMap['ResampleInterpolator0FocalPoint'] = ['0.54 -0.85 -813.234']

parameterMap['Threshold'] = ['1000']

parameterMap['DefaultPixelValue'] = ['0']

parameterMap['WriteResultImage'] = ["true"]
parameterMap['WriteTransformParametersEachIteration'] = ["true"]

parameterMap['ResultImagePixelType'] = ["float"]
parameterMap['ResultImageFormat'] = ["mhd"]

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(fixed)
elastixImageFilter.SetFixedMask(mask)
elastixImageFilter.SetMovingImage(moving)

parameterMapVector = sitk.VectorOfParameterMap()
parameterMapVector.append(parameterMap)
elastixImageFilter.SetParameterMap(parameterMapVector)

elastixImageFilter.Execute()

But it doesn't work! @kaspermarstal

**Comment by Hurley-Evil** [comment]
Installing all components.
InstallingComponents was successful.

Error: 
Full(index 2) - This component is not installed!
ERROR: error occurred while creating ImageSampler 0.

itk::ExceptionObject (0x7fe5b551a870)
Location: "unknown" 
File: /Users/hurley/Registration/NewBuild/Elastix/Core/Kernel/elxElastixMain.cxx
Line: 819
Description: itk::ERROR: ElastixMain(0x7fe5b550c400): The following component could not be created: Full


Error: 
RayCastInterpolator(index 2) - This component is not installed!
ERROR: error occurred while creating Interpolator 0.

itk::ExceptionObject (0x7fe5b551a940)
Location: "unknown" 
File: /Users/hurley/Registration/NewBuild/Elastix/Core/Kernel/elxElastixMain.cxx
Line: 819
Description: itk::ERROR: ElastixMain(0x7fe5b550c400): The following component could not be created: RayCastInterpolator


Error: 
Powell(index 2) - This component is not installed!
ERROR: error occurred while creating Optimizer 0.

itk::ExceptionObject (0x7fe5b5389f80)
Location: "unknown" 
File: /Users/hurley/Registration/NewBuild/Elastix/Core/Kernel/elxElastixMain.cxx
Line: 819
Description: itk::ERROR: ElastixMain(0x7fe5b550c400): The following component could not be created: Powell


Error: 
FinalRayCastInterpolator(index 2) - This component is not installed!
ERROR: error occurred while creating ResampleInterpolator 0.

itk::ExceptionObject (0x7fe5b539cc80)
Location: "unknown" 
File: /Users/hurley/Registration/NewBuild/Elastix/Core/Kernel/elxElastixMain.cxx
Line: 819
Description: itk::ERROR: ElastixMain(0x7fe5b550c400): The following component could not be created: FinalRayCastInterpolator


ERROR:
One or more components could not be created.
Traceback (most recent call last):
  File "/Users/hurley/Registration/Code/Powell_GD_singleImage.py", line 82, in <module>
    elastixImageFilter.Execute()
  File "/usr/local/lib/python3.7/site-packages/SimpleITK-1.2.0rc2.dev1162+g2a79d-py3.7-macosx-10.14-x86_64.egg/SimpleITK/SimpleITK.py", line 10996, in Execute
    return _SimpleITK.ElastixImageFilter_Execute(self)
RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /Users/hurley/Registration/SimpleElastix/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (0x7fe5b5517d30)
Location: "unknown" 
File: /Users/hurley/Registration/NewBuild/Elastix/Core/Main/elxElastixFilter.hxx
Line: 253
Description: itk::ERROR: Self(0x7fe5b52f9b80): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

**Comment by kaspermarstal** [comment]
Hi @Hurley-Evil, some very technical issues prevents SimpleElastix from doing 2D/3D registration. SimpleElastix can only handle 2D/2D, 3D/3D or 4D/4D. For 2D/3D you have to use elastix directly.

**Comment by Hurley-Evil** [comment]
ok
