### ISSUE TITLE
Is it possible to work with simpleElastix with anaconda or an anaconda virtual enviroment? 

### ISSUE THREAD

**Issue by josemanuel097** [SuperElastix/SimpleElastix#308]

**Comment by PertuyF** [comment]
Yes, compile SimpleElastix and `pip install ...` in your conda environment should work.

**Comment by josemanuel097** [comment]
May you be more explicit about the steps? I think is this what you mean..
after compiling:
$(my_conda_env) python Packaging/setup.py install
$(my_conda_env) pip install SimpleElastix 

Is this what you mean?

**Comment by PertuyF** [comment]
Can't help you more as its been a while since I last used SimpleElastix.
But you got the idea: when you perform whatever steps you need to install the software, do it from your target conda environment.

**Comment by josemanuel097** [comment]
this is what i tried but i did not work : 
$ pip install SimpleElastix
Collecting SimpleElastix
  ERROR: Could not find a version that satisfies the requirement SimpleElastix (from versions: 0.9.1.macosx-10.11-intel, 0.10.0.post224.macosx-10.6-x86_64)
ERROR: No matching distribution found for SimpleElastix

**Comment by PertuyF** [comment]
Then try something else. 
This error suggests there are only macosx versions available from PyPI. And that you likely don't use this OS.
You should compile the thing.

**Comment by timeanddoctor** [comment]
(base) C:\Users\1>pip install SimpleElastix
Collecting SimpleElastix
  Could not find a version that satisfies the requirement SimpleElastix (from versions: 0.9.1.macosx-10.11-intel, 0.10.0.post224.macosx-10.6-x86_64)
No matching distribution found for SimpleElastix
You are using pip version 19.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by timeanddoctor** [comment]
Who can share a setup file for pip after compile for windows...Thanks!

**Comment by PertuyF** [comment]
Used this way pip tries to install from PyPI.  What you're looking to do is install your locally compiled package. Either with pip or setup.py

**Comment by elainehoml** [comment]
@josemanuel097 not sure if you've solved this already, but I had the same problem - fixed by calling `pip install SimpleITK` from Anaconda command prompt.

**Comment by vlonge** [comment]
> Yes, compile SimpleElastix and `pip install ...` in your conda environment should work.

Close. What you need to do in your environment is: 
$(my_conda_env) pip install SimpleITK
$(my_conda_env)pip install SimpleITK-SimpleElastix

**Comment by vlonge** [comment]
> May you be more explicit about the steps? I think is this what you mean.. after compiling: $(my_conda_env) python Packaging/setup.py install $(my_conda_env) pip install SimpleElastix
> 
> Is this what you mean?

Close. What you need to do in your environment is:
$(my_conda_env) pip install SimpleITK
$(my_conda_env)pip install SimpleITK-SimpleElastix
