### ISSUE TITLE
The program 'python.exe' has exited with code -1 (0xffffffff).

### ISSUE THREAD

**Issue by Sattlert2** [SuperElastix/SimpleElastix#309]
Hello,

I am using simpleElastix in visual studio windows 10 64 bit. I keep running into this issue when the code is running and I receive the error: The program 'python.exe' has exited with code -1 (0xffffffff). It runs for a little bit then stops abruptly. 
I am unsure how to get a more detailed bug report and I can't really find it anywhere on the internet. Below is my code, thanks all:

import SimpleITK as sitk

elastixImageFilter = sitk.ElastixImageFilter();
elastixImageFilter.SetParameterMap(sitk.ReadParameterFile('Par0000affine.txt'));
elastixImageFilter.AddParameterMap(sitk.ReadParameterFile('Par0000bspline.txt'));

elastixImageFilter.SetFixedImage(sitk.ReadImage('autofluo_resampled.tif'));
elastixImageFilter.SetMovingImage(sitk.ReadImage('template_25-left.tif'));

resultImage = elastixImageFilter.Execute();
writer = sitk.ImageFileWriter();
writer.SetFileName('registered_C366.tif');
writer.Execute(resultImage);
#sitk.WriteImage(resultImage, 'registered_C366.tif')

**Comment by kaspermarstal** [comment]
Mhm. Does this happen with other images or only the images you use in this case?

**Comment by Sattlert2** [comment]
I ended up just installing it on linux and it works fine. I am unsure what my issue was. Might have been an installation error.
