### ISSUE TITLE
Transforming Point Sets Without Writing to File

### ISSUE THREAD

**Issue by srajaram** [SuperElastix/SimpleElastix#310]
Thanks for the awesome package!

Given a transformation calculated by simpleelastix, I want to to apply this to a point set. While this works great, the issue is I need to perform this operation thousands of times, and would like to implement via parallel runs on a cluster. 

The documented implementation: https://simpleelastix.readthedocs.io/PointBasedRegistration.html takes the point set as input using SetFixedPointSetFileName which expects a file written to disk and outputs the result in the file "outputpoints.txt". This reading/writing to files causes problems/inefficiencies in parallellization.

So I was wondering 
1) Is it possible to provide the Fixed Point Set in memory, i.e. not as a file on disk? 
2) Is it possible to change the default output file from outputpoints.txt (or ideally not write to a file at all)?

Thanks!

**Comment by kaspermarstal** [comment]
It is not possible at the moment because elastix itself only supports reading point files from disk.

**Comment by kaspermarstal** [comment]
It is not possible at the moment because elastix itself only supports reading point files from disk.

**Comment by srajaram** [comment]
Thanks for the response. This seems like a strange choice by elastix ... 

I'm mostly working with rigid transformations, so I guess I can extract the transformation parameters and implement myself. So I'll mark the issue closed.

Thanks!
