### ISSUE TITLE
Documentation for building on Windows

### ISSUE THREAD

**Issue by quakberto** [SuperElastix/SimpleElastix#314]
Thanks for the great package!

Just wanted to note that I just built SimpleElastix on Windows and the final

`sudo python setup.py install`

didn't work with the error:

> error: can't copy '...\SimpleElastix_build\SimpleITK-build\Wrapping\Python\Packaging\_SimpleITK.pyd': doesn't exist or not a regular file

I found _SimpleITK.pyd in the parent folder and 

`python Packaging\setup.py install`

from there worked for me.

**Comment by kaspermarstal** [comment]
Thanks for the report! Will update the documentation.
