### ISSUE TITLE
Can't git clone ITK while building SimpleElastix

### ISSUE THREAD

**Issue by Leomeror** [SuperElastix/SimpleElastix#315]
Hi there,
I am currently trying to get SimpleElastix running on my Windows 7 PC. 
When trying to build SimpleElastix by following the tutorial I ran into some errors, which got fixed by uninstalling previous Python versions and only leaving Python 3.7.4 on my PC.

I was able to build the Super Build with CMake and tried to compile with the msbuild command in x64 native tools command prompt. 
It completes with errors and I can't find the setup.py nor the Wrapping/Python folder in my SimpleITK-build folder. 
I believe the problem is that ITK can't get cloned from github dew to my internet connection breaking off during the process.

Is there a way of downloading ITK seperately and telling the build to just take ITK from my machine instead of downloading it from git?
With other repos there is no problem with git cloning it in x64 native tools command prompt by the way. I think it's just that ITK is too big and my router isn't cut out for  that much Download traffic.

I hope my explanation to the problem wasn't too confusing and let me know if you need more details.

Thanks in advance and best regards,
Leon

**Comment by kaspermarstal** [comment]
Yes, run `ccmake` in the build directory where you build the SuperBuild, and use `ccmake` to set `USE_SYSTEM_ITK` to `ON` and then set `ITK_DIR` to the build directory of ITK on your own system.

**Comment by Leomeror** [comment]
Thank you!

Regards, Leon
