### ISSUE TITLE
about setup.py file

### ISSUE THREAD

**Issue by cs123951** [SuperElastix/SimpleElastix#317]
Hi, I want to use SimpleElastix to register images in python code, so I did the following steps:

$ git clone https://github.com/SuperElastix/SimpleElastix
$ mkdir build
$ cd build
$ cmake ../SimpleElastix/SuperBuild
$ make -j4
$ cd /SimpleITK-build/Wrapping/Python/Packaging
$ sudo python setup.py install

There is no setup.py in /SimpleITK-build/Wrapping/Python/Packaging directory, only a setup.py.in, so I deleted the .in postfix and got a setup.py file.

However, errors occurred.

 File "setup.py", line 13
    doc_files = @SimpleITK_DOC_FILES_AS_LIST@
                ^
SyntaxError: invalid syntax

I am confused about the @SimpleITK_DOC_FILES_AS_LIST@, and @SimpleITK_VERSION_MAJOR@ in the following get_pep386version() function.

Could you give me some advice?
Thank you.

**Comment by cs123951** [comment]
Sorry, I have found my mistakes.

**Comment by pskeshu** [comment]
Hi, I have the sample problem. How did you fix it?

**Comment by kaspermarstal** [comment]
Try to cd into the `/SimpleITK-build/Wrapping/Python` directory and run `sudo python Packaging/setup.py install` (the difference being the location of the Packaging directory in the commands)
