### ISSUE TITLE
AttributeError: 'SimpleITK' object has no attribute 'GetDefaultParameterMap'

### ISSUE THREAD

**Issue by clementgr** [SuperElastix/SimpleElastix#323]
my system is MacOS Mojave 10.14.5

I tried the 'Hello World" tutorial available [here](https://simpleelastix.readthedocs.io/HelloWorld.html) :

```
import SimpleITK as sitk

fixedImage = sitk.ReadImage('fixedImage.png')
movingImage = sitk.ReadImage('movingImage.png')
parameterMap = sitk.GetDefaultParameterMap('translation')

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(fixedImage)
elastixImageFilter.SetMovingImage(movingImage)
elastixImageFilter.SetParameterMap(parameterMap)
elastixImageFilter.Execute()

resultImage = elastixImageFilter.GetResultImage()
transformParameterMap = elastixImageFilter.GetTransformParameterMap()
```
when running this script, i get the following error : 

`AttributeError: 'SimpleITK' object has no attribute 'GetDefaultParameterMap'`

why ?
thank you

**Comment by cmitch** [comment]
Did you use pip install for this? For some reason when I've tried to install that way it doesn't work as many methods simply don't exist. If you did, make sure to use the "Getting Started" page on that link you have instead: https://simpleelastix.readthedocs.io/GettingStarted.html . Good luck though. The newer people on my team have been spending way too much time debugging this, but this method did work for most of us.

**Comment by clementgr** [comment]
hello, thank you for the details!

eventually I uninstalled everything related to SimpleElastix and followed the installation in the Getting Started page (there is still an issue when compiling for Ruby but I only need Python package so I set WRAP_RUBY:BOOL=OFF in the CMakeCache.txt of the build/ directory).

It did install without errors! 
Yet when trying to execute the following script : 

```
import numpy as np
from PIL import Image
import SimpleITK as sitk

fixed_img_path = '../input/fixed_img.png'
moving_img_path = '../input/moving_img.png'

fixed_img = Image.open(fixed_img_path)
moving_img = Image.open(moving_img_path)

parameterMap = sitk.GetDefaultParameterMap('translation')

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(fixed_img)
elastixImageFilter.SetMovingImage(moving_img)
elastixImageFilter.SetParameterMap(parameterMap)
elastixImageFilter.Execute()

resultImage = elastixImageFilter.GetResultImage()
transformParameterMap = elastixImageFilter.GetTransformParameterMap()
```

I get the following error : 

```
Traceback (most recent call last):
  File "image_registration.py", line 24, in <module>
    elastixImageFilter.SetFixedImage(fixed_img)
  File "(...)/python3.6/site-packages/SimpleITK-1.2.0rc2.dev1162+g2a79d-py3.6-macosx-10.7-x86_64.egg/SimpleITK/SimpleITK.py", line 10663, in SetFixedImage
    return _SimpleITK.ElastixImageFilter_SetFixedImage(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'ElastixImageFilter_SetFixedImage'.
  Possible C/C++ prototypes are:
    itk::simple::ElastixImageFilter::SetFixedImage(itk::simple::Image const &)
    itk::simple::ElastixImageFilter::SetFixedImage(itk::simple::ElastixImageFilter::VectorOfImage const &)
```

I can't figure out why...

**Comment by clementgr** [comment]
Ok this one was actually silly...
I just had to use SimpleITK built-in `ReadImage` instead of PIL image reader.
Sorry for the inconvenience.
