### ISSUE TITLE
revenge of `No module named '_SimpleITK'`

### ISSUE THREAD

**Issue by cabaker7** [SuperElastix/SimpleElastix#340]
built for Python 3.6 using CMake without any errors, in a python 3.6-specific Anaconda environment. 

navigated to `{BUILD_DIRECTORY}/SimpleITK-build/Wrapping/Python`
ran `python Packaging/setup.py install`

installation proceeded without any problem, but whenever I try to execute `import SimpleITK` from my python 3.6 environment I once again see `No module named '_SimpleITK'`.

according to my module list it has installed `1.2.0rc2.dev1162+g2a79d`. 

Is this issue solely due to the use of Anaconda? I thought that running setup.py from the appropriate directory solved the problems.

**Comment by kaspermarstal** [comment]
Can you post the full error message? Usually when I see this error it is related to linking of the SimpeITK.so file. If this is the case, the error message will contain information of which symbols that could not be loaded.

**Comment by cabaker7** [comment]
we might actually be able to close this. I removed the environment and built under python 2.7 (also an Anaconda install) and everything went smoothly. At the moment I'm in no hurry to rebuild in python 3 and replicate the error, but if you're still interested I'll let you know when I do.
