### ISSUE TITLE
Using the "TransformParameters.0.txt" file to transform other images

### ISSUE THREAD

**Issue by avasile96** [SuperElastix/SimpleElastix#341]
I've registered a set of 180 3D volumes and generated the "TransformParameters.0.txt" file for each of them like this:

elastixImageFilter.LogToFileOn()
elastixImageFilter.SetOutputDirectory(logsDirectory)

Now I try to register another 180 volumes with the same transformations as before. For this I believe I have to use the "TransformParameters.0.txt" files.

**I don't know how to load  the "TransformParameters.0.txt" into my program.**

I've tried with
initial_parameter_map =  "TransformParameters.0.txt"
parameterMap["InitialTransformParametersFileName"] = [initial_parameter_map]
but it doesn't give me the same results in the end because it only uses  "TransformParameters.0.txt" as an initial transformation.

**Is there a way to use  "TransformParameters.0.txt" to move other volumes in the exact same way the original ones are moved?**

**Comment by kaspermarstal** [comment]
You can load the transform parameter map with `sitk.ReadParameterFile("/path/to/TransformParameters.0.txt`. If you have multiple parameter files (e.g. `TransformParameters.0.txt` and `TransformParameters.1.txt`) you need to do this:

    parameterMap0 = sitk.ReadParameterFile("/path/to/TransformParameters.0.txt`)
    parameterMap1 = sitk.ReadParameterFile("/path/to/TransformParameters.1.txt`)
    transformixImageFilter.SetParameterMap(parameterMap0)
    transformixImageFilter.AddParameterMap(parameterMap1)

Note that the first parameter map needs be set with `SetParameterMap` (deletes previous parameter maps and sets this as the first) and subsequent parameter needs to be set with `AddParameterMap` (appends to the list of existing parameter maps).

**Comment by avasile96** [comment]
> 
> 
> You can load the transform parameter map with `sitk.ReadParameterFile("/path/to/TransformParameters.0.txt`. If you have multiple parameter files (e.g. `TransformParameters.0.txt` and `TransformParameters.1.txt`) you need to do this:
> 
> ```
> parameterMap0 = sitk.ReadParameterFile("/path/to/TransformParameters.0.txt`)
> parameterMap1 = sitk.ReadParameterFile("/path/to/TransformParameters.1.txt`)
> transformixImageFilter.SetParameterMap(parameterMap0)
> transformixImageFilter.AddParameterMap(parameterMap1)
> ```
> 
> Note that the first parameter map needs be set with `SetParameterMap` (deletes previous parameter maps and sets this as the first) and subsequent parameter needs to be set with `AddParameterMap` (appends to the list of existing parameter maps).

Thank you so much! This has worked perfectly!
