### ISSUE TITLE
Core use on windows vs linux

### ISSUE THREAD

**Issue by ryancinsight** [SuperElastix/SimpleElastix#380]
Hello when I compile python version of simpleelastix on windows, no matter how many cores I set, it will only use 50% of my cores when I run the Elastix image filter. However, compiling on docker or windows subsystem Linux on same system it ends up using 100% of the cores. Why is this occurring and is there a way I can correct this?

**Comment by kaspermarstal** [comment]
The number of cores are automatically detected by ITK. Perhaps ITK detects the number of physical cores on Windows but the number of logical cores on Linux. I can't say for sure, but this would be my best guess.

You can manually adjust the number of cores using `SetNumberOfThreads()`.
