### ISSUE TITLE
elxElastixFilter.hxx

### ISSUE THREAD

**Issue by cruigo93** [SuperElastix/SimpleElastix#389]
RuntimeError: Exception thrown in SimpleITK Elastix: ....SimpleElastix/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (0x5634e2d2e190)
Location: "unknown" 
File: ..../build/Elastix/Core/Main/elxElastixFilter.hxx
Line: 253
Description: itk::ERROR: ElastixFilter(0x5634e3fcf8c0): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

I face this problem while trying different types of registration but default one ("translation") works fine.
What am supposed to do to tackle this problem?
I compiled elastix as it was proposed in tutorial

**Comment by michaelsfr** [comment]
Hi, as stated in the error message, the actual error message can be found in the elastix log file. To get the log file add this to your code before executing the registration:

`elastix.LogToFileOn()` 
`elastix.SetOutputDirectory(@'C:\...')` 

> I face this problem while trying different types of registration but default one ("translation") works fine.

Here you just gather the default parameters for a translation registration from simple elastix (other possible default parameter maps are 'affine', 'rigid', 'bspline' or 'nonrigid'). In most cases it makes more sense to create your own default parameter files and pass them to elastix by calling 

`elastix.ReadParameterFile(@'C:\...')`

Examples for parameter files can be found here: http://elastix.bigr.nl/wiki/index.php/Parameter_file_database#:~:text=The%20parameter%20file%20database%20is,here%20many%20examples%20of%20usage.

**Comment by cruigo93** [comment]
@michaelsfr thank you!
