### ISSUE TITLE
Masking for affine registration

### ISSUE THREAD

**Issue by gazile17** [SuperElastix/SimpleElastix#410]
Hello, 

I've tried to perform an affine registration with initially setting a fixed binary mask. The registration works, however it does not differ from the result without setting a fixed mask prior to the same registration.
I did masking before and for a bspline registration it worked perfectly fine. For the affine registration, the whole image is transformed despite setting a mask before. Can anyone relate to this problem? Thank you in advance!

All the best

**Comment by sorenchr2011** [comment]
An affine transform is global to the image. It maps every voxel in the
fixed image to a point in the moving image space - regardless if you use a
mask or not.  The masking is used during registration, not during the final
resampling.
So using a mask/not using masking is not bound to give you a different
result for a global transformation. It depends on to what extent the mask
exterior would have led to a different result. For example, if the exterior
is different between moving and fixed, then the result would likely be
better with masking. If the mask-exterior is similar, eg zeros, then it is
likely masking would have limited to no effect (for a global transform).

Soren

**Comment by gazile17** [comment]
Alright, thank you very much for the quick and clear explanation!
