### ISSUE TITLE
build directory and python setup

### ISSUE THREAD

**Issue by stephenholtz** [SuperElastix/SimpleElastix#43]
It seems like some of the directories mentioned in the documentations might not exist any more. 

for instance `./SimpleITK-build/Wrapping` does not contain PythonPackage,

it seems instead to be under `./SimpleElastix/Wrapping/PythonPackage` and be the`ez_setup.py`

Is this correct? I was going to update documentation to reflect this if so.

Related to this, the "build directory" referenced is sometimes the `./build` folder made during installation, and other times seems to be the `./SimpleElastix` folder made after running the `make` command. Could you clarify what each directory is?

**Comment by stephenholtz** [comment]
In the build directory:

```
kyobi@mischief:~/code$ find build/ -type f -name "*setup*" -print
build/Swig-prefix/src/Swig/Tools/setup.py.tmpl
build/Swig-prefix/src/Swig/Examples/chicken/egg/single.setup
build/Swig-prefix/src/Swig/Examples/chicken/egg/multi.setup
```
In the SimpleElastix directory:
```
kyobi@mischief:~/code$ find SimpleElastix -type f -name "*setup*" -print
SimpleElastix/Wrapping/PythonPackage/setuptools-2.2.tar.gz
SimpleElastix/Wrapping/PythonPackage/ez_setup.py
SimpleElastix/Wrapping/PythonPackage/setup.py.in
SimpleElastix/Wrapping/PythonPackage/setupegg.py
```

At this point I am not clear on how to actually install the python module successfully. Running the ez_setup.py script:

`sudo python ez_setup.py install` 

but this itself does not let me import the module, is there some system path variable I am neglecting?

**Comment by kaspermarstal** [comment]
You should have a setup.py file in build/SimpleITK-build/Wrapping/PythonPackage directory. This should then be run like `sudo python setup.py install`. 

Can you point out where there is confusion about the build directories? It should be the top-level build directory when using the SuperBuild and needs to be fixed :) thanks for the heads up

**Comment by kaspermarstal** [comment]
The confusion may stem from that fact that the Python directory will be in `buildir/SimpleITK-build/Wrapping/PythonPackage` directory when using the superbuild, and `buildir/Wrapping/PythonPackage` when not using the superbuild.

**Comment by snapfinger** [comment]
I didn't find the `setup.py` either. To be more specific, there's no such directory called `PythonPackage`.
I tried the `setupegg.py` of `Wrapping/Python/Packaging/setupegg.py`, but it didn't work.

![image](https://cloud.githubusercontent.com/assets/13393457/21318146/099b5f0e-c5d6-11e6-8c80-cad7478d90fb.png)

**Comment by sullivak-kyra** [comment]
I found setup.py in SimpleITK-build/Wrapping/Pytho**n/P**ackag**ing**
Running this seemed to work, at least I can see Elastix & SimpleElastix in dir(SimpleITK). This was fresh clone, commit: 7e302601dbced70fe5e73d

**Comment by CPFLAME** [comment]
I just met the same problem as  @stephenholtz, 
![qq 20170227175239](https://cloud.githubusercontent.com/assets/13843079/23356743/fe118998-fd15-11e6-9770-a15cfa7d69d2.png)
There is only Java, Lua and Tcl , I cannot find PythonPackage .

**Comment by CPFLAME** [comment]
I've solved this problem, your Python path mush be '/usr/bin', instead of the anaconda one.

**Comment by a-r-j** [comment]
I'm having the same issue as @snapfinger  

In the build > SimpleITK  folder I only see CMakeCacheInit.txt. In SimpleElastix > Wrapping > Python > Packaging I have the following: __init__.py, setup.py.in and setupegg.py. I have attached the cache file if it is of use.
[CMakeCacheInit.txt](https://github.com/kaspermarstal/SimpleElastix/files/855872/CMakeCacheInit.txt)


Using OS X and have tried using both the native python and anaconda installations.

**Comment by kaspermarstal** [comment]
@a-r-j It looks like CMake is not picking up your Python installation, otherwise it is usually build by default. There isn't any Python variables in your CMakeCacheInit.txt either. Is WRAP_Python set to ON or OFF after cmake is initialized?

**Comment by siavash66** [comment]
Dear kaspermarstal
When I run “**python setup.py install**” command in the {BUILD_DIRECTORY}/SimpleITK-build/Wrapping/Python/Packaging path, the following error occurs:
error: can’t copy ‘F:\Development\build\SimpleElastix\SimpleITK-build\Wrapping\Python\Packaging\ _simpleitk.pyd’ :  does not exist or not a regular file
I would be thankful if you help me in this way

**Comment by longkuanzou** [comment]
> I've solved this problem, your Python path mush be '/usr/bin', instead of the anaconda one.

Hello, I meet the same problem, could tell me how do you solve this problem? thanks.

**Comment by MahnoorTanveer** [comment]
I am having the same issue. Is Python with Anaconda good with Simple-ITK of having linux filesystem is a dependencies
