### ISSUE TITLE
JoinSeries - Largest Possible Region

### ISSUE THREAD

**Issue by gattia** [SuperElastix/SimpleElastix#50]
Hi, 

This is probably actually just something that has been fixed... but I just want to make sure/make note of it on the vaste inter web in case someone else has the same issue. 

I had previously been doing some playing with SimpleElastix and have come back to it after a hiatus and my code wouldn't work any more. In particular, I was running the groupwise registration tutorial from the "readthedocs". When doing this, I couldn't get past the JoinSeries... which I had no problem with before. I was using different data to start, but defaulted back to the old data to make sure. I kept getting an error that ended with :

> Requested region is (at least partially) outside the largest possible region.

So, after some playing, it seems that as long as I pick a bunch of images that are the same dimensions it Joins just fine - all my images have 2 dimensions the same (512x512) but they vary on the number of slices from 90-106.

Anyways, I am assuming that the sitk code has been updated since I last played? Or maybe something else? 

Anyways, to deal with this issue I was wondering if anyone has any thoughts? 
My thoughts are two-fold: 

1) I noticed there is a LargestPossibleRegion parameter when I print a sitk object.... and this value seems to vary from image to image and is sometimes the same as the image itself and sometimes its bigger. If I could change the size of this I am assuming that I wouldn't get the above error anymore and I would be able to join images of different dimension. THOUGH, I can't figure out how to change this. In the simpleITK docs there is no Get or Set for LargestPossibleRegion and I tried to GetMetaData but that didn't work either.

2) I guess I could just pick the largest image dimensions in the dataset (106x512x512) and scale all images to be that size. 

Any thoughts or suggestions would be greatly appreciated. 

Thanks, 

Anthony.

**Comment by kaspermarstal** [comment]
The first step would be to reproduce the problem in SimpleITK. If it works in SimpleITK, let me know, otherwise you could consider opening an issue in the [SimpleITK repo](https://github.com/SimpleITK/SimpleITK). Sorry for the late reply 😬
