### ISSUE TITLE
Multi-channel image registration with large number of channels

### ISSUE THREAD

**Issue by gdhugo** [SuperElastix/SimpleElastix#53]
I'm having a strange issue when running registration on a multi-channel image. I use the suggested approach in the elastix manual such as:

`elastix -f0 channel1_fixed.mhd -f1 channel2_fixed.mhd -m0 channel1_moving.mhd -m1 channel2_moving.mhd ...`

where the multichannel image with N channels has been separated into N scalar images.

In SimpleElastix I implement this as:

```
elastix = sitk.SimpleElastix()
for idx in range(numberOfChannels):
  elastix.AddFixedImage( sitk.VectorIndexSelectionCast(fixedChannelImage, idx))
  elastix.AddMovingImage( sitk.VectorIndexSelectionCast(movingChannelImage, idx))
```

All works the same with both the SimpleElastix and command line elastix approaches for 6 or less channels.  Meaning, I obtain good registrations, and the metric and gradient are both decaying as expected.

However, when I try to use more than 6 channels, the command line approach still gives good results, but SimpleElastix gives very strange results.  The individual channel metrics and gradients do not decay as expected, and the combined metric is very noisy and does not change much with a large number of iterations. To see what I mean, here are plots of the metric and gradient.  Upper left of each plot is the overall Metric value vs. iteration. Lower left is the overall Gradient magnitude. Upper right shows the metric for each individual component / channel (Metric0, Metric1, etc. from IterationInfo.txt).  Lower right shows the individual gradient for each component / channel.

SimpleElastix, 6 channels:
![6_channels_sitk](https://cloud.githubusercontent.com/assets/1187240/19239965/55902098-8ed6-11e6-9371-2d56085ca19c.png)

elastix command line, 6 channels:
![6_channels_elx](https://cloud.githubusercontent.com/assets/1187240/19239974/63dddcda-8ed6-11e6-81d0-b3afaa10b3bc.png)

SimpleElastix, 7 channels:
![7_channels_sitk](https://cloud.githubusercontent.com/assets/1187240/19239990/73be392e-8ed6-11e6-914f-05de62d65b37.png)

elastix command line, 7 channels:
![7_channels_elx](https://cloud.githubusercontent.com/assets/1187240/19239997/7bfc82ee-8ed6-11e6-9225-6a686d1d6701.png)

I've reviewed the SimpleElastix code, and can't find anything that might explain this issue.  I don't believe it is memory related, since I can easily run over 20 channels on the command line (these are small, 2D multichannel images in this test case), and can load just as many into memory in SimpleElastix without issue.  

Any help on this issue would be much appreciated.  I can also package and send this test case, if that would help?

Thanks,
Geoff

**Comment by gdhugo** [comment]
Just a quick update:

I tried the same thing with very tiny images, to make sure it wasn't a memory or floating point issue.  I used the following very tiny images:

```
  numberOfAttributes = 7
  fixedAttributeImage = sitk.Image([32,32], sitk.sitkVectorUInt8, numberOfAttributes)
  movingAttributeImage = sitk.Image([32,32], sitk.sitkVectorUInt8, numberOfAttributes)
  val = range(numberOfAttributes)
  fixedPixel = [16, 16]
  movingPixel = [17, 17]
  fixedAttributeImage.SetPixel(fixedPixel[0], fixedPixel[1], val)
  movingAttributeImage.SetPixel(movingPixel[0], movingPixel[1], val)
```

and got similar results (command line elastix works fine, SimpleElastix gives noisy cost/gradient).

**Comment by kaspermarstal** [comment]
Are you using the exact same parameter settings? SimpleElastix is the Adaptive Stochastic Gradient Descent optimizer by default, are you also using this optimizer when running elastix via the command line?

**Comment by kaspermarstal** [comment]
I am not sure what is going on because SimpleElastix is not compiled for vector images. Or perhaps you customized SimpleElastix for that? In any case, yes, can you send a test data + script? That would be very helpful, thanks.

**Comment by gdhugo** [comment]
Thanks, Kasper.  To answer your questions:

1. Yes, I am using the exact same parameter files.  For components <= 6, I get exactly the same result and performance for command line and SimpleElastix (both with StochasticGradientDescent). 

2. I am not using vector images.  Instead, I load in each component as a (scalar) image into the VectorOfImages.  Command line elastix also does not handle vector-valued images.  Instead, one registers a vector-valued image by extracting each component into a scalar image and running:  

```
elastix -f0 channel1_fixed.mhd -f1 channel2_fixed.mhd -m0 channel1_moving.mhd -m1 channel2_moving.mhd ...
```

For a 2 channel image, for example.

I'll send a small test set through email.

**Comment by kaspermarstal** [comment]
How do you add multiple images in SimpleElastix? Are you using `AddFixedImage()` and `AddMovingImage()`? From your code snippet it looks like you create a vector image.

**Comment by gdhugo** [comment]
Sorry, I probably did not describe this thoroughly.  In the code, yes, I am using `AddFixedImage()` and `AddMovingImage()`. I loop through the component (channel) indices of multi-channeled (vector-valued) fixed and moving images, and use `sitk.VectorIndexSelectionCast()` to extract each channel, and add them subsequently using `AddFixedImage()` and `AddMovingImage()`.  I'm preparing to email you the test case shortly.

**Comment by gdhugo** [comment]
Here is the test set.  You can run it using the python script test.py.  Make sure to change the two parameters in lines 11 and 12:

stem - point this to the disk location of the unzipped directory attributes_problem_smallimage.
numberOfAttributes - set to either 6 or 7 (the number of channels or attributes per pixel).  The script will only run with either 6 channels (this is the case that works fine) or 7 channels (this the case that fails relative to the command line).

At the bottom of the test.py script are two command line calls that can be used to try to run the same case with command line elastix.

[attributes_problem_smallimage.zip](https://github.com/kaspermarstal/SimpleElastix/files/551043/attributes_problem_smallimage.zip)

**Comment by kaspermarstal** [comment]
I have not forgotten you, I just haven't had the time to look at it. To be continued ...

**Comment by gdhugo** [comment]
One update:  Thanks to your help on the C++ project issue, I am able to confirm the problem here is not related to Python wrapping, as the same issue appears when I implemented in C++. I'm thinking about trying to implement using elxElastixFilter to see if this is truly a SimpleElastix issue or an issue with elastix itself. Will let you know when I have some results.

**Comment by gdhugo** [comment]
OK, I've done a bit more investigation on this and I can confirm the issue seems related to SimpleElastix, rather than elastix itself.  I've basically reproduced the internals of SimpleElastixImpl
::DualExecuteInternal by instantiating my own elxElastixFilter, passing the multi-channel SimpleITK image to elastix using AddFixedImage / AddMovingImage and GetITKBase() to get an ITK image.  Thus, I am not using any SimpleElastix to do any of the registration part.  When doing this, elastix runs without issue (as I describe above if calling from the command line).  So, my suspicions are the problem lies somewhere in SimpleElastix / SimpleITK.  However, I am stuck at this point.  Any suggestions on how to proceed to try to track down this issue would be welcome.

**Comment by kaspermarstal** [comment]
Can you check if the difference stems from SimpleITK image reader by trying out both ITKs image reader and SimpleITK's image reader in your C++ code?

**Comment by kaspermarstal** [comment]
Closing as we never found the underlying issue. Feel free to reopen if you want to discuss further. If you found a solution please let me know so I can fix it for everybody, or, even better, make a PR :D
