### ISSUE TITLE
How to use SimpleElastix as C# project reference?

### ISSUE THREAD

**Issue by simingbayer** [SuperElastix/SimpleElastix#57]
Hi everyone,

I have built and compiled SimpleElastix successfully on my PC and plan to implement a registration GUI with C#. The WRAP_CSHARP option was set in CMAKE. However, I didn't find any .dll file in the compiled SimpleElastix solution. I have also tried to create a new C# project from the existing SimpleElastix project, the new solution cannot be built successfully. Does anybody knows where to find th .dll file of SimpleElatix? Or how to use SimpleElastix as framework in a new C# Project?

best,
Siming

**Comment by kaspermarstal** [comment]
Closing since this issue is almost a year old. If anyone knows how to import the C# build into VS, we would be very glad for a PR to the documentation.
