### ISSUE TITLE
Build Failed on Windows and VS 2013

### ISSUE THREAD

**Issue by mylyu** [SuperElastix/SimpleElastix#68]
Hi,

I am trying to build SimpleElastix on Windows using VS 2013. I got the same error for all my PCs. After cmake GUI, I used
`msbuild ALL_BUILD.vcxproj /p:Configuration=Release`

then I got

> -- Adding C# exe CSharpFilterProgressReporting: 'C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/csc.exe /t:exe /out:CS
>   harpFilterProgressReporting.exe /platform:anycpu  /reference:System.dll;/reference:SimpleITKCSharpManaged.dll C:\mri_
>   software\SimpleElastix_src\Examples\CSharp\FilterProgressReporting.cs'
>   -- Configuring incomplete, errors occurred!
>   See also "C:/Si/SimpleITK-build/CMakeFiles/CMakeOutput.log".
>   See also "C:/Si/SimpleITK-build/CMakeFiles/CMakeError.log".
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exi
> ted with code 1. [C:\Si\SimpleITK.vcxproj]
> Done Building Project "C:\Si\SimpleITK.vcxproj" (default targets) -- FAILED.
> 
> Done Building Project "C:\Si\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Something wrong with SimpleITK cmakes files? It looks like in debug mode and giving VS compilers wrong parameters that is not applicable? "SimpleITK-build/CMakeFiles/CMakeError.log" (https://github.com/kaspermarstal/SimpleElastix/files/727234/SimpleITK-build.CMakeFiles.zip) is like:

> ...
> Source file was:
> int main() { return 0; }
> Performing C++ SOURCE FILE Test CXX_HAS-Wno-long-double failed with the following output:
> Change Dir: C:/Si/SimpleITK-build/CMakeFiles/CMakeTmp
> 
> Run Build Command:"C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe" "cmTC_aa042.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=12.0"
> Microsoft (R) Build Engine version 12.0.40629.0
> 
> [Microsoft .NET Framework, version 4.0.30319.42000]
> 
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> 
> 
> Build started 2017-01-24 9:05:06 PM.
> 
> Project "C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\cmTC_aa042.vcxproj" on node 1 (default targets).
> 
> PrepareForBuild:
> 
>   Creating directory "cmTC_aa042.dir\Debug\".
> 
>   Creating directory "C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\Debug\".
> 
>   Creating directory "cmTC_aa042.dir\Debug\cmTC_aa042.tlog\".
> 
> InitializeBuildStatus:
> 
>   Creating "cmTC_aa042.dir\Debug\cmTC_aa042.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> 
> ClCompile:
> 
>   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CXX_HAS-Wno-long-double" /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"cmTC_aa042.dir\Debug\\" /Fd"cmTC_aa042.dir\Debug\vc120.pdb" /Gd /TP /wd4251 /wd4251 /errorReport:queue  /bigobj /bigobj /bigobj -Wno-long-double "C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\src.cxx"
> 
>   Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
> 
>   Copyright (C) Microsoft Corporation.  All rights reserved.
> 
>   
> 
>   cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CXX_HAS-Wno-long-double" /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"cmTC_aa042.dir\Debug\\" /Fd"cmTC_aa042.dir\Debug\vc120.pdb" /Gd /TP /wd4251 /wd4251 /errorReport:queue  /bigobj /bigobj /bigobj -Wno-long-double "C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\src.cxx"
> 
> cl : Command line error D8021: invalid numeric argument '/Wno-long-double' [C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\cmTC_aa042.vcxproj]
> 
> Done Building Project "C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\cmTC_aa042.vcxproj" (default targets) -- FAILED.
> 
> 
> 
> Build FAILED.
> 
> 
> 
> "C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\cmTC_aa042.vcxproj" (default target) (1) ->
> 
> (ClCompile target) -> 
> 
>   cl : Command line error D8021: invalid numeric argument '/Wno-long-double' [C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\cmTC_aa042.vcxproj]
> 
> 
> 
>     0 Warning(s)
> 
>     1 Error(s)
> 
> 
> 
> Time Elapsed 00:00:00.26
> 
> ...

**Comment by kaspermarstal** [comment]
I don't have much experience with the Windows C# build and can't help you sorry. Are you seeing the same errors of you set WRAP_CSHARP to OFF?

**Comment by mylyu** [comment]
Thanks. I still get a similar error:

>  -- Building SimpleITK version "0.10.0-gGITDIR-NOTFOUND"
>   -- Found PythonLibs: C:/Python27/libs/python27.lib (found suitable exact version "2.7.5")
>   -- Found Java: C:/Program Files (x86)/Java/jdk1.6.0_45/bin/java.exe (found version "1.6.0.45") found components:
>    Development Runtime
>   -- Could NOT find Tclsh (missing:  TCL_TCLSH)
>   -- Found the following C# .NET versions: v4.0.30319, v3.5, v2.0.50727
>   -- Processing json files...
>   -- Processing json files...done
>   -- Found PythonLibs: C:/Python27/libs/python27.lib (found version "2.7.5")
>   -- Found Java: C:/Program Files (x86)/Java/jdk1.6.0_45/bin/java.exe (found version "1.6.0.45")
>   -- Generating tests...
>   -- Generating tests...Done
>   -- Configuring incomplete, errors occurred!
>   See also "C:/Si/SimpleITK-build/CMakeFiles/CMakeOutput.log".
>   See also "C:/Si/SimpleITK-build/CMakeFiles/CMakeError.log".
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe"
>  exited with code 1. [C:\Si\SimpleITK.vcxproj]
> Done Building Project "C:\Si\SimpleITK.vcxproj" (default targets) -- FAILED.
> 
> Done Building Project "C:\Si\ALL_BUILD.vcxproj" (default targets) -- FAILED.
> 
> 
> Build FAILED.
> 
> "C:\Si\ALL_BUILD.vcxproj" (default target) (1) ->
> "C:\Si\SimpleITK.vcxproj" (default target) (6) ->
> (CustomBuild target) ->
>   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.ex
> e" exited with code 1. [C:\Si\SimpleITK.vcxproj]

CMakeError.log is attached 
[CMakeError.txt](https://github.com/kaspermarstal/SimpleElastix/files/744330/CMakeError.txt)

, reporting:

> cl : Command line error D8021: invalid numeric argument '/Wno-long-double' [C:\Si\SimpleITK-build\CMakeFiles\CMakeTmp\cmTC_fa6e6.vcxproj]

**Comment by kaspermarstal** [comment]
Try to clone it from github. I suspect you downloaded a zip file with the source code. SimpleITK uses the .git directory to determine version information and fails to build if this is not available.

**Comment by mylyu** [comment]
Great. What you said turned out to be the cause! Although I still got some
errors in the python wrapper part, I can finish the build successfully with
git clone and all wrappers being off. Thanks.

**Comment by mylyu** [comment]
There is no problem is only building c# and Java wrappers, but if I build python wrappers, it will give me hundreds of errors:

> 
> SimpleITKPYTHON_wrap.obj : error LNK2019: unresolved external symbol __imp_PyType_IsSubtype referenced in function
> _wrap_DemonsRegistrationFilter_Execute [C:\Si\SimpleITK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\Si\Simp
> leITK.vcxproj]
> SimpleITKPYTHON_wrap.obj : error LNK2019: unresolved external symbol __imp_PyType_Ready referenced in function Swig
> PyObject_TypeOnce [C:\Si\SimpleITK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\Si\SimpleITK.vcxproj]
> SimpleITKPYTHON_wrap.obj : error LNK2019: unresolved external symbol __imp_PyObject_Str referenced in function "voi
...
> tual void __cdecl itk::simple::PyCommand::Execute(void)" (?Execute@PyCommand@simple@itk@@UEAAXXZ) [C:\Si\SimpleITK-
> build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\Si\SimpleITK.vcxproj]
> sitkPyCommand.obj : error LNK2019: unresolved external symbol __imp_PyObject_CallObject referenced in function "pub
> lic: virtual void __cdecl itk::simple::PyCommand::Execute(void)" (?Execute@PyCommand@simple@itk@@UEAAXXZ) [C:\Si\Si
> mpleITK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\Si\SimpleITK.vcxproj]
> C:\Si\SimpleITK-build\Wrapping\Python\_SimpleITK.pyd : fatal error LNK1120: 107 unresolved externals [C:\Si\SimpleI
> TK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [C:\Si\SimpleITK.vcxproj]
>   Done Building Project "C:\Si\SimpleITK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj" (default targets) -- FAILE
>   D.
>   Done Building Project "C:\Si\SimpleITK-build\Wrapping\Python\PythonVirtualEnv.vcxproj" (default targets) -- FAILE
>   D.
...

**Comment by mylyu** [comment]
So I must use 64-bit python if I use 64-bit SimpleElasitx? If it is a only wrapper, why do 32-bit and 64-bit matter so much?

**Comment by kaspermarstal** [comment]
32-bit programs are generally not compatible with 64-bit programs, but the SimpleITK build system should take care of this so I suspect this is not the root of the problem. 

Are you using a compatible version of Visual Studio for your compiler? Different versions of Visual Studio needs to be used with different versions of Python. You can see which version to use here: https://wiki.python.org/moin/WindowsCompilers.

**Comment by mylyu** [comment]
I switched from 32-bit python 2.7 to its 64-bit, and then the build was finished with no errors. 👍  Many thanks.

**Comment by kaspermarstal** [comment]
OK great :)

**Comment by Va2sili** [comment]
Hello,

I am trying to build SuperElastix on Windows 10 with Visual Studio 2019. I followed exactly the different steps of the tutorial, but when I run the command line to compile everything, the compilation of simple ITK fails with the following messages:
`cl : command line error D8021: invalid numeric argument '/Wno-long-double'`
`cl : command line error D8021: invalid numeric argument '/Wno-unused-local-typedefs'`
`cl : command line error D8021: invalid numeric argument '/Wno-strict-overflow'`
`cl : command line error D8021: invalid numeric argument '/Wextra'`
... and a bunch of other similar errors.
I cloned the repository from github and I am using Python 3.9 64-bit. Could you help me please?
