### ISSUE TITLE
Parameter entries specific to TransformRigidityPenalty are not passed to elastix call

### ISSUE THREAD

**Issue by quakberto** [SuperElastix/SimpleElastix#69]
Hi,

when setting up a parameter map:

`nonrigid_parameters = sitk.GetDefaultParameterMap('nonrigid')`
`nonrigid_parameters['Metric'] = ('AdvancedMattesMutualInformation','TransformRigidityPenalty')`
`nonrigid_parameters['UseOrthonormalityCondition '] = ('false',)`
`SimpleElastix.SetParameterMap(nonrigid_parameters)`

during the run elastix will complain that

`WARNING: The parameter "UseOrthonormalityCondition", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.`

ignoring the previously set field. The same happens for other TransformRigidityPenalty specific options (all I tried so far).
However, if I save the same parameter map to a txt file and run it with command line elastix the entry is successfully registered.

Thanks a lot!
Best,
Marvin

**Comment by kaspermarstal** [comment]
The elastix library API is not aware if these parameters at the moment. If you want to submit a PR to the elastix repo, reopen and I will be happy to give some hints.
