### ISSUE TITLE
How to use Registration Point 

### ISSUE THREAD

**Issue by tvessiere** [SuperElastix/SimpleElastix#70]
Hi everyone,

i'm trying to use Registration point.

i don't know how use it. i have 2 files, one for FixPoint and one for MovingPoint.
My files are like this : 

fixpoint.txt :
point
5
2214.0 282.2 0.0
2445.0 2013.0 0.0
795.0 366.0 0.0
153.0 609.0
324.0 2322.0

movpoint.txt :
point
5
2049.0 204.0 0.0
2442.0 1899.0 0.0
675.0 423.0 0.0
78.0 723.0 0.0
393.0 2406.0 0.0

and I have based myself on this example : 
import SimpleITK as sitk

SimpleElastix = sitk.SimpleElastix()
SimpleElastix.SetFixedImage(sitk.ReadImage("fixedImage.nii")
SimpleElastix.SetMovingImage(sitk.ReadImage("movingImage.nii")
SimpleElastix.Execute()

SimpleTransformix = sitk.SimpleTransformix()
SimpleTransformix.SetFixedPointSet("fixedPointSet.pts")
SimpleTransformix.Execute()

I would like to know If it's possible to apply a transformation based on a list of point on a image and how ?

Thanks you.

Vessiere Thomas.

**Comment by kaspermarstal** [comment]
Yes, you can use SimpleElastix.SetFixedPointFileName()  and SimpleElastix.SetMovingPointFileName() together with the "CorrespondingPointsEuclideanDistanceMetric". I see that the page you have found does not contain code for the actual registration. I will update this!

**Comment by tvessiere** [comment]
Tanks you Kasper,

### I tried this code : 

```
import SimpleITK as sitk
import numpy as np
import scipy.misc as misc

simpleElastix = sitk.SimpleElastix()
simpleElastix.SetParameter( "Metric", "CorrespondingPointsEuclideanDistanceMetric" )
#simpleElastix.SetParameter("Registration","AdvancedImageToImageMetric" )
simpleElastix.LogToConsoleOn()
#simpleElastix.SetParameterMap(sitk.GetDefaultParameterMap('rigid'))
#simpleElastix.AddParameterMap(sitk.GetDefaultParameterMap('affine'))
simpleElastix.PrintParameterMap()

fixImage = sitk.ReadImage("/home/tvessiere/Pictures/fixtissu.png",sitk.sitkFloat32)
movingImage = sitk.ReadImage("/home/tvessiere/Pictures/movtissu.png",sitk.sitkFloat32)

simpleElastix.SetFixedImage(fixImage)
simpleElastix.SetMovingImage(movingImage)

simpleElastix.SetFixedPointSetFileName("/home/tvessiere/Pictures/fixpoint.txt")
simpleElastix.SetMovingPointSetFileName("/home/tvessiere/Pictures/movpoint.txt")
simpleElastix.Execute()

img = simpleElastix.GetResultImage()
np_img = sitk.GetArrayFromImage(img)
img_to_save = np.zeros((np_img.shape[0],np_img.shape[1],3))
img_to_save[:,:,1] = np_img
img_to_save[:,:,2] = sitk.GetArrayFromImage(fixImage)
misc.imsave("result.png",img_to_save)
```

### and i got this error : 

```
itk::ExceptionObject (0x1b55ae0)
Location: "unknown" 
File: /home/tvessiere/data/build/elastix/src/Components/Registrations/MultiResolutionRegistration/elxMultiResolutionRegistration.hxx
Line: 137
Description: itk::ERROR: MultiResolutionRegistration(0x1b48730): ERROR: MultiResolutionRegistration expects the metric to be of type AdvancedImageToImageMetric!

```
### so i add this line in my code : 

`simpleElastix.SetParameter("Registration","AdvancedImageToImageMetric" )`

### and after that i got this : 
```

Error: 
AdvancedImageToImageMetric(index 1) - This component is not installed!
ERROR: error occurred while creating Registration 0.

itk::ExceptionObject (0x1791cd0)
Location: "unknown" 
File: /home/tvessiere/data/build/elastix/src/Core/Kernel/elxElastixMain.cxx
Line: 819
Description: itk::ERROR: ElastixMain(0x17a68f0): The following component could not be created: AdvancedImageToImageMetric
```

do you have any tips ?

Thanks you.

Vessiere Thomas.

**Comment by kaspermarstal** [comment]
Yes, I have a tip :) For historical reasons you need to add a normal metric in addition to CorrespondingPointsEuclideanDistanceMetric, and CorrespondingPointsEuclideanDistanceMetric needs to be the last one. So try the following

```
simpleElastix.SetParameter( "Metric", ("NormalizedMutualInformation", "CorrespondingPointsEuclideanDistanceMetric",))
```

and set the weight of the mutual information metric to zero if you do not want that to influence the registration,

```
simpleElastix.SetParameter("Metric0Weight", "0.0")
```
 (although a little bit of an intensity-based metric is good to regularize the b-spline field if you have a sparse set of points).

Let me know how it goes!

**Comment by tvessiere** [comment]
Hi Kasper,

Thanks a lot for the tip ! it works 

but i have a question. did i  param correctly my algo here for using point registration (btw, i dont want to use bspline transform because i got some plastic deformations..) ? 
## i have tried this code : 
```
import SimpleITK as sitk
import numpy as np
import scipy.misc as misc


iterationNumbers = 6000
spatialSamples = 6000

simpleElastix = sitk.SimpleElastix()
simpleElastix.SetParameter("Registration","MultiMetricMultiResolutionRegistration")
simpleElastix.SetParameter( "Metric", ("NormalizedMutualInformation", "CorrespondingPointsEuclideanDistanceMetric",))
simpleElastix.SetParameter("Metric0Weight", "0.0")

simpleElastix.LogToConsoleOn()
simpleElastix.SetParameterMap(sitk.GetDefaultParameterMap('translation'))
simpleElastix.AddParameterMap(sitk.GetDefaultParameterMap('affine'))

simpleElastix.SetParameter("MaximumNumberOfIterations" , str(iterationNumbers))
simpleElastix.SetParameter("NumberOfSpatialSamples" , str(spatialSamples))

simpleElastix.PrintParameterMap()

fixImage = sitk.ReadImage("/home/tvessiere/Pictures/fixtissu2.png",sitk.sitkFloat32)
movingImage = sitk.ReadImage("/home/tvessiere/Pictures/movtissu2.png",sitk.sitkFloat32)

simpleElastix.SetFixedImage(fixImage)
simpleElastix.SetMovingImage(movingImage)

simpleElastix.SetFixedPointSetFileName("/home/tvessiere/Pictures/fixpoint.txt")
simpleElastix.SetMovingPointSetFileName("/home/tvessiere/Pictures/movpoint.txt")
simpleElastix.Execute()

img = simpleElastix.GetResultImage()
np_img = sitk.GetArrayFromImage(img)
img_to_save = np.zeros((np_img.shape[0],np_img.shape[1],3))
img_to_save[:,:,1] = np_img
img_to_save[:,:,2] = sitk.GetArrayFromImage(fixImage)
misc.imsave("result.png",img_to_save)

```
final metric = -0.569108

### and i have the same final metric without fix & point files : 
```
import SimpleITK as sitk
import numpy as np
import scipy.misc as misc


iterationNumbers = 6000
spatialSamples = 6000

simpleElastix = sitk.SimpleElastix()
simpleElastix.SetParameter("Registration","MultiMetricMultiResolutionRegistration")
simpleElastix.SetParameter( "Metric", ("NormalizedMutualInformation", "CorrespondingPointsEuclideanDistanceMetric",))
simpleElastix.SetParameter("Metric0Weight", "0.0")

simpleElastix.LogToConsoleOn()
simpleElastix.SetParameterMap(sitk.GetDefaultParameterMap('translation'))
simpleElastix.AddParameterMap(sitk.GetDefaultParameterMap('affine'))

simpleElastix.SetParameter("MaximumNumberOfIterations" , str(iterationNumbers))
simpleElastix.SetParameter("NumberOfSpatialSamples" , str(spatialSamples))

simpleElastix.PrintParameterMap()

fixImage = sitk.ReadImage("/home/tvessiere/Pictures/fixtissu2.png",sitk.sitkFloat32)
movingImage = sitk.ReadImage("/home/tvessiere/Pictures/movtissu2.png",sitk.sitkFloat32)

simpleElastix.SetFixedImage(fixImage)
simpleElastix.SetMovingImage(movingImage)

#simpleElastix.SetFixedPointSetFileName("/home/tvessiere/Pictures/fixpoint.txt")
#simpleElastix.SetMovingPointSetFileName("/home/tvessiere/Pictures/movpoint.txt")
simpleElastix.Execute()

img = simpleElastix.GetResultImage()
np_img = sitk.GetArrayFromImage(img)
img_to_save = np.zeros((np_img.shape[0],np_img.shape[1],3))
img_to_save[:,:,1] = np_img
img_to_save[:,:,2] = sitk.GetArrayFromImage(fixImage)
misc.imsave("result.png",img_to_save)
```
What have I done wrong?  

Thranks You.

Vessiere Thomas.

**Comment by kaspermarstal** [comment]
Yes that looks correct. Sorry for the looooooooong reply. I am working through the backlog of issues. Do reopen if you still have a problem!

**Comment by peterzzz12** [comment]
@kaspermarstal 
I tried the method you mentioned on the above, but it apears an new error like this 
`LinearInterpolator(index 1) - This component is not installed!
ERROR: error occurred while creating Interpolator 0.

itk::ExceptionObject (000000000023E198)
Location: "unknown" 
File: C:\Elastix\src\Core\Kernel\elxElastixMain.cxx
Line: 819
Description: itk::ERROR: ElastixMain(00000000004AC450): The following component could not be created: LinearInterpolator

ERROR:
One or more components could not be created.` 

and here is my C++ code:
`	sitk::Image img1 = sitk::ReadImage("CT.tif", sitk::sitkFloat32);

	sitk::Image img2 = sitk::ReadImage("afterSVD.tif", sitk::sitkFloat32);
	sitk::SimpleElastix elastixTest;

	
	elastixTest.SetParameter("Metric", ("NormalizedMutualInformation", "CorrespondingPointsEuclideanDistanceMetric"));
	elastixTest.SetParameter("Metric0Weight", "0.0");
	elastixTest.SetParameter("Registration", "AdvancedImageToImageMetric");
	elastixTest.LogToFileOn();
	elastixTest.LogToConsoleOn();
	elastixTest.SetParameterMap(sitk::GetDefaultParameterMap("rigid"));
	elastixTest.AddParameterMap(sitk::GetDefaultParameterMap("affine"));
	std::cout << "1" << std::endl;
	elastixTest.PrintParameterMap();
	std::cout << "2" << std::endl;
	elastixTest.SetFixedImage(img1);
	elastixTest.SetMovingImage(img2);
	std::cout << "3" << std::endl;
	elastixTest.SetFixedPointSetFileName("Test_landmark.txt");
	elastixTest.SetMovingPointSetFileName("TestMove_landmark.txt");
	std::cout << "4" << std::endl;
	system("pause");
	elastixTest.Execute();
	sitk::Image Elastix_test = elastixTest.GetResultImage();

	sitk::WriteImage(Elastix_test, "0Restlt.tif");`
What should I do ?
thanks so much

**Comment by ctorti** [comment]
> 
> 
> Hello @kaspermarstal & @tvessiere
> I tried the method you guys mentioned on the above, but it apears an new error like this
> `
> 
> ```
>     LinearInterpolator(index 1) - This component is not installed!
>    ERROR: error occurred while creating Interpolator 0.
>     itk::ExceptionObject (000000000023E198)
>      Location: "unknown" 
>     File: C:\Elastix\src\Core\Kernel\elxElastixMain.cxx
>     Line: 819
>     Description: itk::ERROR: ElastixMain(00000000004AC450): The following component could not be 
>     created: LinearInterpolator
> 
>     ERROR:
>     One or more components could not be created.`
> ```
> 
> and here is my C++ code:
> 
> `
> 
> ```
> sitk::SimpleElastix elastixTest;
> 
>     elastixTest.SetParameterMap(sitk::GetDefaultParameterMap("rigid"));  
> 
>     elastixTest.AddParameterMap(sitk::GetDefaultParameterMap("affine"));
> 
> elastixTest.SetParameter("Registration", "AdvancedImageToImageMetric");
> 
> elastixTest.SetParameter("Interpolator", "BSplineInterpolator");
> 
> elastixTest.SetParameter("Metric", ("NormalizedMutualInformation", "CorrespondingPointsEuclideanDistanceMetric"));
> 
> elastixTest.SetParameter("Metric0Weight", "0.0");
> 
> elastixTest.SetParameter("MaximumNumberOfIterations", "6000");
> 
> elastixTest.SetParameter("NumberOfSpatialSamples", "6000");
> 
> elastixTest.PrintParameterMap();
> 
>     elastixTest.SetFixedPointSetFileName("Test_landmark.txt");
> 
>     elastixTest.SetMovingPointSetFileName("TestMove_landmark.txt");
> 
>     elastixTest.Execute();`
> ```
> 
> and after I change the Interpolator to BSplineInterpolator
> `elastixTest.SetParameter("Interpolator", "BSplineInterpolator");`
> The old error same with @tvessiere about AdvancedImageToImageMetric is still exist.
> Do you have any idea about what should I do ?
> Thanks so much~

It might be too late to be of help, but for the potential benefit of others, it appears that 'AdvancedImageToImageMetric' does not exist within Elastix.  I've searched both the [SimpleElastix](https://simpleelastix.readthedocs.io) and [Elastix](https://elastix.lumc.nl/download/elastix-5.0.1-manual.pdf) manuals and I've not been able to find any resolution (or other) parameter with that name.
