### ISSUE TITLE
missing complex types in Python bindings when built via conda recipe

### ISSUE THREAD

**Issue by lebedov** [SuperElastix/SimpleElastix#77]
I tried building SimpleElastix via rev d989261 of the in-progress [conda recipe](https://github.com/almarklein/staged-recipes/commit/d98926140f2adc4e3e4797d8c30416de36ad812e) on MacOS 10.11.6. Although the resulting conda package mostly works, the included import test failed during the build. I also had to comment out the mappings to/from sitkComplexFloat32 and sitkComplexFloat64 in SimpleITK.py as those symbols did not appear to exist.

**Comment by kaspermarstal** [comment]
Thank you very much for trying it out @lebedov and thanks for your feedback! I will fix up these last issues

**Comment by kaspermarstal** [comment]
Did you build it locally or via conda-forge? Most builds I see on conda-forge still time out

**Comment by lebedov** [comment]
Locally.

**Comment by kaspermarstal** [comment]
How do you setup the conda-forge build locally?

**Comment by lebedov** [comment]
I added `conda-forge` to the channels in my `~/.condarc` file and ran `conda build .` in the subdir containing the recipe.

**Comment by kaspermarstal** [comment]
Closing since the conda-forge build approach has been abandoned due to build time.
