### ISSUE TITLE
No output from sitk.PrintParameterMap()

### ISSUE THREAD

**Issue by rcasero** [SuperElastix/SimpleElastix#80]
Hi,

I built and installed SimpleElastix for python 3.x (I noted the steps [here](https://github.com/rcasero/pysto/wiki/Build-and-install-SimpleElastix-for-python-3.x)).

This snippet

    import SimpleITK as sitk
    
    # get parameter map template
    p = sitk.GetDefaultParameterMap('bspline')
    
    # set registration parameters
    p['WriteIterationInfo'] = ['true']
    p['DefaultPixelValue'] = ['0']
    p['Transform'] = ['BSplineTransform']
    p['FinalGridSpacingInPhysicalUnits'] = ('4',)
    p['GridSpacingSchedule'] = ['50', '25', '10']
    p['NumberOfResolutions'] = ['3']
    p['MaximumNumberOfIterations'] = ['512']
    
    for keys,values in p.items():
        print(keys)
        print(values)

extracts the parameters as expected

    AutomaticParameterEstimation
    ('true',)
    CheckNumberOfSamples
    ('true',)
    DefaultPixelValue
    ('0',)
    ...

However, if I run sitk.PrintParameterMap(), I get no output, with either of the following

    sitk.PrintParameterMap(sitk.GetDefaultParameterMap('bspline'))
    sitk.PrintParameterMap(p)

**Comment by kaspermarstal** [comment]
Hi, thanks for letting me know. I have previously encountered problems with writing to std::out from wrapped Python particularly in the Spyder IDE. In what environment are you running your code?

**Comment by rcasero** [comment]
In Spyder3.

On 15 Mar 2017 09:29, "Kasper Marstal" <notifications@github.com> wrote:

Hi, thanks for letting me know. I have previously encountered problems with
writing to std::out from wrapped Python particularly in the Spyder IDE. In
what environment are you running your code?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kaspermarstal/SimpleElastix/issues/80#issuecomment-286686982>,
or mute the thread

**Comment by kaspermarstal** [comment]
It seems to be a known issue in Spyder (e.g. http://stackoverflow.com/questions/20767639/stdout-from-a-c-program-in-spyder and https://github.com/spyder-ide/spyder/issues/2860). In https://github.com/spyder-ide/spyder/issues/2860 the guy can flush std::out within Python using `import sys; sys.stdout.flush()`. Does this work for you? It is not immediately obvious to me how to fix it from the SimpleElastix side.

**Comment by rcasero** [comment]
Many thanks for the suggestion, but it doesn't seem to work for me :(

**Comment by rcasero** [comment]
I did a bit more digging. We have the following code in `python3 myfile.py`

    p = sitk.GetDefaultParameterMap('bspline')
    elastix = sitk.SimpleElastix()
    elastix.PrintParameterMap(p)

Running from spyder3, we get

    Out[55]: <SimpleITK.SimpleITK.SimpleElastix; proxy of <Swig Object of type 'itk::simple::SimpleElastix *' at 0x7f25662f9e70> >

Running from the bash `python3 myfile.py`

    Self (0x4b568b0)
      RTTI typeinfo:   elastix::ParameterObject
      Reference Count: 1
      Modified Time: 82790
      Debug: Off
      Object Name: 
      Observers: 
        none
    ParameterMap 0: 
      (AutomaticParameterEstimation "true")
      (CheckNumberOfSamples "true")
      ...

On the other hand, the code

    sitk.PrintParameterMap(p)

does not produce any output, whether on python3 or the bash.

**Comment by PertuyF** [comment]
Hi @rcasero 

Sorry for the delay, I just saw your issue.
Did you found a solution?

In Spyder2 I was used to see the output of former `selx.PrettyPrint(p)` in the standard Python console instead of the IPython console. And it was the same for all `selx` outputs with `selx.LogToConsoleOn()`.
I think `PrintParameterMap` is the same function renamed, so maybe you could check there.

**Comment by kaspermarstal** [comment]
@PertuyF @rcasero Can confirm, they are the same functions, just renamed.

**Comment by PertuyF** [comment]
@kaspermarstal I just found an info that could help with these `sys.stdout.flush()` problems in Python3

> Note: stdout.flush() does not flush C stdio buffers on Python 3 where I/O is implemented directly on read()/write() system calls. To flush all open C stdio output streams, you could call libc.fflush(None) explicitly if some C extension uses stdio-based I/O

Details [here](https://stackoverflow.com/questions/4675728/redirect-stdout-to-a-file-in-python/22434262#22434262)

**Comment by kaspermarstal** [comment]
Nice digging @PertuyF! I don't know if this can be implemented in the SWIG layer on our side though, or if users will have to always call fflush themselves.
