### ISSUE TITLE
Single resolution registration

### ISSUE THREAD

**Issue by rdg-clearbridge** [SuperElastix/SimpleElastix#83]
I have a registration problem in which I need to do a simple rigid transform of images primarily composed of thousands of small particles. Where there is some underlying low-frequency structure, simpleElastix works well, however fail with just particles.

I am assuming this is because I am using the default MultiResolutionRegistration which is initially ignoring the high frequency information. I expect I would have better luck by starting with a single resolution registration at the highest resolution possible. However, I can't find anything in the documentation about this or any alternatives to MultiResolutionRegistration.

**Comment by gdhugo** [comment]
Unless you have a high degree of overlap in the particles, or you can make them 'fuzzy' enough to overlap using the multi-resolution approach, this type of image may not register well with an image-based approach such as SimpleElastix. 

For point-based rigid registration, the classic approach is iterative closest points, which is implemented in ITK. If the particles can be easily segmented in the image (e.g., if you can simply threshold the image to identify the particle locations), you might be better off using such a method. Here is an [example](https://itk.org/Doxygen/html/Examples_2RegistrationITKv4_2IterativeClosestPoint3_8cxx-example.html). I'm not sure if this is implemented in SimpleITK or not, though.

**Comment by PertuyF** [comment]
@rdg-clearbridge Note that if you set the number of resolutions to `1` ElastiX will register your images in full resolution, which in your case may work. And maybe changing the metric to cross-correlation (`AdvancedNormalizedCorrelationMetric`) may help if the pattern is very similar from an image to another.

I encountered one case were ElastiX was less appropriate that a basic cross-correlation, which you can test very quickly using [scikit-image register_translation](http://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.register_translation). Note that this implementation only computes translations, but you can get the rotation too if you transform your images to polar coordinates and perform cross-correlation again (you'll even get the scaling if you use log-polar transform).

Another solution would be to extract some particles coordinates from your images (convert image to binary, analyse particles and get central coordinates for each) and register the points sets with ElastiX. But it may be tricky to automate depending on your images.
