### ISSUE TITLE
import error in Ubuntu 16.04 

### ISSUE THREAD

**Issue by franfcunha** [SuperElastix/SimpleElastix#89]
Hello,
After following the procedure presented in the docs with sudo python setup.py install in the desired virtual environment I listed with conda list getting, in fact a row regarding SimpleElastix:
       SimpleElastix             0.10.0rc1.dev812+g7e302           <pip>
I already installed SimpleITK with conda install method and I am being able to import it but for example the method Elastix() is not available from the list of autocompletation methods belonging to sitk...
But when i rely only on the sudo python setup.py install and when in python i import SimpleITK:

File "/home/franfcunha/anaconda3/envs/p34/lib/python3.4/site-packages/SimpleITK/SimpleITK.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/franfcunha/anaconda3/envs/p34/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1715, in load_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
**ImportError: /home/franfcunha/anaconda3/envs/p34/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/franfcunha/anaconda3/envs/p34/lib/python3.4/site-packages/SimpleITK/_SimpleITK.so)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/franfcunha/anaconda3/envs/p34/lib/python3.4/site-packages/SimpleITK/__init__.py", line 1, in <module>
    from .SimpleITK import *
  File "/home/franfcunha/anaconda3/envs/p34/lib/python3.4/site-packages/SimpleITK/SimpleITK.py", line 21, in <module>
    _SimpleITK = swig_import_helper()
  File "/home/franfcunha/anaconda3/envs/p34/lib/python3.4/site-packages/SimpleITK/SimpleITK.py", line 20, in swig_import_helper
    return importlib.import_module('_SimpleITK')
  File "/home/franfcunha/anaconda3/envs/p34/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_SimpleITK'

Please any help would be appreciated...

**Comment by kaspermarstal** [comment]
Some googling reveals that anaconda ships its own OpenMP library which may conflict with the system OpenMP used at the compilation stage. I will disable OpenMP by default to avoid situations like this in the future. Stay tuned.

**Comment by franfcunha** [comment]
Thanks for reply,
I reproceed with the steps of the documentation, and so cloning and rebuilding SimpleElastix.
After sudo python setup.py install, SimpleITK was added to the site-packages folder of system, but not in the 3.5 version but on the 2.7.
I then copied the folder SimplTK and egg file of SimpleElastix to the site-packages folder of my virtual conda environment and when importing SimpleITK:

**ImportError: /home/franfcunha/anaconda3/envs/p34/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/franfcunha/anaconda3/envs/p34/lib/python3.4/site-packages/SimpleITK/_SimpleITK.so)**

What is missing this time? The building process also did not fished correctly without errors. I can not figured out what is going on, it has being really hard to install it properly in my system...

**Comment by kaspermarstal** [comment]
You need to make sure that the build system picks up the Python version for which you wish to compile SimpleElastix. Assuming you want to use 3.5 (or is it 3.4 as the error suggest?), you should either 1) make sure Python 3.5 is listed _first_ in your PATH environment variable, 2) create and activate a Python 3.5 virtual environment prior configuring cmake (the `cmake path/to/source` command) or by manually setting the `PYTHON_EXECUTABLE`, `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` CMake variables. On my machine they are `/Users/kasper/anaconda/bin/python`, `/Users/kasper/anaconda/include/python2.7` and `/Users/kasper/anaconda/lib/libpython2.7.dylib` respectively. I am on a mac so it will be different from you, but at least you have something to build on.

Copying files across Python versions is not recommended. That is bound to go wrong.

You also say `building process also did not fished correctly without errors`. What errors are you seeing? I am in the middle of validating the fix for the OpenMP error you mentioned above.

**Comment by franfcunha** [comment]
Approximately at 60% of building process i get:

collect2: error: ld returned 1 exit status
Wrapping/Tcl/CMakeFiles/SimpleITKTclsh.dir/build.make:608: recipe for target 'Wrapping/Tcl/bin/SimpleITKTclsh' failed
make[5]: *** [Wrapping/Tcl/bin/SimpleITKTclsh] Error 1
CMakeFiles/Makefile2:3855: recipe for target 'Wrapping/Tcl/CMakeFiles/SimpleITKTclsh.dir/all' failed
make[4]: *** [Wrapping/Tcl/CMakeFiles/SimpleITKTclsh.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:118: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kaspermarstal** [comment]
Could you try to run it with just `make -j1`? The error messages may be easier to discern when not intertwined from different threads. It also looks like some linker error messages at the top were left out. I could be wrong, but if not can you post all error messages? 

If you are not using the Tcl wrapping you can just set WRAP_TCL to OFF. That doesn't solve the original problem of course, but you could move on and use the Python bindings.

I admire your persistence! Keep it up! 😆

**Comment by franfcunha** [comment]
Dear Kasper I am so sorry for this inconvenience,
The fact is that SimpleElastix seems to be the best way to accomplish my to do work...
So, I've followed your instructions and here it is the building error:

[ 37%] BuildTime Configuration of /home/franfcunha/SimpleElastix/Wrapping/Python/Packaging/setup.py.in to /home/franfcunha/build/SimpleITK-build/Wrapping/Python/Packaging/setup.py
[ 37%] Built target ConfigureFileBuildtime
Scanning dependencies of target PythonVirtualEnv
[ 37%] Creating python virtual enviroment...
Already using interpreter /home/franfcunha/anaconda3/envs/p34/bin/python
Not deleting /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin
Using base prefix '/home/franfcunha/anaconda3/envs/p34'
New python executable in /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python
ERROR: The executable /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python is not functioning
ERROR: It thinks sys.prefix is '/home/franfcunha/SimpleElastix/Wrapping/Python' (should be '/home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv')
ERROR: virtualenv is not compatible with this system or executable
CMake Error at PythonVirtualEnvInstall.cmake:40 (message):
  Creation of Python virtual enviroment failed.

  
  /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python:
  error while loading shared libraries: libpython3.4m.so.1.0: cannot open
  shared object file: No such file or directory



Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/build.make:61: recipe for target 'Testing/Installation/PythonVirtualenv/bin/python' failed
make[5]: *** [Testing/Installation/PythonVirtualenv/bin/python] Error 1
make[5]: *** A apagar ficheiro 'Testing/Installation/PythonVirtualenv/bin/python'
CMakeFiles/Makefile2:3420: recipe for target 'Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all' failed
make[4]: *** [Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:118: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I must remind you that I activated my Conda virtual environment python3.4 prior to the "call" cmake in the terminal. I hope this post can be clear to understand what the hell can be going on my machine.

Thank you so much!

**Comment by kaspermarstal** [comment]
What happens if you do not have virtualenv activated when you call cmake, but activate the virtual env prior to `sudo python setup.py install`?

Alternatively, [these guys](https://github.com/conda/conda/issues/1367) suggest that downgrading to Python 2.7  with `conda install python=2.7.9` solves the problem.

**Comment by PertuyF** [comment]
Hi @franfcunha , I did compile SimpleElastiX under xUbuntu 14.04 a while ago, so things may have changed, but I was able to link the project to the desired python executable and libraries (it was a py34 from conda env) using the CMake GUI, then compile.

Once the project has been compiled for the right python version, you should be able to activate the environment and then install the package, as @kaspermarstal suggested.

**Comment by franfcunha** [comment]
@kaspermarstal one thing that I realized is that independently of having or not my p34 env activated, when sudo python setup.py install it writes SimpleITK folder and SimpleElastix1.0.0.rc(...) in my system python's dist-packages folder.

@PertuyF, one naive question ( i am sorry!): how can i " compile the project for the right python version" using my terminal?

**Comment by franfcunha** [comment]
So another try another error, my goodness, at least is becoming closer to 100% ahahah
I did not activate my p34 virtual environment and followed the superbuild method without any tcl,csharp and lua wraps. The result:

[ 73%] Linking CXX executable ../../bin/DemonsRegistration2
Already using interpreter /home/franfcunha/anaconda3/bin/python
Not deleting /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin
Using base prefix '/home/franfcunha/anaconda3'
New python executable in /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python
ERROR: The executable /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python is not functioning
ERROR: It thinks sys.prefix is '/home/franfcunha/SimpleElastix/Wrapping/Python' (should be '/home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv')
ERROR: virtualenv is not compatible with this system or executable
CMake Error at PythonVirtualEnvInstall.cmake:40 (message):
  Creation of Python virtual enviroment failed.

  
  /home/franfcunha/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python:
  error while loading shared libraries: libpython3.6m.so.1.0: cannot open
  shared object file: No such file or directory



Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/build.make:61: recipe for target 'Testing/Installation/PythonVirtualenv/bin/python' failed
make[5]: *** [Testing/Installation/PythonVirtualenv/bin/python] Error 1
make[5]: *** A apagar ficheiro 'Testing/Installation/PythonVirtualenv/bin/python'
CMakeFiles/Makefile2:3414: recipe for target 'Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all' failed
make[4]: *** [Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all] Error 2
make[4]: ** Esperando que outros processos terminem.
[ 73%] Built target DemonsRegistration2
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:118: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kaspermarstal** [comment]
@franfcunha As for your first question, you are probably right, it only depends on the virtual environment that is activated when you install Python, not when you run CMake.

Perhaps you can try to build with the SimpleITK_USE_SYSTEM_VIRTUALENV set to ON? You could also try to set BUILD_TESTING to OFF. At this point we just want to get you up and running with the Python wrappings.

I am sorry I cannot provide more concrete advise at this point. It is difficult to debug from a distance.

**Comment by franfcunha** [comment]
Thank you again for your reply,
Please, just let me ask where to turn SimpleITK_USE_SYSTEM_VIRTUALEV to ON. On my ccmake menu, i only have the following variables: Building_examples, building_testing, cmake_build_tipe, cmake_install_prefix and the languages wraps...

**Comment by kaspermarstal** [comment]
Press `T` to show all options 😊

**Comment by franfcunha** [comment]
brand new error still in building process :( Jesus, how hard can be to use SimpleElastix?

[ 65%] Linking CXX executable ../../bin/SimpleITKUnitTestDriver6
[ 65%] Built target SimpleITKUnitTestDriver6
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:118: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kaspermarstal** [comment]
Your error log does not contain the the actual error. Run `make` on only one thread (i.e. without `-j` ), and it will be clearer where the error occurs. 

You can also set BUILD_TESTING to OFF to avoid compiling tests.

**Comment by franfcunha** [comment]
Dear Kasper,
I already set BUILD_TESTING to OFF several times, but the building process still crashes when SimpleITK unit test driver is performed. I understood your point asking me to use just one thread but i am losing my mind trying to install this tool and time to do it is starting to be a really important variable to me.

Did anyone face so much problems trying to build simple elastix in ubuntu 16.04; such amount of fails only happened with me? i am starting to feel that something is really wrong with my machine...

**Comment by kaspermarstal** [comment]
If you set it to OFF it should not build testing at all. Sometimes it helps just to start from an empty folder, adjust the settings we discussed, and rebuild from scratch. CMake can be little unpredictable  when settings are changed in the middle of a build.

**Comment by middleAgedHacker** [comment]
@franfcunha How did you resolve this issue? I'm having the same problem.

**Comment by radao** [comment]
@franfcunha Same problem as well.

**Comment by franfcunha** [comment]
I did not continue with simple elastix. I moved directly to Elastix
Terminal executable...

2017-10-10 13:44 GMT+01:00 radao <notifications@github.com>:
