### ISSUE TITLE
ElastixImageFilter

### ISSUE THREAD

**Issue by unimusic** [SuperElastix/SimpleElastix#92]
Hi Kasper,

Sorry to bother you more, but I am struggling to set a fixed and moving image mask for the ElastixImageFilter. Right now, I am creating a numpy array of 0's and 1's (ints) and calling mask_img = sitk.GetImageFromArray(numpy_mask) to the numpy array, followed by elastixImageFilter.SetMovingMask(mask_img). This gives me the error "Moving mask must be of pixel type unsigned char (moving mask at index 0 is of type "long")." Please advise.

Thanks!

Angela

**Comment by kaspermarstal** [comment]
Hi Angela,

You have to cast the image to an unsigned char. You can do it like this:

    sitk.Cast(mask, sitk.sitkUInt8)

The error message could be more helpful. I must admit. Will change that :)

**Comment by unimusic** [comment]
Ah, wonderful. Thanks!
