### ISSUE TITLE
Super build failed on Ubuntu 

### ISSUE THREAD

**Issue by giacomomarchioro** [SuperElastix/SimpleElastix#93]
I have tried to build it using Superbuild following:

- [x] $ git clone https://github.com/kaspermarstal/SimpleElastix
- [x] $ mkdir build
- [x] $ cd build
- [ ] $ cmake ../SimpleElastix/SuperBuild  

Last command produces this error:  

-- Checking if c++11 is required...
-- Checking if c++11 is required... NO
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found Java: /usr/lib/jvm/java-8-oracle/bin/java (found version "1.8.0.131") found components:  Development Runtime 
-- Found JNI: /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjawt.so  
-- Could NOT find BISON (missing:  BISON_EXECUTABLE) 
-- Passing variable "SITK_CHECK_CXX11=TRUE" to SimpleITK external project.
-- Passing variable "SimpleITK_4D_IMAGES=OFF" to SimpleITK external project.
-- Passing variable "SimpleITK_GIT_PROTOCOL=https" to SimpleITK external project.
-- Passing variable "SimpleITK_LUA_EXECUTABLE=/home/opdate/build/Lua/bin/lua" to SimpleITK external project.
-- Passing variable "SimpleITK_OPENMP=OFF" to SimpleITK external project.
-- Configuring incomplete, errors occurred!
See also "/home/opdate/build/CMakeFiles/CMakeOutput.log".

Attacched here:
[CMakeOutput.txt](https://github.com/SuperElastix/SimpleElastix/files/1018175/CMakeOutput.txt)

**Comment by kaspermarstal** [comment]
It looks like your environment is missing `bison` which is a unix utility that SimpleITK uses to parse text files. Information on how to install bison can be found here:

http://ccm.net/faq/30635-how-to-install-flex-and-bison-under-ubuntu
https://askubuntu.com/questions/557629/how-to-install-flex-and-bison-error-can-not-locate-file

Let me know how it goes!

**Comment by giacomomarchioro** [comment]
Thanks for the quick reply. It solved the issue.  This is the procedure followed:

1. Delete the previous built attempt
2. sudo apt-get update 
3. sudo apt-get upgrade 
4. sudo apt-get install flex bison
5. reboot 
6. mkdir SEla
7. cd SEla

From now on I followed the procedure described in the documentation and in the previous tread.
