### ISSUE TITLE
Register numpy arrays and output numpy arrays 

### ISSUE THREAD

**Issue by giacomomarchioro** [SuperElastix/SimpleElastix#94]
I've got two numpy arrrays one is smaller than the other it captures only a portion (a ROI) of the sample that is captured with the other. I would like to register them and to return a numpy array.  
 
```
import numpy as np
import SimpleITK as sitk


#TEST DATA
testarray = np.array(range(36)).reshape(6,6)
croparr = testarray[2:,4:]
zero = np.zeros(36).reshape(6,6)

#Fixed 
ta = sitk.GetImageFromArray(testarray)
#Small array to register
tb = sitk.GetImageFromArray(croparr)
#Same dimension of the fixed array but zeros in others positions 
zero[:4,:2] = croparr
tc = sitk.GetImageFromArray(zero) #same dimension of ta


import SimpleITK as sitk

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.LogToConsoleOn()
elastixImageFilter.SetFixedImage(ta)
elastixImageFilter.SetMovingImage(tb)
elastixImageFilter.SetParameterMap(sitk.GetDefaultParameterMap("rigid"))
elastixImageFilter.Execute()
res = elastixImageFilter.GetResultImage()
hi = sitk.GetArrayFromImage(res)
```

But I've got this error:

> Traceback (most recent call last):
> 
>   File "<ipython-input-1-a4d6d82ea9bd>", line 1, in <module>
>     runfile('/home/opdate/Desktop/Python Script/SimpleITK_example.py', wdir='/home/opdate/Desktop/Python Script')
> 
>   File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
>     execfile(filename, namespace)
> 
>   File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
>     builtins.execfile(filename, *where)
> 
>   File "/home/opdate/Desktop/Python Script/SimpleITK_example.py", line 32, in <module>
>     elastixImageFilter.Execute()
> 
>   File "/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.py", line 10102, in Execute
>     return _SimpleITK.ElastixImageFilter_Execute(self)
> 
> RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /home/opdate/SEla/SimpleElastix/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:208:
> sitk::ERROR: 
> itk::ExceptionObject (0x4dfb7b0)
> Location: "unknown" 
> File: /home/opdate/SEla/build/Elastix/src/Core/Main/elxElastixFilter.hxx
> Line: 240
> Description: itk::ERROR: Self(0x3a29f90): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

Thanks for your help. 

Best regards, 
GM

**Comment by PertuyF** [comment]
Hi @giacomomarchioro ,

Do you execute this script in a standard python console or in iPython ?
You should find more details in the ElastiX log, that output to the (standard) python console when using `elastixImageFilter.LogToConsoleOn()`.
If needed you can use `elastixImageFilter.LogToFileOn()` that should create a log file in your output directory.

Come back with these info and debugging will (probably) be easier :)

**Comment by zwep** [comment]
For anyone that lands here..  and wants to reproduce this example

https://github.com/SuperElastix/SimpleElastix/issues/86

sitk.ElastixImageFilter() is no more, it is now called with sitk.SimpleElastix()
