### ISSUE TITLE
Error building the solution

### ISSUE THREAD

**Issue by LauraCarretero** [SuperElastix/SimpleElastix#96]
Hi, I'm trying to install SimpleElastix. When I reach almost the 70% of the process I get the following error:

Cloning into 'Elastix'...

Then, a prompt appears and I must sign in github. 

remote: Repository not found.
fatal: repository 'https://github.com/mstaring/elastix/' not found

I don't know why it's trying to clone the repository again. It happens to me installing it on Linux, using the command line and on windows, using Visual Studio 2013. I rather install it on Windows. 

I have sought for that repository and it does not exist, it has been moved to https://github.com/SuperElastix/elastix.

Do you know what can I do?

Thank you in advance!

**Comment by kaspermarstal** [comment]
Hi Laura, the elastix repo has been moved from SVN to Github and unfortunately the old elastix mirror was removed in the process. Simply do `git pull` to get the latest update and rebuild the project. Let me know how it goes!

**Comment by cat2tom** [comment]
Hi Kaspermrstal, Thanks for developing this fantastic tool and answer the question.  I have the same issue.  I have 64 bit python 2.7 installed on Win7. What version of VS you recommended to build python wrap. Vs2012 profession is ok? or need vs 2015? 

Thanks, tom

**Comment by kaspermarstal** [comment]
I hope you will find it useful! For Python 2.7 you should actually use Visual Studio 2008 which comes with the Visual C++ 9.0 (https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Build_Tools_for_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29).

**Comment by sofroniewn** [comment]
Hi @kaspermarstal 
I'm trying to install on my macOSX, but running into an error at 55%

```[ 55%] Completed 'ITK'
[ 55%] Built target ITK
make: *** [all] Error 2```

I'm not sure how to proceed. If I rerun make again I get the following error

```[  1%] Generating /Users/sofroniewn/Github/SimpleElastix/build/ExternalData/.ExternalSource/lua-5.1.5.tar.gz
-- Found object: "/Users/sofroniewn/Github/SimpleElastix/build/ExternalData/Objects/MD5/2e115fe26e435e33b0d5c022e4490567"
[  2%] Generating /Users/sofroniewn/Github/SimpleElastix/build/ExternalData/.ExternalSource/pcre-8.37.tar.gz
-- Found object: "/Users/sofroniewn/Github/SimpleElastix/build/ExternalData/Objects/MD5/6e0cc6d1bdac7a4308151f9b3571b86e"
[  3%] Generating /Users/sofroniewn/Github/SimpleElastix/build/ExternalData/.ExternalSource/swig-3.0.11.tar.gz
-- Found object: "/Users/sofroniewn/Github/SimpleElastix/build/ExternalData/Objects/MD5/13732eb0f1ab2123d180db8425c1edea"
[  5%] Generating /Users/sofroniewn/Github/SimpleElastix/build/ExternalData/.ExternalSource/googletest-release-1.8.0.tar.gz
-- Found object: "/Users/sofroniewn/Github/SimpleElastix/build/ExternalData/Objects/MD5/16877098823401d1bf2ed7891d7dce36"
[  6%] Generating /Users/sofroniewn/Github/SimpleElastix/build/ExternalData/.ExternalSource/virtualenv-15.1.0.tar.gz
-- Found object: "/Users/sofroniewn/Github/SimpleElastix/build/ExternalData/Objects/MD5/44e19f4134906fe2d75124427dc9b716"
[  6%] Built target SuperBuildSimpleITKSourceReal
[  6%] Built target SuperBuildSimpleITKSource
[ 16%] Built target Lua
[ 26%] Built target virtualenv
[ 36%] Built target ITK
[ 48%] Built target GTest
[ 49%] Performing build step for 'PCRE'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [PCRE-prefix/src/PCRE-stamp/PCRE-build] Error 2
make[1]: *** [CMakeFiles/PCRE.dir/all] Error 2
make: *** [all] Error 2```

Any ideas on how to proceed? I tried updating my xcode.

Thanks so much for your time, Nick

**Comment by sofroniewn** [comment]
This issue, 
https://github.com/SimpleITK/SimpleITK/issues/79
may be relevant, but I still can't get it working

**Comment by kaspermarstal** [comment]
Hi @sofroniewn take a look here: https://simpleelastix.readthedocs.io/GettingStarted.html#pcre-perl-compatible-regular-expression-build-fails-on-mac-os-x. Sorry for the late reply.

**Comment by sofroniewn** [comment]
Great - that has helped a lot, I can now get most of the way through the install (sorry for not seeing that on the website tip earlier). I still run into this error

'''
[ 77%] Linking CXX executable ../../bin/SimpleITKUnitTestDriver5
[ 77%] Built target SimpleITKUnitTestDriver5
[ 77%] Built target org_itk_simple_jar
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
'''

But now the build is far enough along that 'SimpleITK-build/Wrapping/Python/Packaging' and I can run SimpleElastix from python. I'm not sure if I'm missing some important parts though.

**Comment by kaspermarstal** [comment]
The build is failing earlier than this. It is probably the Examples or one of the language wrappings that fails, but if the python package is there, then you have the complete python package. If you want to continue debugging this issue, post the log from running make with one job, i.e. `make -j1`, if you are happy with just the python package, you can close the issue :)

**Comment by sofroniewn** [comment]
Just the python package is fine with me. I'm not sure I have permissions to close this issue though. Thanks
