### ISSUE TITLE
python finds SimpleITK but not SimpleElastix

### ISSUE THREAD

**Issue by romangrothausmann** [SuperElastix/SimpleElastix#99]
After compiling and installing SimpleElastix@d6eaa (current master), python seems to find SimpleITK but not SimpleElastix:

```
PYTHONPATH=/opt/SimpleElastix/lib/python/:$PYTHONPATH python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import SimpleITK as sitk
>>> selx = sitk.SimpleElastix()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SimpleElastix'
```

The last SimpleElastix I used (SimpleElastix@7e302, end of 2016) just worked fine. Also if I recompile SimpleElastix@7e302 now, all works. Any idea what could cause the problem for current master?

**Comment by kaspermarstal** [comment]
`SimpleElastix` was renamed to `ElastixImageFilter` to align with the SimpleITK naming scheme. Similarly, `SimpleTransformix` was renamed to `TransformixImageFilter`. Does this solve your issue?

**Comment by romangrothausmann** [comment]
It does. Many thanks for that hint. Perhaps worth mentioning in the next release info.

**Comment by rubiha** [comment]
Hi

I attempted using elastix in python. I first used SimpleITK.Elastix and after reading this discussion I also tried SimpleITK.ElastixImageFilter
Neither worked.
I got the following error message:
AttributeError: 'module' object has no attribute 'ElastixImageFilter'

any ideas as for what is wrong?
